.eslintrc.json, .github/pull_request_template.md, .gitignore, README.md, package.json, public/index.html, public/manifest.json
[OCL-4: Project Initialization And SetUp](https://issues.openmrs.org/browse/OCL-4)
This contains the initial setup of the project with the development environment and a Readme
=> OCL-4: Project Initialization And SetUp

Dockerfile
[OCLOMRS-9](https://issues.openmrs.org/projects/OCLOMRS/issues/OCLOMRS-9)
The Dockerfile will ensure that a new docker image for the project is created after every merge to the master branch. This is important for continuous integration of the project in the production environment.
=> OCLOMRS-9: Docker set-up

.eslintrc.json, .gitignore, package-lock.json, package.json, public/index.html, src/ActionCreators/AuthActionCreators.js, src/Actions/AuthActions.js, src/App.css, src/App.js, src/Reducers/AuthReducers.js, src/Reducers/Index.js, src/__tests__/App.test.js, src/__tests__/AuthActions.test.js, src/__tests__/AuthReducers.test.js, src/__tests__/Login.test.js, src/__tests__/__snapshots__/Login.test.js.snap, src/components/Dashboard.js, src/components/Login.js, src/components/Navbar.js, src/index.css, src/index.js, src/setupTests.js
[OCLOMRS-5: Authentication Login UI implementation](https://issues.openmrs.org/browse/OCLOMRS-5)
This PR includes:
-  The login UI
- The login logic 
- And login tests
=> OCLOMRS-5: Authentication Login UI implementation

README.md
[OCLOMRS-11: Modify ReadMe](https://issues.openmrs.org/browse/OCLOMRS-11)
This PR adds the development steps in the ReadMe, tells the user how to set up the project inorder to get it working locally in their browsers.
=> OCLOMRS: Modify ReadMe

.coveralls.yml, .travis.yml, README.md, package-lock.json, package.json
[OCLOMRS-13: Fix ReadMe.md file and Add coveralls.yml file](https://issues.openmrs.org/browse/OCLOMRS-13)
This pull request does the following;
- Fix the installation issue in the ReadMe.md that was raised by a colleague
- Add the coveralls.yml file 
- should code coverage after Travis has finished running
=> OCLOMRS-13: Fix ReadMe.md file and Add coveralls.yml file

README.md
[OCLOMRS-14: Fix ReadMe.md file](https://issues.openmrs.org/browse/OCLOMRS-14)
This fix is to ensure the ReadME.md file is well detailed for all users to have a good setUp process
=> OCLOMRS-14: Fix ReadMe.md file

Dockerfile, docker-compose.yml
[OCLOMRS-12](https://issues.openmrs.org/projects/OCLOMRS/issues/OCLOMRS-12?filter=allopenissues)
The docker-compose.yml file will ensure that the application docker container is able to interact with other docker containers. The docker file, on the other hand,is used to create, run and serve the docker image The task references the issue created by the infrastructure team  [ITSM-4148](https://issues.openmrs.org/browse/ITSM-4148) on the JIRA board
=> OCLOMRS-12: docker build set-up

package-lock.json, src/ActionCreators/AuthActionCreators.js, src/Actions/AuthActions.js, src/App.css, src/Reducers/AuthReducers.js, src/Reducers/Index.js, src/__tests__/AuthActions.test.js, src/__tests__/AuthReducers.test.js, src/__tests__/Loader.test.js, src/__tests__/Login.test.js, src/__tests__/Navbar.test.js, src/components/Dashboard.js, src/components/Loader.js, src/components/Login.js, src/components/Navbar.js
[OCLOMRS-16: Fix Login UI and add preloader](https://issues.openmrs.org/browse/OCLOMRS-16)
This PR fixes the Login component as advised during the demo: 
- the Login component is rendered as the index page.
- Adds a loader component that will show the user the progress when the request is being made.
- Implements logout
=> OCLOMRS-16: Fix Login UI, Add preloader and logout functionality

package-lock.json, package.json, src/App.js, src/components/Auth/index.jsx, src/components/Login.js, src/components/Navbar.js, src/redux/actions/auth/authActionCreators.js, src/redux/reducers/store.js, src/setupTests.js, src/tests/Auth/index.test.jsx, src/tests/__mocks__/FakeComponent.jsx, src/tests/__mocks__/fakeStore.js
[OCLOMRS-17: Protected access of urls](https://issues.openmrs.org/browse/OCLOMRS-17)
After a user logs in, the other urls or routes need to be private to ensure authentication and confidentiality.
=> OCLOMRS-17: Protect routes that require authentication

.eslintrc.json, .travis.yml, package-lock.json, package.json, src/ActionCreators/AuthActionCreators.js, src/Actions/AuthActions.js, src/App.js, src/Reducers/AuthReducers.js, src/Reducers/Index.js, src/__tests__/AuthActions.test.js, src/__tests__/Login.test.js, src/__tests__/Navbar.test.js, src/components/Dashboard.js, src/components/Login.js, src/components/Navbar.js, src/components/SideNavigation.js
Reverts openmrs/openmrs-ocl-client#22
=> Revert "Revert "OCLOMRS-21: Integrate Linting on CI and Prettier for better code""

src/App.js, src/components/dashboard/components/ListWrapper.jsx, src/components/dashboard/components/SearchBar.jsx, src/components/dashboard/components/SourceCard.jsx, src/components/dashboard/container/SourceSearch.jsx, src/components/dashboard/styles/index.css, src/redux/actions/sources/index.js, src/tests/Dashboard/container/SourceSearch.test.jsx
[Redesign sources page user interface](https://issues.openmrs.org/browse/OCLOMRS-40)
Redesign the source cards and remove the sort button from the search bar
=> OCLOMRS-40: Redesign sources page user interface

.eslintrc.json, src/App.js, src/components/dashboard/components/SourceCard.jsx, src/components/dashboard/components/concepts/SpecificConceptList.jsx, src/components/dashboard/components/concepts/SpecificConceptTable.jsx, src/components/dashboard/container/SpecificConcept.jsx, src/components/dashboard/styles/index.css, src/redux/actions/concepts/specificConceptAction.js, src/tests/Dashboard/action/specificConceptAction.test.js, src/tests/Dashboard/container/SpecificConcept.test.jsx
[OCLOMRS-32: A user should retrieve and search through all the concepts in a specific source](https://issues.openmrs.org/browse/OCLOMRS-32)
As a user, I should be able to view and search through all the concepts in a specific source.
=> OCLOMRS-32: A user should retrieve and search through all the concepts in a specific source

package-lock.json, src/App.js, src/components/login/components/SubmitButton.jsx, src/components/login/container/index.jsx, src/components/login/styles/index.css, src/tests/Login/container/index.test.jsx
[Fix login page UI](https://issues.openmrs.org/browse/OCLOMRS-45)
Redesign the login page - focus on the size of the form and the submit button. Also, use a custom stylesheet. This is to prevent the login page's design from changing if anyone alters the general stylesheet.
=> OCLOMRS-45: Fix login page UI

package-lock.json, src/components/dashboard/components/dictionary/DictionariesSearch.jsx, src/components/dashboard/components/dictionary/ListDictionaries.jsx, src/components/dashboard/container/DictionariesDisplay.jsx, src/redux/actions/dictionaries/dictionaryActionCreators.js, src/redux/actions/dictionaries/dictionaryActions.js, src/redux/actions/types.js, src/redux/api.js, src/tests/Dashboard/action/api.test.js, src/tests/Dashboard/action/dictionaryAction.test.js, src/tests/Dashboard/container/DictionaryDisplay.test.jsx, src/tests/Dictionary/DictionaryModal.test.jsx, src/tests/Navbar.test.js
[OCLOMRS-50](https://issues.openmrs.org/browse/OCLOMRS-50)
As a user, I should be able to search through dictionaries and get a particular dictionary. The search should be on the dictionaries dashboard and should return exact matches of what has been searched for in the search bar. The search results however only include the dictionaries created through OCL for OpenMRS.
=> OCLOMRS-50 : Adding search to the dictionaries component

src/App.js, src/components/dashboard/components/SideNavigation.jsx, src/components/dashboard/styles/index.css
[OCLOMRS-60: Rework on the side bar](https://issues.openmrs.org/browse/OCLOMRS-60)
Change the sidebar organization.
Indicate the active component.
Change the color of the sidebar.
=> OCLOMRS-60: Rework on the side bar

src/components/dashboard/container/SpecificConcept.jsx, src/components/dashboard/styles/index.css, src/redux/actions/concepts/ConceptActionCreators.js, src/redux/actions/types.js, src/redux/reducers/ConceptReducers.js, src/tests/Dashboard/container/SpecificConcept.test.jsx, src/tests/Dashboard/reducer/conceptReducer.test.js
[A user should be able to view paginated concepts in a particular source	
](https://issues.openmrs.org/browse/OCLOMRS-52)
As a user, I should be able to view paginated concepts in a particular source
=> OCLOMRS-52: A user should be able to view paginated concepts in a particular source

package-lock.json, src/App.js, src/components/dashboard/components/dictionary/DictionaryCard.jsx, src/components/dashboard/components/dictionary/DictionaryContainer.jsx, src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx, src/components/dashboard/components/dictionary/ListDictionaries.jsx, src/components/dashboard/components/dictionary/styles/dictionary-modal.css, src/components/dashboard/container/DictionariesDisplay.jsx, src/components/dashboard/styles/index.css, src/redux/actions/dictionaries/dictionaryActionCreators.js, src/redux/actions/dictionaries/dictionaryActions.js, src/redux/actions/types.js, src/redux/api.js, src/redux/reducers/dictionaryReducers.js, src/tests/Dashboard/action/dictionaryAction.test.js, src/tests/Dashboard/container/DictionaryDisplay.test.jsx, src/tests/Dashboard/reducer/dictionaryReducers.test.js, src/tests/Dictionary/DictionaryContainer.test.jsx
[OCLOMRS-47](https://issues.openmrs.org/browse/OCLOMRS-47)
As a user, I should be able to view all the details of a particular dictionary
=> OCLOMRS-47: A user should view details of a particular dictionary

package-lock.json, package.json, src/redux/reducers/store.js
[OCLOMRS-62: Fix Redux logger logging on production environment](https://issues.openmrs.org/browse/OCLOMRS-62)
The `redux-logger` logs on production environment which should not be so because of security reasons.
=> OCLOMRS-62: Fix Redux logger logging on production environment

src/components/dashboard/components/concepts/ConceptList.jsx, src/components/dashboard/components/concepts/ConceptModal.js, src/components/dashboard/components/concepts/ConceptTable.jsx, src/components/dashboard/components/concepts/SpecificConceptList.jsx, src/components/dashboard/components/concepts/SpecificConceptTable.jsx, src/components/dashboard/container/Concepts.jsx, src/components/dashboard/container/SpecificConcept.jsx, src/components/dashboard/styles/index.css, src/components/dictionaryConcepts/components/ConceptDropdown.jsx, src/tests/Dashboard/container/ConceptModal.test.js
[OCLOMRS-64: Implement the UI for Previewing a concept.](https://issues.openmrs.org/browse/OCLOMRS-64)
- This involves working on the UI that appears when a user selects the concept to be added to a dictionary.
- Create a modal that first shows the user all about the concept they are about to add to their dictionary.
=> OCLOMRS-64: Implement the UI for Previewing a concept.

src/components/dashboard/components/SideNavigation.jsx, src/components/dashboard/components/dictionary/DictionariesSearch.jsx, src/components/dashboard/components/dictionary/common/DictionaryModal.jsx, src/components/dashboard/container/DictionariesDisplay.jsx, src/components/dashboard/styles/index.css, src/tests/Dashboard/container/DictionaryDisplay.test.jsx, src/tests/Dictionary/DictionaryModal.test.jsx
[OCLOMRS-78: Move the Add dictionary button to the Dashboard](https://issues.openmrs.org/browse/OCLOMRS-78)
- This involves moving the dictionary button from the side Navigation bar to the Page where dictionaries display.
=> OCLOMRS-78: Move the Add dictionary button to the Dashboard

package-lock.json, src/components/dashboard/container/DictionariesDisplay.jsx
[OCLOMRS-74: Remove misleading information on the Dashboard.](https://issues.openmrs.org/browse/OCLOMRS-74)
A user should not find misleading information of the number of dictionaries that exist contradicting what is displayed.
=> OCLOMRS-74: Remove misleading information on the Dashboard.

src/components/dictionaryConcepts/components/ConceptDropdown.jsx
[OCLOMRS-83: Fix the url to get CIEL concepts.](https://issues.openmrs.org/browse/OCLOMRS-83)
Fix the url to view CIEL concepts to be added to the dictionary
=> OCLOMRS-83: Fix the url to get CIEL concepts.

src/App.js, src/components/dashboard/components/dictionary/DictionaryCard.jsx, src/components/dashboard/components/dictionary/DictionaryContainer.jsx, src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx, src/components/dashboard/components/dictionary/styles/dictionary-modal.css, src/components/dashboard/container/DictionariesDisplay.jsx, src/components/dashboard/styles/index.css, src/redux/actions/dictionaries/dictionaryActionCreators.js, src/redux/api.js, src/tests/Dashboard/action/dictionaryAction.test.js, src/tests/Dictionary/DictionaryContainer.test.jsx
[OCLOMRS-81: Fix A Bug In The Dictionary Details Component.](https://issues.openmrs.org/browse/OCLOMRS-81)
- Added a lifecycle method to load data into the component even after a page reload.
- Added a loader to display right before the data is fetched and loaded into the component.
=> OCLOMRS-81: Fix A Bug In The Dictionary Details Component.

src/App.css, src/components/NavBar/GeneralSearch.jsx, src/components/Navbar.js, src/components/dashboard/styles/index.css
[OCLOMRS-92: Create a new UI for the navigation bar](https://issues.openmrs.org/browse/OCLOMRS-92)
A user should be able to navigate to the different components through selection destinations from the navigation bar.
A user should have access to the general search on the navigation bar
=> OCLOMRS-92: Create a new UI for the navigation bar

src/App.js, src/components/dashboard/components/dictionary/DictionariesSearch.jsx, src/components/dashboard/components/dictionary/OwnerListDictionaries.jsx, src/components/dashboard/container/OwnerDictionary.jsx, src/components/dashboard/styles/index.css, src/redux/actions/dictionaries/dictionaryActionCreators.js, src/redux/reducers/util.js, src/tests/Dashboard/container/OwnerDisplay.test.jsx
[OCLOMRS-87: As a user, I should be able to see all public dictionaries](https://issues.openmrs.org/browse/OCLOMRS-87)
When a user clicks on see all public dictionary link in the user dashboard, the user should see a list of dictionaries created by the user and also by other people.
=> OCLOMRS-87: As a user, I should be able to see all public dictionaries

package-lock.json, package.json, src/redux/reducers/store.js
[OCLOMRS-104: Activate Redux Dev tools](https://issues.openmrs.org/browse/OCLOMRS-104)
Currently, the Redux dev tools are not activated, which does not allow the team to utilize the extension for connecting the browser to the Redux application to help in debugging and viewing the changes in Redux state and actions.
=> OCLOMRS-104: Activate Redux Dev tools

src/redux/actions/user/index.js
[Fix CORS errors](https://issues.openmrs.org/browse/OCLOMRS-106)
This is a bug fix. 
Due to a missing `/` at the end of some of the API endpoints consumed in [this ticket](https://issues.openmrs.org/browse/OCLOMRS-84), The requests are failing, therefore returning incomplete data in the dashboard while running on the production environment.
=> OCLOMRS-106: Fix CORS errors

src/components/dashboard/container/SpecificConcept.jsx, src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx
[OCLOMRS-105: Fix the link from concepts back to the dictionary](https://issues.openmrs.org/browse/OCLOMRS-105)
- Currently, it shows a 404 page because the URL is not found,  so this needs to be fixed.
=> OCLOMRS-105: Fix the link from concepts back to the dictionary

.gitignore, SAMPLE_ENV_FILE, src/components/login/container/LoginDetails.jsx, src/components/login/container/index.jsx, src/components/userDasboard/components/DashboardDetails.jsx, src/config/axiosConfig.js, src/config/index.js, src/redux/actions/auth/authActions.js
[Create environment variables to hold base urls](https://issues.openmrs.org/browse/OCLOMRS-108)
The current base URLs are meant to be used in development mode alone. At some point, the URLs will be replaced with live URLs meant for production. Create a `.env` file to store these URLs so that it can be easily switched when the need arrives.
=> OCLOMRS:108: Create environment variables to hold base urls

src/components/userDasboard/components/CardWrapper.jsx, src/components/userDasboard/components/DashboardDetails.jsx, src/components/userDasboard/container/UserDashboard.jsx
[OCLOMRS-122: Fix the grammar of the dictionary displayed to the user.](https://issues.openmrs.org/browse/OCLOMRS-122)
The home screen currently shows “You currently have 0 personal dictionary” and the title below is “Your dictionary”. Both of these should indicate“dictionaries” (plural).
=> OCLOMRS-122: Fix the grammar of the dictionary displayed to the user.

src/App.js, src/components/bulkConcepts/addBulkConcepts.jsx, src/components/bulkConcepts/style.css, src/components/dictionaryConcepts/components/ConceptDropdown.jsx, src/tests/bulkConcepts/addBulkConcepts.test.jsx
[OCLOMRS-97: Design the UI for the bulk concept page](https://issues.openmrs.org/browse/OCLOMRS-97)
- This is the page where the user will choose the preferred source, view its concepts, then after,  adds them to a dictionary.
=> OCLOMRS-97: Design the UI for the bulk concept page

src/components/userDasboard/container/UserDashboard.jsx, src/redux/actions/types.js, src/redux/actions/user/index.js, src/redux/reducers/user/index.js, src/redux/reducers/util.js, src/tests/Dashboard/container/DictionaryDisplay.test.jsx, src/tests/userDashboard/actions/index.test.js, src/tests/userDashboard/container/UserDashboard.test.jsx, src/tests/userDashboard/reducers/index.test.js
[OCLOMRS-141: Fix a bug on the user dashboard page.](https://issues.openmrs.org/browse/OCLOMRS-141)
Currently, the URL we are using does not allow a user to view all the dictionaries they have created. This is because the URL was designed to only return 10 items and not even adding a limit to the URL would solve the issue.
=> OCLOMRS-141: Fix a bug on the user dashboard page.

src/App.js, src/components/bulkConcepts/component/ActionButtons.jsx, src/components/bulkConcepts/component/ConceptTable.jsx, src/components/bulkConcepts/component/Paginations.jsx, src/components/bulkConcepts/component/SearchBar.jsx, src/components/bulkConcepts/component/Sidenav.jsx, src/components/bulkConcepts/component/TableItem.jsx, src/components/bulkConcepts/container/BulkConceptsPage.jsx, src/components/bulkConcepts/styles/index.css, src/redux/actions/concepts/addBulkConcepts/index.js, src/redux/actions/types.js, src/redux/reducers/bulkConceptReducer.js, src/redux/reducers/index.js, src/tests/bulkConcepts/actions/bulkConcept.test.js, src/tests/bulkConcepts/containers/BulkConceptsPage.test.js, src/tests/bulkConcepts/reducer/index.test.js
[Redesign page to match original mockup](https://issues.openmrs.org/browse/OCLOMRS-143)
Redesign the add concept page to match the provided mockup.
=> OCLOMRS-143: Redesign page to match original mockup

package-lock.json, package.json, src/App.js, src/components/bulkConcepts/component/ActionButtons.jsx, src/components/bulkConcepts/component/CardBody.jsx, src/components/bulkConcepts/component/ConceptTable.jsx, src/components/bulkConcepts/component/Paginations.jsx, src/components/bulkConcepts/component/PreviewCard.jsx, src/components/bulkConcepts/component/TableItem.jsx, src/components/bulkConcepts/container/BulkConceptsPage.jsx, src/components/bulkConcepts/styles/index.css, src/components/dictionaryConcepts/components/ConceptDropdown.jsx, src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx, src/redux/actions/concepts/addBulkConcepts/index.js, src/redux/actions/types.js, src/redux/reducers/bulkConceptReducer.js, src/tests/__mocks__/concepts.js, src/tests/bulkConcepts/actions/bulkConcept.test.js, src/tests/bulkConcepts/components/PreviewCard.test.js, src/tests/bulkConcepts/containers/BulkConceptsPage.test.js, src/tests/bulkConcepts/reducer/index.test.js
[Add functionality to the preview and add buttons](https://issues.openmrs.org/browse/OCLOMRS-150)
As a user, when I click on the preview button of a concept, I should see a popup with more information about that concept with a button to add the concept to my dictionary. If I click on any of the add buttons, the corresponding concept should be added to my dictionary.
=> OCLOMRS-150: Add functionality to the preview and add buttons

src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx, src/components/dashboard/components/dictionary/styles/dictionary-modal.css
[Redesign the dictionary overview UI to match the Mockup](https://issues.openmrs.org/browse/OCLOMRS-147)
Currently, the dictionary overview UI does not match the original mockup from the OCL documentation.
We should redesign it to match the mockup.
=> OCLOMRS-147: Redesign the dictionary overview UI to match the Mockup

src/components/bulkConcepts/component/SearchBar.jsx, src/components/bulkConcepts/container/BulkConceptsPage.jsx, src/redux/actions/concepts/addBulkConcepts/index.js, src/tests/bulkConcepts/actions/bulkConcept.test.js, src/tests/bulkConcepts/containers/BulkConceptsPage.test.js
[Add search functionality to "Add concept" page](https://issues.openmrs.org/browse/OCLOMRS-151)
As a user, I should be able to search for concepts in the dictionary I am trying to import concepts from.
=> OCLOMRS-151: Add search functionality to "Add Concepts" page

package-lock.json, src/components/Navbar.js
[Remove the (global) Search bar](https://issues.openmrs.org/browse/OCLOMRS-161)
Currently, the global search bar located in the navigation bar is not necessary and does match the OCL MVP documentation.
Therefore it should be removed.
=> OCLOMRS-161 : Remove the (global) Search bar

src/components/dictionaryConcepts/components/CreateConceptForm.jsx, src/tests/dictionaryConcepts/components/CreateConceptForm.test.jsx
[Changes to create concept form options for set of concepts](https://issues.openmrs.org/browse/OCLOMRS-172)
When a user selects to create a set of concepts the form should allow 3 classes:
- LabSet
- ConvSet
- MedSet
=> OCLOMRS-172: Changes to create concept form options for set of concepts

src/components/dashboard/components/SearchBar.jsx, src/components/dashboard/components/concepts/Search.jsx, src/components/dashboard/components/dictionary/DictionariesSearch.jsx, src/components/dashboard/container/DictionariesDisplay.jsx, src/tests/Dashboard/container/Concepts.test.jsx, src/tests/Dashboard/container/DictionaryDisplay.test.jsx, src/tests/Dashboard/container/OwnerDisplay.test.jsx, src/tests/Dashboard/container/SourceSearch.test.jsx, src/tests/Dashboard/container/SpecificConcept.test.jsx
[Rework the Search bar UI on the All Dictionaries, Sources and Concepts pages.](https://issues.openmrs.org/browse/OCLOMRS-195)
Currently, search bars UI in the above mentioned pages does not match what is expected in the original mockup from the OCL documentation.
We should redesign them to match the mockup.
=> OCLOMRS-195: Rework the Search bar UI on the All Dictionaries, Sources and Concepts pages.

src/components/bulkConcepts/style.css, src/components/bulkConcepts/styles/index.css, src/components/dashboard/components/DictionariesPaginations.jsx, src/components/dashboard/components/dictionary/DictionaryCard.jsx, src/components/dashboard/components/dictionary/ListDictionaries.jsx, src/components/dashboard/container/DictionariesDisplay.jsx, src/components/dashboard/styles/index.css, src/tests/Dashboard/container/DictionaryDisplay.test.jsx, src/tests/Dictionary/ListDictionaries.test.jsx, src/tests/Login/actions/login.test.js, src/tests/__mocks__/dictionaries.js
[Paginate Dictionaries on the All Dictionaries page](https://issues.openmrs.org/browse/OCLOMRS-197)
Dictionaries should be paginated and a user should be able to change their limit of the dictionaries per page.
=> OCLOMRS-197: Paginate Dictionaries on the All Dictionaries page

src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx, src/tests/Dictionary/DictionaryContainer.test.jsx
[Rework the Dictionary Overview page to make it more responsive](https://issues.openmrs.org/browse/OCLOMRS-214)
Dictionary details page was not responsive, and this should be fixed so it will be responsive even for small screen devices
=> OCLOMRS-214: Rework the Dictionary Overview page to make it more responsive

src/App.js, src/components/Navbar.js, src/components/bulkConcepts/addBulkConcepts.jsx, src/components/bulkConcepts/container/BulkConceptsPage.jsx, src/components/bulkConcepts/container/Header.js, src/components/bulkConcepts/style.css, src/components/bulkConcepts/styles/index.css, src/components/dashboard/components/concepts/SpecificConceptTable.jsx, src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx, src/components/dashboard/container/Concepts.jsx, src/components/dashboard/container/DictionariesDisplay.jsx, src/components/dashboard/styles/index.css, src/components/dictionaryConcepts/components/ConceptDropdown.jsx, src/components/dictionaryConcepts/style/index.css, src/tests/bulkConcepts/addBulkConcepts.test.jsx
[Rework the Back to page links to be consistent across the app](https://issues.openmrs.org/browse/OCLOMRS-221)
Currently, the Back to page links UI is not consistent across the app.
Therefore the Back to page links UI should be made consistent across the app.
=> OCLOMRS-221 : Rework the Back to page links to be consistent across the app

src/components/bulkConcepts/container/BulkConceptsPage.jsx, src/components/dashboard/components/dictionary/common/DictionaryModal.jsx, src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx, src/redux/actions/concepts/addBulkConcepts/index.js, src/redux/actions/user/index.js
[Search bar and the checkbox while adding CIEL concepts should work asynchronously](https://issues.openmrs.org/browse/OCLOMRS-199)
Results shown in table should correspond to the items selected with the checkboxes and the search input value.
=> OCLOMRS-199: Search bar and the checkbox while adding CIEL concepts should work asynchronously

src/components/login/container/index.jsx, src/components/login/styles/index.css
[Rework the Login UI according to the MVP](https://issues.openmrs.org/browse/OCLOMRS-220)
Currently, the login page doesn't match the mockup. This issue should ensure that the login page should match what is given in the mockup.
=> OCLOMRS-220: Rework the Login UI according to the MVP

src/App.js, src/components/Auth/index.jsx, src/components/Navbar.js, src/components/bulkConcepts/container/Header.js, src/components/bulkConcepts/styles/index.css, src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx, src/components/dashboard/styles/index.css, src/components/dictionaryConcepts/components/Header.jsx, src/components/dictionaryConcepts/style/index.css, src/components/login/container/index.jsx
[Change rename dashboard to Home and the route](https://issues.openmrs.org/browse/OCLOMRS-230)
On the navbar,  the name Dashboard should be replaced with Home. The routes should be also descriptive.
=> OCLOMRS-230:Change rename dashboard to Home and the route

src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx, src/redux/actions/concepts/dictionaryConcepts.js
[When a concept is edited it should display the new version](https://issues.openmrs.org/browse/OCLOMRS-201)
When the a concept is edited, it should the display the new version in the table that shows concepts in the dictionary.
=> OCLOMRS-201: When a concept is edited it should display the new version

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx
[Add tooltip on the short code input field](https://issues.openmrs.org/browse/OCLOMRS-237)
When adding a dictionary, "short code" input field should have a descriptive tooltip.
=> OCLOMRS-237: Add tooltip on the short code input field

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx, src/tests/Dictionary/DictionaryModal.test.jsx
[The preferred language should not appear in other languages](https://issues.openmrs.org/browse/OCLOMRS-232)
When a user selects the preferred language, it should not appear in other languages selection.
=> OCLOMRS-232: The preferred language should not appear in other languages

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx
[Add placeholder on the select multiple option](https://issues.openmrs.org/browse/OCLOMRS-241)
Select multiple option fields should have a placeholder to guide the user on an option to choose.
=> OCLOMRS-241 : Add placeholder on the select multiple option

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx, src/redux/actions/auth/authActionCreators.js, src/tests/Dictionary/DictionaryModal.test.jsx
[OCLOMRS-198: After creating a new Dictionary the Visibility public should map to view while visibility private should map to None](https://issues.openmrs.org/browse/OCLOMRS-198)
This is a fix After creating a new Dictionary the Visibility public should map to view while visibility private should map to None
=> OCLOMRS-198:After creating a new Dictionary the Visibility public should map to view while visibility private should map to None

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx, src/components/dashboard/components/dictionary/messages/InlineError.jsx, src/redux/actions/bulkConcepts/index.js, src/redux/actions/dictionaries/dictionaryActionCreators.js, src/redux/actions/user/index.js, src/redux/api.js, src/redux/reducers/dictionaryReducers.js, src/tests/Dashboard/action/api.test.js, src/tests/Dictionary/DictionaryContainer.test.jsx, src/tests/Dictionary/DictionaryModal.test.jsx, src/tests/bulkConcepts/actions/index.test.js, src/tests/userDashboard/actions/index.test.js
[Copy a dictionary by referencing custom concepts in original dictionary](https://issues.openmrs.org/browse/OCLOMRS-192)
Users should be able to reference concepts from an existing dictionary when creating a dictionary.
=> OCLOMRS-192: Copy a dictionary by referencing custom concepts in original dictionary

package.json
[Change the generated CSS filename to match with the one included in the components](https://issues.openmrs.org/browse/OCLOMRS-255)
Change the generated CSS filename to match with the one included in the components(Generated filename when watching changes in SASS files). In package.json.
=>  Change the generated CSS filename to match with the one included in the components

src/components/bulkConcepts/addBulkConcepts.jsx, src/components/bulkConcepts/container/BulkConceptsPage.jsx, src/components/dashboard/components/dictionary/ListDictionaries.jsx, src/styles/bulk_concepts.scss, src/styles/dictionary_concepts.scss, src/styles/dictionary_modal.scss
[All the pages in the App to have consistence margin and padding](https://issues.openmrs.org/browse/OCLOMRS-227)
The margin and padding on the pages should consistency. All the pages should have a uniform margin and padding not to have other pages with a bigger, other smaller and other none.
=> OCLOMRS-227 : All the pages in the App to have consistence margin and padding

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx, src/styles/dictionary_modal.scss
[Dictionary Modal should be responsive](https://issues.openmrs.org/browse/OCLOMRS-246)
Dictionary modal should be visible within the view port of different screen sizes.
=> OCLOMRS-246: Dictionary Modal should be responsive

package.json, src/components/dashboard/components/dictionary/DictionaryContainer.jsx, src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx, src/components/dashboard/components/dictionary/DictionaryVersionsTable.jsx, src/tests/Dictionary/DictionaryContainer.test.jsx, src/tests/__mocks__/concepts.js
[Download Concepts from a released version of an implementation dictionary](https://issues.openmrs.org/browse/OCLOMRS-253)
Currently, a user cannot be able to download concepts in released version of an implementation dictionary. This issue should ensure that a user can download concepts of a released implementation dictionary
=> OCLOMRS-253: Download Concepts from a released version of an implementation dictionary

src/components/Navbar.js
[Fix the navbar alignment](https://issues.openmrs.org/browse/OCLOMRS-248)
The navbar was initially displaying the navbar items in a disorganized manner. This is a fix to make the navbar items be aligned at the center thus resulting to a good user experience.
=> OCLOMRS-248: Fix the navbar alignment

src/redux/actions/concepts/dictionaryConcepts.js
[Fix display dictionary concepts](https://issues.openmrs.org/browse/OCLOMRS-263)
When you click on concepts button on dictionary details page, there is no any concept that gets displayed on dictionary concepts page.
=> OCLOMRS-263: Fix display dictionary concepts

src/App.js, src/components/Signup/components/container/index.jsx, src/styles/login.scss, src/tests/Signup/index.test.jsx
[OCLOMRS-212: Design the Signup page UI according to the MVP](https://issues.openmrs.org/browse/OCLOMRS-212)
This is the design of the sigup page for the Open Concept Lab.
=> OCLOMRS-212: Design the Signup page UI according to the MVP

src/components/bulkConcepts/component/ActionButtons.jsx, src/components/bulkConcepts/component/PreviewCard.jsx, src/components/bulkConcepts/container/BulkConceptsPage.jsx, src/components/dashboard/components/dictionary/DictionaryContainer.jsx, src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx, src/components/dashboard/components/dictionary/DictionaryVersionsTable.jsx, src/components/dashboard/components/dictionary/EditDictionary.jsx, src/components/dashboard/components/dictionary/common/DictionaryModal.jsx, src/components/dashboard/components/dictionary/common/ReleaseVersionModal.jsx, src/components/dashboard/components/dictionary/messages/InlineError.jsx, src/components/login/container/index.jsx
[Fix all the errors/warnings that appear in the browser console in development mode](https://issues.openmrs.org/browse/OCLOMRS-262)
In development mode, there are warnings/errors that appear in the browser console. Some code refactoring is required to fix those warnings and errors. Most of those errors and warnings are related to prop types validation and DOM nesting.
Those errors need to be fixed to leave the development console error/warning free.
=> OCLOMRS-262: Fix all the errors/warnings that appear in the browser console in development mode

src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx
[OCLOMRS-252: Add all bulk concepts fix](https://issues.openmrs.org/browse/OCLOMRS-252)
Users can be able to add all bulk concepts at once.
=> OCLOMRS-252: Add all bulkconcepts fix

src/components/login/components/SubmitButton.jsx
[Make loader appear when one clicks the login button.](https://issues.openmrs.org/browse/OCLOMRS-283)
A loader was not well implemented on the login button as it does not appear once one clicks the login button. Minor adjustments to the code can make it visible as it was intended.
=> OCLOMRS-283: Make loader appear when one clicks the login button.

README.md
[Update README to describe commands to use for SASS usage](https://issues.openmrs.org/browse/OCLOMRS-282)
Recently, the app migrated from CSS to SASS usage. and the README should be updated to describe commands to use when you're using SASS
=> OCLOMRS-282: Update README to describe commands to use for SASS usage

.eslintrc.json, src/redux/actions/concepts/addBulkConcepts/index.js, src/redux/actions/concepts/dictionaryConcepts.js, src/redux/actions/concepts/specificConceptAction.js
[Fix wrong API URL endpoints](https://issues.openmrs.org/browse/OCLOMRS-297)
Some parts of the application are making API calls to the wrong API endpoint which is causing 404 error. These API endpoints URLs should be corrected to the right ones.
=> OCLOMRS-297: Fix wrong API URL endpoints

src/components/login/container/index.jsx
[OCLOMRS-244: Fix the style guide in the application](https://issues.openmrs.org/browse/OCLOMRS-244)
This ticket fixes the eslint error on style guide. There is an error in the alignment of the function. Some functions are defined before other and that should not be the case.
=> OCLOMRS-244: Fix the style guide in the application

src/components/dictionaryConcepts/components/CreateConceptTable.jsx
[Change "preferred in locale" to "preferred in language"](https://issues.openmrs.org/browse/OCLOMRS-300)
Concept names have both locale and language but it should have one used all through for consistency purposes. We will use language hence it would be "preferred in language".
=> OCLOMRS-300: Change 'preferred in locale' to 'preferred in language'

package.json
[Clean up application dependencies](https://issues.openmrs.org/browse/OCLOMRS-294)
Currently, in the application dependencies file(`package.json`), app development dependencies are mixed with app dependencies and there are some unused dependencies listed there. This should be worked on and do and clean up.
=> OCLOMRS-294: Clean up application dependencies

src/App.js, src/components/Footer.js, src/styles/app.scss, src/styles/index.scss
[Add application footer](https://issues.openmrs.org/browse/OCLOMRS-295)
Now: the application has not the footer. The application should have a footer like the traditional OCL UI.
The footer should indicate the Copyright holder and year, link to about page and link to the API(Link to the API should be opened in the new tab).
=> OCLOMRS-295: Add application footer

src/App.js, src/styles/app.scss
[Fix action buttons on add bulk concepts page](https://issues.openmrs.org/browse/OCLOMRS-314)
On add bulk concepts page, the bottom action buttons(**Add all selected** and **Back** buttons) don't appear properly.
=> OCLOMRS-314: Fix action buttons on add bulk concepts page

.eslintrc.json, src/components/dictionaryConcepts/components/ActionButtons.jsx, src/components/dictionaryConcepts/components/AddMapping.jsx, src/components/dictionaryConcepts/components/ConceptNameRows.jsx, src/components/dictionaryConcepts/components/ConceptTable.jsx, src/components/dictionaryConcepts/components/ExternalMapping.jsx, src/components/dictionaryConcepts/components/InternalMapping.jsx, src/components/dictionaryConcepts/components/MappingModal.jsx, src/styles/dictionary_concepts.scss, src/tests/dictionaryConcepts/components/AddMapping.test.jsx, src/tests/dictionaryConcepts/components/ExternalMapping.test.js, src/tests/dictionaryConcepts/components/InternalMapping.test.js, src/tests/dictionaryConcepts/components/MappingModal.test.js
[Create concept mapping form](https://issues.openmrs.org/browse/OCLOMRS-303)
Concept mapping is an instructional strategy for individual and group learning that involves the integration of knowledge and creation of meaning from each individual's language or locale that relates to specific concepts. This ticket involves the creation of the mapping forms without its functionalities.
=> OCLOMRS-303: Create concept mapping form

src/components/Footer.js, src/components/Navbar.js, src/components/bulkConcepts/addBulkConcepts.jsx, src/components/bulkConcepts/component/Sidenav.jsx, src/components/bulkConcepts/container/BulkConceptsPage.jsx, src/components/dashboard/components/dictionary/DictionaryContainer.jsx, src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx, src/components/dictionaryConcepts/components/ConceptTable.jsx, src/components/dictionaryConcepts/components/Sidenav.jsx, src/components/dictionaryConcepts/containers/CreateConcept.jsx, src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx, src/components/userDasboard/container/UserDashboard.jsx, src/styles/app.scss, src/styles/dashboard.scss, src/styles/dictionary_concepts.scss
[Fix the app CSS files to cater for all the media](https://issues.openmrs.org/browse/OCLOMRS-257)
Previously, some parts of app were not responsive, some were not aligned properly or some elements overflowed out of their containers on smaller devices.
This is fixed by this PR.
=> OCLOMRS-257: Fix the app CSS files to cater for all the media

public/index.html
[Remove unnecessary libraries](https://issues.openmrs.org/browse/OCLOMRS-307)
Remove the following from the application:
- Bootstrap
- Popper JS
- JQuery
=> OCLOMRS-307: Remove unnecessary libraries

src/components/dictionaryConcepts/components/ActionButtons.jsx, src/components/dictionaryConcepts/components/ConceptTable.jsx, src/components/dictionaryConcepts/components/ViewConceptMappings.jsx, src/components/dictionaryConcepts/components/ViewMappingsModal.jsx, src/components/dictionaryConcepts/proptypes.js, src/redux/actions/concepts/dictionaryConcepts.js, src/tests/dictionaryConcepts/components/ActionButtons.test.jsx, src/tests/dictionaryConcepts/components/AddMapping.test.jsx, src/tests/dictionaryConcepts/components/ViewConceptMappings.test.js, src/tests/dictionaryConcepts/components/ViewMappingsModal.test.js
[OCLOMRS-310: Implement view mapping functionality](https://issues.openmrs.org/browse/OCLOMRS-310)
Implemented the concept's mappings table to display mappings belonging to a given concept.
=> OCLOMRS-310: Implement view mapping functionality

src/components/Navbar.js
[Resize the logout dropdown](https://issues.openmrs.org/browse/OCLOMRS-323)
Previously, with the changes to move from react-bootstrap to reactstrap, some styling was interfered with. This ticket resizes the logout dropdown to be as it was before.
=> OCLOMRS-323: Resize the logout dropdown 

src/redux/actions/concepts/dictionaryConcepts.js
[Edit the view concepts url](https://issues.openmrs.org/browse/OCLOMRS-324)
Currently, the get concept URL is using the collections and due to the change on the backend, we switched to sources in order to get the concepts.
=> OCLOMRS-324: Edit the view concepts url

src/components/bulkConcepts/component/ActionButtons.jsx, src/components/bulkConcepts/component/CardBody.jsx, src/components/dashboard/components/dictionary/DictionariesSearch.jsx, src/components/dashboard/components/dictionary/DictionaryContainer.jsx
[Refactor code to reduce console warnings](https://issues.openmrs.org/browse/OCLOMRS-332)
Currently, when running tests, there are warnings on the console due to invalid prop validation.
=> OCLOMRS-332: Refactor code to reduce console warnings

src/components/dictionaryConcepts/components/ActionButtons.jsx, src/components/dictionaryConcepts/components/AddMapping.jsx, src/components/dictionaryConcepts/components/ExternalMapping.jsx, src/components/dictionaryConcepts/components/InternalMapping.jsx, src/components/dictionaryConcepts/components/MappingModal.jsx, src/components/dictionaryConcepts/components/ViewConceptMappings.jsx, src/components/dictionaryConcepts/components/ViewMappingsModal.jsx, src/redux/actions/dictionaries/dictionaryActionCreators.js, src/redux/api.js, src/tests/Dashboard/action/dictionaryAction.test.js, src/tests/dictionaryConcepts/components/AddMapping.test.jsx, src/tests/dictionaryConcepts/components/InternalMapping.test.js, src/tests/dictionaryConcepts/components/MappingModal.test.js, src/tests/dictionaryConcepts/components/ViewMappingsModal.test.js
[Implement edit internal mapping functionality](https://issues.openmrs.org/browse/OCLOMRS-309)
Enable editing of internal concept mappings.
=> OCLOMRS-309: Implement edit internal mapping functionality

src/components/bulkConcepts/addBulkConcepts.jsx, src/tests/bulkConcepts/addBulkConcepts.test.jsx
[Fix unresponsive button on bulk concepts page](https://issues.openmrs.org/browse/OCLOMRS-333)
This fixes the back button in the bulk concepts page. Currently, the button is sometimes unresponsive and is fixed by this PR.
=> OCLOMRS-333: Fix unresponsive button on bulk concepts page

src/components/dashboard/components/dictionary/common/SubscriptionModal.jsx
[OCLOMRS-347: Change Subscription URL modal 'cancel' button to 'close'](https://issues.openmrs.org/browse/OCLOMRS-347)
Change Subscription URL modal '**cancel**' button to '**close**'
=> OCLOMRS-347: Change Subscription URL modal 'cancel' button to 'close'

src/components/dictionaryConcepts/components/AddMapping.jsx, src/components/dictionaryConcepts/components/ExternalMapping.jsx, src/components/dictionaryConcepts/components/MappingModal.jsx, src/components/dictionaryConcepts/components/ViewConceptMappings.jsx, src/components/dictionaryConcepts/components/ViewMappingsModal.jsx, src/tests/dictionaryConcepts/components/ActionButtons.test.jsx, src/tests/dictionaryConcepts/components/AddMapping.test.jsx, src/tests/dictionaryConcepts/components/ExternalMapping.test.js, src/tests/dictionaryConcepts/components/InternalMapping.test.js, src/tests/dictionaryConcepts/components/MappingModal.test.js, src/tests/dictionaryConcepts/components/ViewConceptMappings.test.js, src/tests/dictionaryConcepts/components/ViewMappingsModal.test.js
[Implement Edit External Mapping](https://issues.openmrs.org/browse/OCLOMRS-344)
Currently, editing mapping only works on internal concepts. It should be implemented for external mapping too. Only the external mappings component is created but it is still redundant as it has no edit external mapping implementation.
=> OCLOMRS-344: Implement Edit External Mapping

src/components/dashboard/components/dictionary/DictionaryContainer.jsx, src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx, src/components/dashboard/components/dictionary/DictionaryVersionsTable.jsx, src/redux/actions/dictionaries/dictionaryActionCreators.js, src/tests/Dashboard/action/dictionaryAction.test.js, src/tests/Dictionary/DictionaryContainer.test.jsx, src/tests/__mocks__/versions.js
[Change "Change dictionary version release behaviour"](https://issues.openmrs.org/browse/OCLOMRS-348)
Change version table behaviour and show modal when releasing all versions
=> OCLOMRS-348: Change dictionary version release behaviour

src/components/dictionaryConcepts/components/CreateConceptForm.jsx, src/components/dictionaryConcepts/components/CreateMapping.jsx, src/components/dictionaryConcepts/components/helperFunction.js, src/components/dictionaryConcepts/containers/CreateConcept.jsx, src/redux/actions/concepts/dictionaryConcepts.js, src/styles/app.scss, src/tests/__mocks__/concepts.js, src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js, src/tests/dictionaryConcepts/components/CreateMapping.test.js, src/tests/dictionaryConcepts/container/CreateConcept.test.jsx
[Implement create mapping functionality](https://issues.openmrs.org/browse/OCLOMRS-363)
Implement create concept mapping functionality. In this case, it should be implemented in the same interface as the create new concept interface. One should be able to add multiple mapping to a concept he/she is creating..
=> OCLOMRS-364: Implement create mapping functionality

src/components/dictionaryConcepts/components/CreateConceptTable.jsx, src/styles/dictionary_concepts.scss
[Fix background overlap on the create/edit concepts page.](https://issues.openmrs.org/browse/OCLOMRS-380)
Fix background overlap on the create/edit concepts page.
=> OCLOMRS-380: Fix background overlap on the create/edit concepts page.

src/components/dictionaryConcepts/components/CreateConceptTable.jsx
[Fix the table format on the create new concept page](https://issues.openmrs.org/browse/OCLOMRS-388)
The names title and add names link on the create new concept page are out of place.
=> OCLOMRS-388: Fix the table format on the create new concept page

src/components/dashboard/components/dictionary/common/GeneralModal.jsx, src/components/dashboard/components/dictionary/common/ReleaseVersionModal.jsx, src/components/dashboard/components/dictionary/common/SubscriptionModal.jsx, src/styles/dictionary_modal.scss
[Make buttons consistent](https://issues.openmrs.org/browse/OCLOMRS-402)
The buttons theme for (Subscription URL popup, Release a new version popup, Confirm release popup) is inconsistent
- The buttons on these popups do not look like the other buttons in the application hence the inconsistency
=> OCLOMRS-402: The buttons theme for (Subscription URL popup, Release a new version popup, Confirm release popup) is inconsistent

src/components/Loader.js, src/components/bulkConcepts/addBulkConcepts.jsx, src/redux/actions/bulkConcepts/index.js, src/redux/actions/types.js, src/redux/reducers/bulkConcepts/index.js, src/styles/app.scss, src/tests/bulkConcepts/actions/index.test.js, src/tests/bulkConcepts/addBulkConcepts.test.jsx, src/tests/bulkConcepts/reducers/index.test.js
[Add a loader to add bulk concepts search](https://issues.openmrs.org/browse/OCLOMRS-394)
A user should see the loader to show something is going on while the search is loading
=> OCLOMRS-394: Add a loader to addBulk concepts search

src/components/dictionaryConcepts/components/CreateConceptForm.jsx, src/components/dictionaryConcepts/components/CreateMapping.jsx, src/styles/dictionary_modal.scss
[Make mapping interfaces consistent (header-body table format) with other parts of concept form](https://issues.openmrs.org/browse/OCLOMRS-416)
The mappings interface table on create concept should be made consistent with all the other tables:
- Make the table have a header row similar to the other tables.
- Make the add mappings link same as the other links on the page.
=> OCLOMRS-416: Make mapping interfaces consistent (header-body table format) with other parts of concept form

src/components/dictionaryConcepts/components/CreateConceptForm.jsx, src/components/dictionaryConcepts/components/CreateMapping.jsx, src/components/dictionaryConcepts/components/MapType.jsx, src/components/dictionaryConcepts/components/helperFunction.js, src/components/dictionaryConcepts/containers/CreateConcept.jsx, src/components/dictionaryConcepts/containers/EditConcept.jsx, src/redux/actions/concepts/dictionaryConcepts.js, src/styles/dictionary_concepts.scss, src/tests/__mocks__/concepts.js, src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js, src/tests/dictionaryConcepts/components/CreateMapping.test.js, src/tests/dictionaryConcepts/components/MapType.test.js, src/tests/dictionaryConcepts/components/MappingModal.test.js, src/tests/dictionaryConcepts/container/EditConcept.test.jsx
[implement edit mapping on the right interface](https://issues.openmrs.org/browse/OCLOMRS-406)
"edit mapping" is currently implemented in the view mappings interface. It needs to be implemented in the edit concept interface
=> OCLOMRS-406: implement edit mapping on the right interface

src/components/dictionaryConcepts/components/CreateMapping.jsx, src/redux/actions/concepts/dictionaryConcepts.js
[Make Concept Name search field search by both Concept Name and Code, with preview of suggestions showing name and code](https://issues.openmrs.org/browse/OCLOMRS-425)
A user should be able to search by concept name or code with a preview showing both name and code
=> OCLOMRS-425: Make Concept Name search field search by both Concept Name and Code, with preview of suggestions showing name and code

Dockerfile, README.md
[update README to guide new setup successfully](https://issues.openmrs.org/browse/OCLOMRS-437)
Following the readme for new setup is unsuccessful. The readme needs to be updated.
=> OCLOMRS-437: update README to guide new setup

src/components/dictionaryConcepts/components/CreateConceptForm.jsx, src/components/dictionaryConcepts/components/CreateMapping.jsx
[Move the Mappings "Code" field from the Relationship column to the Concept column](https://issues.openmrs.org/browse/OCLOMRS-444)
Under the Mappings table (for Create/Edit Concept) Rename the "Name" column to "Concept" and move the "Code" field from the Relationship column to the Concept column.
=> OCLOMRS-444: Move the Mappings "Code" field from the Relationship column to the Concept column

package.json, src/components/dictionaryConcepts/components/CreateConceptForm.jsx, src/components/dictionaryConcepts/components/CreateMapping.jsx, src/components/dictionaryConcepts/containers/CreateConcept.jsx, src/components/dictionaryConcepts/containers/EditConcept.jsx, src/tests/__mocks__/concepts.js, src/tests/dictionaryConcepts/components/CreateMapping.test.js, src/tests/dictionaryConcepts/container/CreateConcept.test.jsx, src/tests/dictionaryConcepts/container/EditConcept.test.jsx
[Make the source field a select option](https://issues.openmrs.org/browse/OCLOMRS-446)
A user should just be able to select from the list of available Sources while adding a mapping to a concept.
=> OCLOMRS-446: Make the source field a select option

src/components/bulkConcepts/addBulkConcepts.jsx, src/styles/bulk_concepts.scss, src/styles/dashboard.scss
[Fix the aesthetics on the Add Bulk Concepts Page](https://issues.openmrs.org/browse/OCLOMRS-459)
- Fix the alignment of search fields on the Add Bulk Concepts Page
- Make the "Add" button consistent with other buttons in the application.
=> OCLOMRS-459: Fix the aesthetics on the Add Bulk Concepts Page

package.json, src/components/dictionaryConcepts/components/CreateMapping.jsx
[Make all mappings fields editable when editing a concept.](https://issues.openmrs.org/browse/OCLOMRS-474)
Make the Concept Name field editable on the Edit Concept page (under the mappings table) and ensure that all other fields can be edited as well.
=> OCLOMRS-474: Make all mappings fields editable when editing a concept.

src/tests/Signup/index.test.jsx
[Raise test coverage](https://issues.openmrs.org/browse/OCLOMRS-479)
Raise test coverage drop from the sign-up component.
=> OCLOMRS-479: Raise test coverage

package.json
[Fix the project start script](https://issues.openmrs.org/browse/OCLOMRS-487)
Remove the unwanted configurations from the start script in `package.json`
=> OCLOMRS-487: Fix the project start script

src/components/dictionaryConcepts/containers/EditConcept.jsx, src/redux/actions/concepts/dictionaryConcepts.js, src/tests/dictionaryConcepts/container/EditConcept.test.jsx
[Edit the reference of a Concept in a Dictionary](https://issues.openmrs.org/browse/OCLOMRS-480)
After Editing a Concept, edit its corresponding reference in the current Dictionary as well.
=> OCLOMRS-480: Edit the reference of a Concept in a Dictionary

src/components/dictionaryConcepts/components/CreateConceptForm.jsx, src/components/dictionaryConcepts/containers/EditConcept.jsx, src/tests/dictionaryConcepts/container/EditConcept.test.jsx
[When one clicks Cancel (Edit Concept page) show message a “Are you sure you want to cancel without saving ?”](https://issues.openmrs.org/browse/OCLOMRS-469)
On the Edit Concept page, when one clicks "Cancel", there should be a message saying, "Are you sure you want to cancel without saving?" with options to proceed or not.
=> OCLOMRS-469: When one clicks Cancel (Edit Concept page) show message a “Are you sure you want to cancel without saving ?

src/components/dictionaryConcepts/components/CreateMapping.jsx, src/tests/dictionaryConcepts/components/CreateMapping.test.js
[Fix memory leak console log error when running tests](https://issues.openmrs.org/browse/OCLOMRS-499)
When running tests, a console log error associated with createMappings.test appears that indicates a memory leak in the application. This could result in performance issues.
=> OCLOMRS-499: Fix memory leak console log error when running tests

src/components/dictionaryConcepts/components/AnswerRow.jsx, src/components/dictionaryConcepts/components/AnswersTable.jsx, src/components/dictionaryConcepts/components/helperFunction.js, src/components/dictionaryConcepts/containers/SelectAnswers.jsx, src/redux/actions/concepts/dictionaryConcepts.js, src/styles/dictionary_concepts.scss, src/tests/dictionaryConcepts/container/SelectAnswers.test.js
[Fix concept search on add Q and A concept page](https://issues.openmrs.org/browse/OCLOMRS-492)
Fix concept search so that;
- When a user wants to search for a concept.
- When they entering the search data.
- They have to first strike enter to search for a given concept.
=> OCLOMRS-492: Fix concept search on add Q and A concept page.

.gitignore, src/components/dictionaryConcepts/components/AnswersTable.jsx, src/components/dictionaryConcepts/containers/EditConcept.jsx, src/tests/__mocks__/answers.js, src/tests/dictionaryConcepts/components/AnswersTable.test.jsx
[A user should be able to edit Answers in a custom Q-A Concept](https://issues.openmrs.org/browse/OCLOMRS-502)
This PR fixes the Edit functionality for Answers in Q-A Concepts.
=> OCLOMRS-502: A user should be able to edit Answers in a custom Q-A Concept

src/redux/actions/bulkConcepts/index.js
[when creating a mapping, source dropdown does not show all available sources](https://issues.openmrs.org/browse/OCLOMRS-507)
source does not show all available sources
=> OCLOMRS-507: source does not show all available sources	

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx
[The Add dictionary modal fields should be rearranged](https://issues.openmrs.org/browse/OCLOMRS-517)
The Add dictionary modal fields should be rearranged
=> OCLOMRS-517: The Add dictionary modal fields should be rearranged

src/components/dictionaryConcepts/components/ConceptDropdown.jsx, src/components/dictionaryConcepts/containers/CreateConcept.jsx, src/tests/dictionaryConcepts/container/CreateConcept.test.jsx
The title of the create set of concept should be changed
[The title of the create set of concept should be changed](https://issues.openmrs.org/browse/OCLOMRS-519)
The title of the 'create a set of concept' should be changed to 'Create a set of concepts'
=> OCLOMRS-519: The title of the create set of concept should be changed

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx
[Reorder the fields when creating a new dictionary](https://issues.openmrs.org/browse/OCLOMRS-523)
Reorder the fields when creating a new dictionary
=> OCLOMRS-523: Reorder the fields when creating a new dictionary

src/components/dictionaryConcepts/components/ActionButtons.jsx
[A referenced concept should be viewable on the dictionary concepts page](https://issues.openmrs.org/browse/OCLOMRS-527)
A referenced concept should be viewable on the dictionary concepts page
=> OCLOMRS-527: A referenced concept should be viewable on the dictionary concepts page

src/components/dictionaryConcepts/components/AnswerRow.jsx, src/components/dictionaryConcepts/components/AnswersTable.jsx
[Answers showing incorrect sources](https://issues.openmrs.org/browse/OCLOMRS-545)
The source column for answers shows an incorrect source
=> OCLOMRS-545: Answers showing incorrect sources

public/index.html, src/components/Navbar.js, src/components/bulkConcepts/component/Pagination.jsx, src/components/dashboard/components/DictionariesPaginations.jsx, src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx, src/components/dictionaryConcepts/components/CreateConceptForm.jsx, src/components/userDasboard/container/UserDashboard.jsx, src/styles/app.scss, src/styles/bulk_concepts.scss, src/styles/dashboard.scss, src/styles/dictionary_concepts.scss, src/styles/dictionary_modal.scss, src/styles/index.scss, src/tests/userDashboard/container/UserDashboard.test.jsx
[Improve Application UI](https://issues.openmrs.org/browse/OCLOMRS-546)
- Improve color consistency and coherence across app
- Increase navbar size
- Improve heading font sizes
- Change app font
=> OCLOMRS-546: Improve Application UI

src/components/dictionaryConcepts/components/ConceptDropdown.jsx
[When creating a custom concept, the first letter of the class name should be capitalized ](https://issues.openmrs.org/browse/OCLOMRS-551)
When creating custom concepts ensure that all concept class names begin with a capital letter. For example, when one creates a diagnosis concept, the concept class is saved as ***question*** but it should be ***Question***, same for diagnosis and Drug concepts etc.
=> OCLOMRS-551: When creating a custom concept, the first letter of the class name should be capitalized 

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx, src/setupTests.js, src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js, src/tests/dictionaryConcepts/components/ActionButtons.test.jsx, src/tests/dictionaryConcepts/components/AnswerRow.test.js, src/tests/dictionaryConcepts/components/ConceptNameRows.test.jsx, src/tests/dictionaryConcepts/container/CreateConcept.test.jsx, src/tests/dictionaryConcepts/container/EditConcept.test.jsx, src/tests/dictionaryConcepts/container/SelectAnswers.test.js
[Add tests and fix console errors](https://issues.openmrs.org/browse/OCLOMRS-560)
Add more tests to address the coverage drop from this [PR](https://github.com/openmrs/openmrs-ocl-client/pull/435).
It also handles the console errors that have been showing up when running tests
=> OCLOMRS-560: Raise test coverage and fix console errors

src/components/dictionaryConcepts/components/AnswerRow.jsx, src/components/dictionaryConcepts/components/AnswersTable.jsx, src/components/dictionaryConcepts/components/CreateConceptForm.jsx, src/components/dictionaryConcepts/components/helperFunction.js, src/components/dictionaryConcepts/containers/CreateConcept.jsx, src/components/dictionaryConcepts/containers/EditConcept.jsx, src/components/dictionaryConcepts/containers/SelectAnswers.jsx, src/redux/actions/concepts/dictionaryConcepts.js, src/redux/actions/types.js, src/redux/reducers/ConceptReducers.js, src/redux/reducers/store.js, src/tests/Dashboard/reducer/conceptReducer.test.js, src/tests/__mocks__/concepts.js, src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js, src/tests/dictionaryConcepts/components/CreateMapping.test.js, src/tests/dictionaryConcepts/container/CreateConcept.test.jsx, src/tests/dictionaryConcepts/container/EditConcept.test.jsx
[Create set of concepts should have sets field after descriptions](https://issues.openmrs.org/browse/OCLOMRS-520)
When creating a set concept, one of the available fields should be sets. These previously did not appear.
=> OCLOMRS-520: Create set of concepts should have sets field after descriptions

src/tests/bulkConcepts/containers/BulkConceptsPage.test.js
[Refactoring tests in the BulkConceptsPage.test file](https://issues.openmrs.org/browse/OCLOMRS-564)
Refactoring tests in the BulkConceptsPage.test file
=> OCLOMRS-564: Refactoring tests in the BulkConceptsPage file

src/components/bulkConcepts/component/SideNavItems.jsx, src/components/bulkConcepts/component/Sidenav.jsx, src/components/bulkConcepts/container/BulkConceptsPage.jsx, src/redux/actions/concepts/addBulkConcepts/index.js, src/tests/bulkConcepts/actions/bulkConcept.test.js, src/tests/bulkConcepts/containers/BulkConceptsPage.test.js
[Filter concepts By Class name not working as intended](https://issues.openmrs.org/browse/OCLOMRS-567)
When viewing bulk concepts, the current filter status is not reflected in the checkbox sometimes, causing the functionality to break
=> OCLOMRS-567: Filter concepts By Class name not working as intended

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx
[Set auto focus on the dictionary name field when a creating new dictionary](https://issues.openmrs.org/browse/OCLOMRS-573)
When creating a dictionary the default cursor position should be set in the dictionary name field.
=> OCLOMRS-573: Set auto focus on the dictionary name field when a creating new dictionary

src/redux/actions/concepts/dictionaryConcepts.js, src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js
[Internal Mappings Not Created When Creating or Updating a Concept](https://issues.openmrs.org/browse/OCLOMRS-574)
The body of data sent to the API when creating mappings to internal concepts is incorrect.
=> OCLOMRS-574: Internal Mappings Not Created When Creating or Updating a Concept

src/tests/bulkConcepts/actions/bulkConcept.test.js, src/tests/dictionaryConcepts/components/CreateMapping.test.js
[Tests completing before all async actions are complete](https://issues.openmrs.org/browse/OCLOMRS-581)
A few tests are completed before asynchronous actions complete, causing failing Travis builds
=> OCLOMRS-581: Tests completing before all async actions are complete

src/tests/Dictionary/DictionaryModal.test.jsx
[Refactor the structure of the DictionaryModal tests to align with the coding convention](https://issues.openmrs.org/browse/OCLOMRS-586)
Refactor the structure of the DictionaryModal tests to align with the coding convention
=> OCLOMRS-586: Refactor the structure of the DictionaryModal tests to align with the coding convention

src/components/userDasboard/container/UserDashboard.jsx
[Incorrect dictionary count on home page](https://issues.openmrs.org/browse/OCLOMRS-578)
Incorrect dictionary count on home page
=> OCLOMRS-578: Incorrect dictionary count on home page (#466)

src/components/dictionaryConcepts/components/helperFunction.js, src/redux/actions/concepts/addBulkConcepts/index.js, src/redux/api.js
[When adding a CIEL concept, some of it's mappings are not added](https://issues.openmrs.org/browse/OCLOMRS-582)
When adding a CIEL concept to the collection, it returns an error message when we attempt to add Non-CIEL mappings.
=> OCLOMRS-582: When adding a CIEL concept, some of it's mappings are not added.

src/redux/actions/concepts/dictionaryConcepts.js, src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js
[Add an external_id when creating mappings](https://issues.openmrs.org/browse/OCLOMRS-595)
Add an external_id when creating mappings
=> OCLOMRS-595: Add an external_id when creating mappings

src/tests/bulkConcepts/components/Pagination.test.js
[Raise Test Coverage](https://issues.openmrs.org/browse/OCLOMRS-603)
Raise Test Coverage for this [PR](https://github.com/openmrs/openmrs-ocl-client/pull/478/files)
=> OCLOMRS-603: Raise Test Coverage

src/components/dictionaryConcepts/components/helperFunction.js, src/redux/actions/concepts/dictionaryConcepts.js, src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js, src/tests/dictionaryConcepts/components/helperFunction.test.js
[Raise Test Coverage](https://issues.openmrs.org/browse/OCLOMRS-604)
Address coverage drop on https://github.com/openmrs/openmrs-ocl-client/pull/481.
=> OCLOMRS-604: Raise Test Coverage

src/components/dictionaryConcepts/components/helperFunction.js, src/components/dictionaryConcepts/containers/EditConcept.jsx, src/redux/actions/concepts/dictionaryConcepts.js, src/redux/api.js, src/tests/Dashboard/action/api.test.js, src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js
[When a mapping is created or updated, a reference to it should be added to the collection](https://issues.openmrs.org/browse/OCLOMRS-596)
- When a mapping is created, we should also be adding a reference to it to the collection
- When a mapping is updated, we should also be updating its reference in the collection
=> OCLOMRS-596: When a mapping is created or updated, a reference to it should be added to the collection

src/components/bulkConcepts/addBulkConcepts.jsx, src/components/bulkConcepts/component/ConceptTable.jsx, src/redux/actions/bulkConcepts/index.js, src/redux/actions/concepts/addBulkConcepts/index.js, src/styles/utils.scss, src/tests/bulkConcepts/actions/bulkConcept.test.js, src/tests/bulkConcepts/actions/index.test.js
[OCLOMRS-599](https://issues.openmrs.org/browse/OCLOMRS-599)
There should be an indicator when adding CIEL concepts recursively until they are all fully added
=> OCLOMRS-599: A loader should be displayed when adding CIEL concepts recursively until they are all fully added

src/tests/Loader.test.js
[Raise Test Coverage](https://issues.openmrs.org/browse/OCLOMRS-605)
Raise Test Coverage
=> OCLOMRS-605: Raise Test Coverage

src/components/dictionaryConcepts/containers/EditConcept.jsx, src/tests/dictionaryConcepts/container/EditConcept.test.jsx
[Fix Conflicting Tests](https://issues.openmrs.org/browse/OCLOMRS-610)
A few tests were not mocking some parts of the code/ not cleaning up after themselves, causing subsequent tests to fail
=> OCLOMRS-610: Fix Conflicting Tests

src/tests/dictionaryConcepts/reducer/dictionaryConcept.test.js
[ Add tests](https://issues.openmrs.org/browse/OCLOMRS-611)
Add tests to increase the test coverage
=> OCLOMRS-611: Add tests to increase the test coverage 

src/components/bulkConcepts/component/ConceptTable.jsx
[The Add a Ciel Concept page occasionally returns a single value](https://issues.openmrs.org/browse/OCLOMRS-607)
The Add a Ciel Concept page occasionally returns a single value
=> OCLOMRS-607: The Add a Ciel Concept page occasionally returns a single value

src/components/bulkConcepts/component/ConceptPagination.jsx, src/components/bulkConcepts/component/ConceptTable.jsx, src/components/bulkConcepts/container/BulkConceptsPage.jsx, src/redux/actions/concepts/addBulkConcepts/index.js
[When adding CIEL concepts, a page should display 20 concepts](https://issues.openmrs.org/browse/OCLOMRS-643)
=> OCLOMRS-643: When adding CIEL concepts, a page should display 20 concepts

app.json, static.json
[Setup Heroku Pipleline for Review Apps](https://issues.openmrs.org/browse/OCLOMRS-593)
Add a pipeline to automatically create separate testing apps on every PR. This will make it easier to test proposed changes, as opposed to the current pull and build process.
=> OCLOMRS-593: Setup Heroku Pipeline for Review Apps

src/App.js, src/components/Notifications.jsx, src/redux/actions/bulkConcepts/index.js, src/redux/actions/concepts/addBulkConcepts/index.js, src/redux/actions/notifications/index.js, src/redux/reducers/index.js, src/redux/reducers/notificationsReducer.js, src/styles/all.scss, src/styles/notifications.scss, src/tests/bulkConcepts/actions/bulkConcept.test.js, src/tests/bulkConcepts/actions/index.test.js, src/tests/notifications/Notifications.test.js, src/tests/notifications/notificationsReducer.test.js
[When recursively importing concepts, a more informative spinner with what is actually going on is preferable](https://issues.openmrs.org/browse/OCLOMRS-640)
The way the loader is displayed when the concepts are being added is confusing. It looks like the page is loading. The minimum should be an improved message when this is going on, but this should ideally be a notification telling the user exactly what is happening.
=> OCLOMRS-640: When recursively importing concepts, a more informative spinner with what is actually going on is preferable

src/tests/Dashboard/reducer/conceptReducer.test.js
[Add tests to increase the test coverage](https://issues.openmrs.org/browse/OCLOMRS-648)
Add tests to increase the test coverage to address the drop observed in #502
=> OCLOMRS-648: Add tests to increase the test coverage

src/components/dictionaryConcepts/containers/CreateConcept.jsx, src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx, src/components/dictionaryConcepts/containers/EditConcept.jsx, src/redux/actions/concepts/dictionaryConcepts.js, src/redux/actions/dictionaries/dictionaryActionCreators.js
[A user should be able to view and manage collections belonging to organisations they are a part of- 2](https://issues.openmrs.org/browse/OCLOMRS-657)
- Some parts of the code have hard coded the owner of collections, concepts and mappings as the logged in user.
=> OCLOMRS-657: A user should be able to view and manage collections belonging to organisations they are a part of- 2

src/tests/dictionaryConcepts/container/SelectAnswers.test.js
[Raise Test Coverage](https://issues.openmrs.org/browse/OCLOMRS-619)
Raise Test Coverage and cover the drop realized in #498
=> OCLOMRS-619: Raise Test Coverage

src/components/dictionaryConcepts/components/AnswerRow.jsx, src/components/dictionaryConcepts/components/AnswersTable.jsx, src/components/dictionaryConcepts/components/ConceptNameRows.jsx, src/components/dictionaryConcepts/components/CreateConceptForm.jsx, src/components/dictionaryConcepts/components/CreateConceptTable.jsx, src/components/dictionaryConcepts/components/CreateMapping.jsx, src/components/dictionaryConcepts/components/DescriptionRow.jsx, src/components/dictionaryConcepts/components/DescriptionTable.jsx, src/components/dictionaryConcepts/components/MapType.jsx, src/styles/app.scss, src/styles/dashboard.scss, src/styles/dictionary_concepts.scss, src/styles/dictionary_modal.scss, src/tests/dictionaryConcepts/container/EditConcept.test.jsx
[Improve color and spacing on concept management page(edit and create concepts)](https://issues.openmrs.org/browse/OCLOMRS-662)
Currently, this page contains multiple colors, non uniform input styling and inconsistent spacing. This ticket aims at improving the design and color on this page to improve UX.
=> OCLOMRS-662: Improve color and spacing on concept management page(edit and create concepts)

src/tests/bulkConcepts/actions/index.test.js
[Raise test coverage](https://issues.openmrs.org/browse/OCLOMRS-681)
Address coverage drop in PRs #525 and #528
=> OCLOMRS-681: Raise test coverage

src/components/Navbar.js, src/components/dictionaryConcepts/components/ActionButtons.jsx, src/components/userDasboard/container/UserDashboard.jsx, src/styles/app.scss, src/styles/bulk_concepts.scss, src/styles/custom_variables.scss, src/styles/dashboard.scss, src/styles/dictionary_concepts.scss, src/styles/dictionary_modal.scss, src/styles/index.scss, src/styles/notifications.scss, src/styles/user_dashboard.scss
[Improve color coherence across application and move all app colors to single file](https://issues.openmrs.org/browse/OCLOMRS-663)
The application currently has multiple incoherent colors from page to page
The goal here is to cut this down to three colors max for a more coherent experience
This ticket also creates color variables , allowing for a single source of truth for all colors in the application
=> OCLOMRS-663: Improve color coherence across application and move all app colors to single file

src/App.js, src/components/dictionaryConcepts/components/ActionButtons.jsx, src/components/dictionaryConcepts/components/ViewConcept.jsx, src/components/dictionaryConcepts/components/ViewMapping.js, src/components/dictionaryConcepts/components/helperFunction.js, src/components/dictionaryConcepts/containers/ViewConceptContainer.js, src/styles/app.scss, src/styles/dictionary_concepts.scss, src/tests/__mocks__/concepts.js, src/tests/dictionaryConcepts/components/ViewConcept.test.jsx, src/tests/dictionaryConcepts/components/ViewMapping.test.jsx, src/tests/dictionaryConcepts/components/helperFunction.test.js, src/tests/dictionaryConcepts/container/DictionaryConcepts.test.jsx, src/tests/dictionaryConcepts/container/ViewConceptContainer.test.jsx
[Users should be able to view concepts in a dictionary](https://issues.openmrs.org/browse/OCLOMRS-539)
- Users should be able view a concept's details within the application
=> OCLOMRS-539: Users should be able to view concepts in a dictionary

src/components/dictionaryConcepts/components/ActionButtons.jsx, src/components/dictionaryConcepts/components/CreateConceptForm.jsx, src/components/dictionaryConcepts/components/helperFunction.js, src/components/dictionaryConcepts/containers/EditConcept.jsx, src/tests/dictionaryConcepts/components/ActionButtons.test.jsx, src/tests/dictionaryConcepts/components/CreateConceptForm.test.jsx, src/tests/dictionaryConcepts/container/EditConcept.test.jsx
[Change Symptom-Finding to Symptom/Finding in all areas](https://issues.openmrs.org/browse/OCLOMRS-695)
The 'Symptom/Finding' class is misappropriately named to 'Symptom-Finding'. This is preventing the creation of custom 'Symptom/Finding' concepts. This PR fixes this issue
=> OCLOMRS-695: Change  to Symptom/Finding in all cases

src/components/bulkConcepts/addBulkConcepts.jsx
[Add help text on bulk concepts page](https://issues.openmrs.org/browse/OCLOMRS-713)
This text should include relevant information about the format of the concepts to paste in this field, include expected data(CIEL ids) and how it should be formatted (commas, spaces, new lines) and common use case(copy and pasting from a spreadsheet)
=> OCLOMRS-713: Add help text on bulk concepts page

src/components/dictionaryConcepts/components/CreateConceptForm.jsx
Reverts openmrs/openmrs-ocl-client#554
=> Revert "OCLOMRS-712: The coded datatype should only be an option on pages where we can add answers to a concept"

src/components/dictionaryConcepts/components/CreateConceptForm.jsx
Reverts openmrs/openmrs-ocl-client#561
Reverting this again since it was not the source of the issue. :)
=> Revert "Revert "OCLOMRS-712: The coded datatype should only be an option on pages where we can add answers to a concept""

.travis.yml
[jira ticket Name](Url to the ticket)
=> Upgrading node version to 8.11.2

README.md
[jira ticket Name](Url to the ticket)
=> Improve the README.md for easy readability

src/components/dictionaryConcepts/components/CreateConceptForm.jsx
Changed text from Add set... to Add set member
Ticket: https://issues.openmrs.org/browse/OCLOMRS-737
=> OCLOMRS-737:Changed text from Add set... to Add set member

cypress/tsconfig.json, src/apps/authentication/tests/e2e/LoginPage.test.ts, src/apps/authentication/tests/e2e/testUtils.ts, src/apps/concepts/tests/e2e/CreateOrEditConceptPage.test.ts, src/apps/concepts/tests/e2e/ViewConceptsPage.test.ts, src/apps/concepts/tests/e2e/testUtils.ts, src/apps/dictionaries/tests/e2e/CreateDictionaryPage.test.ts, src/apps/dictionaries/tests/e2e/EditDictionaryPage.test.ts, src/apps/dictionaries/tests/e2e/ViewDictionaryPage.test.ts, src/components/NavDrawer.tsx, src/utils/components/AsyncSelect.tsx, start_local_instance.sh
[Add e2e testing to CI process.](https://issues.openmrs.org/browse/OCLOMRS-744)
=> OCLOMRS-744: Fix failing travis build

src/App.tsx, src/apps/concepts/pages/ViewConceptsPage.tsx, src/apps/concepts/tests/e2e/ViewConceptsPage.test.ts, src/apps/concepts/utils.ts, src/utils/constants.ts
[Allow searching all public sources when adding concepts.](https://issues.openmrs.org/browse/OCLOMRS-769)
Allow searching all public sources when adding concepts. Currently a choice between either CIEL or PIH.
=> OCLOMRS-769: Allow searching all public sources when adding concepts.

src/apps/dictionaries/pages/EditDictionaryPage.tsx
[Edit dictionary page should have a cancel button.](https://issues.openmrs.org/browse/OCLOMRS-767)
=> OCLOMRS-767: Edit dictionary page should have a cancel button.

package.json, src/apps/concepts/pages/tests/e2e/ViewConceptsPage.test.ts, src/apps/dictionaries/api.ts, src/apps/dictionaries/components/ReleasedVersions.tsx, src/apps/dictionaries/components/__test__/ReleasedVersions.test.tsx, src/apps/dictionaries/pages/ViewDictionaryPage.tsx, src/apps/dictionaries/redux/actionTypes.ts, src/apps/dictionaries/redux/actions.ts, src/apps/dictionaries/redux/reducer.ts, src/utils/components/ConfirmationDialog.tsx
[OCLOMRS-832](https://issues.openmrs.org/browse/OCLOMRS-832)
[OCLOMRS-833](https://issues.openmrs.org/browse/OCLOMRS-833)
[TW] As a user, I want to differentiate the released version of a collection from the unreleased ones so that the user is clear about the active collection in the subscription
[TW] As a user, I want to differentiate the released version of a collection from the unreleased ones so that the user is clear about the active collection in the subscription
=> OCLOMRS-832,  OCLOMRS-833

src/apps/concepts/pages/tests/e2e/ViewConceptsPage.test.ts, src/apps/dictionaries/pages/AddBulkConceptsPage.tsx, src/apps/dictionaries/redux/actions.ts, src/apps/dictionaries/utils.ts, src/components/ActionsInProgressPage.tsx, src/components/NavDrawer.tsx, src/redux/__test__/localStorageUtils.test.ts, src/redux/localStorageUtils.ts
* Bindu | OCLOMRS-848 | MOBN-1407 | persist notification data into localstorage
* Bindu | OCLOMRS-848 | MOBN-1407 | Adding test cases for localStorageUtil
* Bindu | OCLOMRS-848 | MOBN-1407 | Addressed the feedback changes
* Bindu | OCLOMRS-848 | MOBN-1407 | Adding check for empty results array
[OCLOMRS-848](https://issues.openmrs.org/projects/OCLOMRS/issues/OCLOMRS-848)
As a user performing a bulk-upload of concepts, I need to see a progress bar and confirmation of successful (or unsuccessful/incomplete) upload.
=> Bindu | OCLOMRS-848 | MOBN-1407 |Progress bar and concept upload seems to fail

package.json, src/apps/authentication/api.ts, src/apps/authentication/redux/actions.ts, src/apps/authentication/tests/api.test.ts, src/apps/dictionaries/components/DictionaryForm.tsx, src/apps/dictionaries/constants.ts, src/apps/sources/pages/ViewSourcePage.tsx
*Bindu, Supriya | OCLOMRS-872 | MOBN-1443 | Update the organisation API GET call to … (#33)
* Bindu, Supriya | OCLOMRS-872 | MOBN-1443 | Update the organisation API GET call to fetch only user specific organisations
* Supriya, Bindu | OCLOMRS-872 | MOBN-1443 | Handling review comments
* Bindu, Supriya | OCLOMRS-872 | MOBN-1443 | Make the order of dictionary tabs same as source page
[OCLOMRS-872](https://issues.openmrs.org/browse/OCLOMRS-872)
As a user, I should be able to see all the organisations that i am part of in the create dictionary page
=> Bindu, Supriya | OCLOMRS-872 | MOBN-1443 | Remove the limitation on the List of Organizations displayed in the Owner dropdown

src/App.tsx, src/apps/authentication/__test__/components/UserForm.test.tsx, src/apps/authentication/__test__/components/UserOrganisationDetails.test.tsx, src/apps/authentication/__test__/components/UserTokenDetails.test.tsx, src/apps/authentication/__test__/pages/ViewUserProfilePage.test.tsx, src/apps/authentication/__test__/test_data.ts, src/apps/authentication/components/UserForm.tsx, src/apps/authentication/components/UserOrganisationDetails.tsx, src/apps/authentication/components/UserTokenDetails.tsx, src/apps/authentication/components/index.tsx, src/apps/authentication/pages/ViewUserProfilePage.tsx, src/apps/authentication/pages/index.ts, src/apps/authentication/types.ts, src/components/NavDrawer.tsx, src/index.scss
[OCLOMRS-882](https://issues.openmrs.org/browse/OCLOMRS-882)
Create a user profile page
=> Tarun, Supriya | OCLOMRS-882 | MOBN-1428 | Create a user profile page

src/apps/concepts/__test__/components/AddConceptsIcon.test.tsx, src/apps/concepts/__test__/pages/ViewConceptsPage.test.tsx, src/apps/concepts/components/AddConceptsIcon.tsx, src/apps/concepts/components/index.ts, src/apps/concepts/pages/ViewConceptsPage.tsx
* Tarun, Bindu | OCLOMRS-881 | Add create concept button to create custom concepts in source
* Tarun, Bindu | OCLOMRS-881 | Refactored code and added new unit tests
* Tarun, Bindu | OCLOMRS-881 | Add snapshot tests for AddConceptsIcon component and refactored ViewConceptsPage test cases
* Bindu, Tarun | OCLOMRS-881 | Handled feedback changes
[OCLOMRS-881](https://issues.openmrs.org/browse/OCLOMRS-881)
As a user, I want to add concepts to source
=> Tarun, Bindu | OCLOMRS-881 | Create new concepts within a Source (#36)

.gitignore, cypress/support/commands.js, src/apps/authentication/__test__/utils.test.ts, src/apps/concepts/__test__/components/ConceptsActionMenu.test.tsx, src/apps/concepts/__test__/components/ConceptsTable.test.tsx, src/apps/concepts/__test__/components/EnhancedTableHead.test.tsx, src/apps/concepts/__test__/components/EnhancedTableToolbar.test.tsx, src/apps/concepts/__test__/utils.test.ts, src/apps/concepts/components/ConceptsActionMenu.tsx, src/apps/concepts/components/ConceptsTable.tsx, src/apps/concepts/components/ConceptsTableRow.tsx, src/apps/concepts/components/EnhancedTableHead.tsx, src/apps/concepts/components/EnhancedTableToolbar.tsx, src/apps/concepts/pages/ViewConceptsPage.tsx, src/apps/concepts/pages/tests/e2e/ViewConceptsPage.test.ts, src/index.scss
Co-authored-by: Kirity Mahanty <kirity.mahanty@thoughtworks.com>
[JIRA ticket name](https://issues.openmrs.org/browse/OCLOMRS-883)
As a user
I want to see relevant options against each of the concept in my source
So that I can perform the necessary actions as per my need
=> Rakesh, Kirity | OCLOMRS-883 | MOBN-1445 | Define the actions for concepts inside a Source (#39)

src/apps/concepts/components/ConceptForm.tsx, src/apps/concepts/components/MappingsTable.tsx, src/apps/concepts/components/MappingsTableRow.tsx, src/apps/concepts/components/NamesTable.tsx, src/apps/concepts/pages/tests/e2e/testUtils.ts, src/utils/components/AsyncSelect.tsx
[OCLOMRS-885](https://issues.openmrs.org/browse/OCLOMRS-885)
Concept details page - Change the UI component that displays the concept ID and Name
=> Tarun, Supriya | OCLOMRS-885 | MOBN-1461 | Fix css in create concept page

src/apps/dictionaries/__test__/utils.test.ts, src/apps/dictionaries/redux/actions.ts, src/apps/dictionaries/types.ts, src/apps/dictionaries/utils.ts, src/components/ActionsInProgressPage.tsx, src/components/NotificationCard.tsx, src/components/__test__/NotificationCard.test.tsx, src/redux/__test__/localStorageUtils.test.ts, src/redux/localStorageUtils.ts
Vinisha, Kirity | MOBN-1459 | Add concepts import initiated dateTime in notification page (#46)
* Vinisha, Kirity | MOBN-1459 | Add concepts import initiated dateTime in notification page
Vinisha, Kirity | MOBN-1459 | Added few styles for notification page
Vinisha, Kirity | MOBN-1459 | Remove console log and unused code
Vinisha, Kirity | MOBN-1459 | Snapshot test for NotificationCard and some refactoring
Vinisha, Kirity | MOBN-1459 | Add tests for util function
* Vinisha, Kirity | MOBN-1459 | Added importMetaData length check in notification page
* Tarun, Rakesh | MOBN-1467 | Fix the inconsistency in progress notification tab
Co-authored-by: Kirity Mahanty <kirity.mahanty@thoughtworks.com>
[OCLOMRS-886](https://issues.openmrs.org/browse/OCLOMRS-886)
Today the notifications do not have the …
=> Vinisha, Kirity | OCLOMRS-886 | MOBN-1467 | Add concepts import initiated dateTime in notification page

src/apps/authentication/__test__/redux/reducer.test.ts, src/apps/authentication/redux/reducer.ts, src/apps/notifications/components/NotificationDetails.tsx, src/redux/__test__/reducer.test.ts, src/redux/reducer.ts
[OCLOMRS-895](https://issues.openmrs.org/browse/OCLOMRS-895)
Even after logout few things are not cleared form state while is resulting in some improper behaviour in notifications page.
In some of the scenarios, in notification bar user getting long error message for failed import. We need to see if we can reduce the error message to get a comfortable view for user.
=> Vinisha, Kirity | OCLOMRS-895 | MOBN-1475 | Clear status state and auth state on logout

src/components/Header.tsx, src/components/NavDrawer.tsx
[OCLOMRS-857](https://issues.openmrs.org/browse/OCLOMRS-857)
fix "Back button and title hidden by expanded side nav or NavDrawer"
=> OCLOMRS-857 Back button and title hidden by expanded side nav

src/apps/organisations/components/OrgDetails.tsx, src/apps/organisations/components/OrgDictionaries.tsx, src/apps/organisations/components/OrgSources.tsx
[Should make sources and dictionaries with in an organization links.](https://issues.openmrs.org/browse/OCLOMRS-920)
- Made organization sources and collections links.
=> OCLOMRS-920: Make sources and collections links.

src/apps/organisations/api.ts, src/apps/organisations/components/OrgMembers.tsx, src/apps/organisations/pages/ViewOrgPage.tsx, src/apps/organisations/redux/actionTypes.ts, src/apps/organisations/redux/actions.ts, src/apps/organisations/redux/index.ts, src/apps/organisations/redux/reducer.ts, src/apps/organisations/types.ts
[OCLOMRS-914](https://issues.openmrs.org/browse/OCLOMRS-914)
=> OCLOMRS-914:Organization Members UI

src/apps/organisations/api.ts, src/apps/organisations/components/AddMemberForm.tsx, src/apps/organisations/components/OrgMembers.tsx, src/apps/organisations/pages/ViewOrgPage.tsx, src/apps/organisations/redux/actionTypes.ts, src/apps/organisations/redux/actions.ts, src/apps/organisations/redux/index.ts, src/apps/organisations/redux/reducer.ts, src/apps/organisations/redux/selectors.ts, src/apps/organisations/types.ts
[Add new member to an organization](https://issues.openmrs.org/browse/OCLOMRS-924)
- I can't test it working yet, not sure if it's because of permissions, but I am reaching out to the backend people to help me.
=> OCLOMRS-924: Adds new member to an organisation.

src/apps/organisations/api.ts, src/apps/organisations/components/OrgMembers.tsx, src/apps/organisations/pages/ViewOrgPage.tsx, src/apps/organisations/redux/actionTypes.ts, src/apps/organisations/redux/actions.ts, src/apps/organisations/redux/selectors.ts
[Delete members in an organisation](https://issues.openmrs.org/browse/OCLOMRS-925)
=> OCLOMRS-925:Delete members in an organisation

src/apps/concepts/pages/ViewConceptPage.tsx
[OCLOMRS-875:Strange Concept Name formatting](https://issues.openmrs.org/browse/OCLOMRS-875)
removed the formatting of Concept Name
=> OCLOMRS-875 : removed the strange Concept Name formatting

src/App.tsx, src/apps/dictionaries/Routes.tsx, src/apps/dictionaries/pages/CreateDictionaryPage.tsx, src/apps/dictionaries/pages/ViewDictionaryPage.tsx, src/apps/dictionaries/utils.ts, src/apps/organisations/pages/CreateOrgPage.tsx, src/apps/organisations/pages/EditOrgPage.tsx, src/apps/organisations/utils.ts, src/apps/sources/pages/CreateSourcePage.tsx, src/apps/sources/pages/ViewSourcePage.tsx
Issue worked on:
[OCLOMRS-930](https://issues.openmrs.org/browse/OCLOMRS-930)
- I Created back arrow on the create pages(Dictionary, Source & Organistion) and General details pages
- The tests are all running.
=> OCLOMRS-930 - Created back arrow on the create pages(Dictionary, Source & Organistion) and General details pages

src/apps/containers/components/ContainerVersionForm.tsx, src/apps/dictionaries/components/DictionaryVersionForm.tsx, src/redux/utils.ts
[OCLOMRS-890](https://issues.openmrs.org/browse/OCLOMRS-890)
=> OCLOMRS-890:added clear error message for :release ID already exists

src/apps/authentication/LoginPage.tsx, src/apps/authentication/components/AuthenticationRequired.tsx, src/apps/authentication/redux/actionTypes.ts, src/apps/authentication/redux/actions.ts, src/apps/authentication/redux/index.ts, src/apps/authentication/redux/reducer.ts, src/apps/authentication/types.ts
[As a user, I want to be able to go directly to the page I was trying to access after logging in.](https://issues.openmrs.org/browse/OCLOMRS-898)
How to allow users access their intended url instead of redirecting them back to the home page.
My routes are
=> OCLOMRS-898:As a user, I want to be able to go directly to the page I  was trying to access after logging in

docker-compose.yml, src/apps/authentication/components/Login.tsx, src/utils/constants.ts, startup.sh
[OCLOMRS-931](https://issues.openmrs.org/browse/OCLOMRS-931)
Allows the sign-up link on the login screen to be driven via an environment variable.
=> OCLOMRS-931: Allow signup link to be controlled via environment variable

src/apps/concepts/pages/CreateOrEditConceptPage.tsx
[JIRA OCLOMRS-875 ](https://issues.openmrs.org/browse/OCLOMRS-875 )
The string formatting on the edit Concept page is removed in this PR
this PR is an extension of https://github.com/openmrs/openmrs-ocl-client/pull/649
=> OCLOMRS-875 : strange concept on edit Concept page

src/apps/organisations/api.ts, src/apps/organisations/components/ViewOrgsPage.tsx, src/apps/organisations/pages/ViewPersonalOrgs.tsx
[My Organisations view displays all organisations by default](https://issues.openmrs.org/browse/OCLOMRS-951)
- The "My Organizations" page should only show organizations that the user is a member of.
=> OCLOMRS-951: My Organisations view displays all organisations by default

src/apps/authentication/components/UserOrganisationDetails.tsx, src/apps/organisations/components/ViewOrgsPage.tsx, src/apps/organisations/constants.ts
[Temporariliy hide the "My Organisations" view](https://issues.openmrs.org/browse/OCLOMRS-957)
Temporarily hides the "My Organisations" view and makes the organisations in the user profile clickable links.
=> OCLOMRS-957: Hide the "My Organisations" view

src/apps/dictionaries/components/DictionaryForm.tsx, src/apps/dictionaries/pages/CreateDictionaryPage.tsx, src/apps/dictionaries/types.ts, src/apps/sources/components/SourceForm.tsx, src/apps/sources/pages/CreateSourcePage.tsx, src/apps/sources/pages/ViewSourcePage.tsx, src/apps/sources/types.ts
[OCLOMRS-936](https://issues.openmrs.org/browse/OCLOMRS-936)
I Fixed  the overlapping fieldset for General details of a dictionary and a source, display the hidden inputs on the owner field in viewing and editing mode
=> OCLOMRS-936: Fixed overlapping fieldsets and hidden inputs for sources and dictionaries

src/apps/concepts/api.ts, src/apps/concepts/components/FilterOptions.tsx, src/apps/concepts/constants.ts, src/apps/concepts/pages/ViewConceptsPage.tsx, src/apps/concepts/types.ts, src/apps/sources/pages/ViewSourcePage.tsx, src/utils/constants.ts
[OCLOMRS-932: Add Filter option to include Retired Concepts](https://issues.openmrs.org/browse/OCLOMRS-932)
=> OCLOMRS-932: Add Filter option to include Retired Concepts

src/apps/concepts/components/MappingsTableRow.tsx, src/apps/concepts/redux/actions.ts, src/apps/concepts/types.ts
[Resolve CIEL Set Member & Mapping names](https://issues.openmrs.org/browse/OCLOMRS-976)
I added to_concept_name_resolved to the Mapping interface defined [here](https://github.com/openmrs/openmrs-ocl-client/blob/master/src/apps/concepts/types.ts#L18). Then changed the definition of `toConceptName` which is currently defined [here](https://github.com/openmrs/openmrs-ocl-client/blob/8c1b83bff55002f4aad9fa72b22275767179f414/src/apps/concepts/components/MappingsTableRow.tsx#L246)). Essentially, that line should change to to_concept_name, and after that we should add to_concept_name_resolved. Then inside the body of the function we should have:
=> OCLOMRS-976:Resolve CIEL Set Member & Mapping names

docker-compose.yml, src/utils/constants.ts
#OCLOMRS-978:
[Update SignUp links to new OCL links](https://issues.openmrs.org/browse/OCLOMRS-978)
=> OCLOMRS-978: Update SignUp links to new OCL links

src/apps/concepts/__test__/components/ConceptsTable.test.tsx, src/apps/concepts/components/ConceptsTable.tsx, src/apps/concepts/components/ConceptsTableRow.tsx, src/apps/concepts/types.ts
[Show Concept's Source in Column in Concept List](https://issues.openmrs.org/browse/OCLOMRS-980)
- Added a source column in the concepts table
=> OCLOMRS-980: Add source column in the concepts table.

src/apps/concepts/components/ConceptsTable.tsx, src/apps/concepts/components/FilterOptions.tsx, src/apps/concepts/components/ViewConceptsHeader.tsx, src/apps/concepts/pages/ViewConceptsPage.tsx, src/components/Header.tsx
[Make header stick to the top](https://issues.openmrs.org/browse/OCLOMRS-964)
=> OCLOMRS-964: Make header stick to the top

src/apps/concepts/components/ViewConceptsHeader.tsx, src/apps/concepts/pages/ViewConceptsPage.tsx, src/utils/constants.ts
[Set Source to whatever user want it to be (maybe “Your Recent Sources” instead of hardcoded)](https://issues.openmrs.org/browse/OCLOMRS-965)
=> OCLOMRS-965:Set Source to whatever user want it to be (maybe “Your Recent Sources” instead of hardcoded)

cypress/integration/dictionary/create.feature, cypress/integration/dictionary/edit.feature, cypress/support/commands.ts, cypress/support/index.d.ts, cypress/support/step_definitions/common/common.ts, cypress/support/step_definitions/dictionary/create/create.ts, cypress/support/step_definitions/dictionary/edit/edit.ts, cypress/support/step_definitions/login/login.ts, cypress/support/utils.ts, cypress/utils.ts, package-lock.json, src/apps/dictionaries/redux/actions.ts, src/redux/store.ts, src/utils/types.ts
Also adds Cypress tests to confirm that the feature behaves as expected
[When creating a public dictionary, the source should also be public](https://issues.openmrs.org/browse/OCLOMRS-1010)
When a public dictionary is created, the source is also public. When a private dictionary is created, the source is private. When the dictionary visibility changes the source visibility changes to match.
=> OCLOMRS-1010: Creating a public dictionary should create a public source

src/apps/organisations/__test__/components/viewOrganisations.test.tsx, src/apps/organisations/__tests__/components/viewOrganisations.test.tsx
[View Organisations page/component unit tests](https://issues.openmrs.org/browse/OCLOMRS-1005)
- Add some unit tests for the view organizations page.
=> OCLOMRS-1005: View organisations test

.github/workflows/dictionary-manager.yml
[Personalise our .yml file and add OCL status badge to the QA dashboard](https://issues.openmrs.org/browse/OCLOMRS-1017)
- The original workflow would show up as `Build with Node` so I have created a new workflow that is personalized for the dictionary manager.
=> OCLOMRS-1017: Personalise our .yml file and add OCL status badge to the QA dashboard

src/apps/containers/components/ContainerSearch.tsx
[The toggle to show verified results should have a clearer label](https://issues.openmrs.org/browse/OCLOMRS-1034)
The label of Toggle to show the verified result is changed from **Showing all results** to **Show Verified Only** for Off state
=> OCLOMRS-1034:The toggle to show verified results should have a clearer label

src/apps/dictionaries/constants.ts, src/apps/organisations/constants.ts, src/apps/sources/constants.ts, src/components/NavDrawer.tsx
[Add a tab to view "My Organizations" to the organizations view](https://issues.openmrs.org/browse/OCLOMRS-1033)
- Put back the My Organisations tab.
=> OCLOMRS-1033: Add a tab to view "My Organizations" to the organizations view

src/apps/dictionaries/logic.ts
[ Only add concepts mapped as answers of concept set members](https://issues.openmrs.org/browse/OCLOMRS-1015)
- Only add concepts mapped as answers or concept sets.
=> OCLOMRS-1015: Only add concepts mapped as answers or concept set members

cypress/integration/organisation/addMember.feature, cypress/integration/organisation/deleteMember.feature, cypress/support/commands.ts, cypress/support/index.d.ts, cypress/support/step_definitions/common/common.ts, cypress/support/step_definitions/organisation/addMember/addMember.ts, cypress/support/step_definitions/organisation/deleteMember/deleteMember.ts, cypress/support/utils.ts, src/apps/authentication/__test__/test_data.ts, src/apps/organisations/components/DeleteMemberDialog.tsx, src/apps/organisations/components/OrgMembers.tsx, src/apps/organisations/redux/actions.ts, src/apps/organisations/redux/reducer.ts, src/apps/organisations/types.ts, src/apps/sources/__test__/test_data.ts
[Automated test: Add and delete members in an organization](https://issues.openmrs.org/browse/OCLOMRS-1025)
[Delete Member dialog doesn't differentiate the actual member.](https://issues.openmrs.org/browse/OCLOMRS-1057)
Automated test for adding and deleting members in a organization.
Fixed the delete member dialog which was deleting the wrong user.
=> OCLOMRS-1025:Automated test: Add and delete members in an organization

cypress/integration/organisation/details.feature, cypress/support/commands.ts, cypress/support/index.d.ts, cypress/support/step_definitions/organisation/create/create.ts, cypress/support/step_definitions/organisation/details/details.ts
[Automated test: View Organisation details page/ Sources and Collections section](https://issues.openmrs.org/browse/OCLOMRS-1026)
- Implements organisation details page, at least test out the sources section
=> OCLOMRS-1026: Add automated tests to View Organisation Sources and Collections

src/apps/concepts/components/ConceptsTable.tsx, src/apps/concepts/components/ConceptsTableRow.tsx, src/apps/concepts/pages/ViewConceptsPage.tsx, src/apps/concepts/types.ts
[Pick concepts - Choice issue with same IDs](https://issues.openmrs.org/browse/OCLOMRS-1051)
Issue fixed for choosing concepts with same IDs while picking concepts
=> OCLOMRS-1051:Pick concepts - Choice issue with same IDs

src/apps/concepts/components/ViewConceptsHeader.tsx
[Fix source selection menu in pick concept view](https://issues.openmrs.org/browse/OCLOMRS-1079)
Fixed the color of source selection button to display in UI
=> OCLOMRS-1079:Fix source selection menu in pick concept view

src/apps/concepts/components/ConceptSpeedDial.tsx, src/apps/concepts/pages/ViewConceptPage.tsx
[Cannot import existing concepts by picking](https://issues.openmrs.org/browse/OCLOMRS-1084)
- Enable adding of a concept on the view concept page.
=> OCLOMRS-1084: Cannot import existing concepts by picking.
