docker-compose.yml

OCLOMRS-27: getting a docker compose
The currently one doesn't work. 
This one has the proper healthcheck, also it points to a new image that you can build locally.

Getting a working docker-compose file

---

.gitignore
README.md
package.json

So, I'd like to configure Bamboo to parse logs results from this project, like:
https://pasteboard.co/HmEpmxo.png
Bamboo can parse junit and mocha (mostly), so I'd like to configure junit. 
I do believe it probably won't affect other functionalities.

Allow Node tests to be parsed by Bamboo build

---

src/config/axiosConfig.js
src/redux/actions/auth/authActions.js

[OCLOMRS-43](https://issues.openmrs.org/browse/OCLOMRS-43)
Currently, the API calls are made from the production version openconceptlab.org and they should be made from the QA version at api.qa.openconceptlab.org
The PR seeks to solve that :)

OCLOMRS-43: Changing the API call  url from production to QA

---

src/App.js
src/components/Navbar.js

[OCLOMRS-46](https://issues.openmrs.org/projects/OCLOMRS/issues/OCLOMRS-46)
Currently, the notifications are being hidden by the navigation bar, as a standard practice, notifications should always appear over the navigation bar as the screenshot below shows. This task involves a fix that will ensure  notifications are visible over the navigation bar.

OCLOMRS-46 : Notifications bug fix

---

src/redux/actions/dictionaries/dictionaryActionCreators.js
src/redux/api.js
src/tests/Dashboard/action/dictionaryAction.test.js

[OCLOMRS-55](https://issues.openmrs.org/browse/OCLOMRS-55)
A fix to show the loader right during the fetching process of dictionaries

OCLOMRS-55: Fix the loader right before the dictionaries are retrieved

---

src/components/dashboard/components/dictionary/DictionariesSearch.jsx
src/components/dashboard/components/dictionary/ListDictionaries.jsx
src/components/dashboard/components/dictionary/user/UserDashboard.jsx
src/components/dashboard/container/DictionariesDisplay.jsx
src/components/dashboard/styles/index.css
src/redux/actions/dictionaries/dictionaryActionCreators.js
src/tests/Dashboard/container/DictionaryDisplay.test.jsx
src/tests/Dictionary/UserDashboard.test.jsx

[OCLOMRS-54](https://issues.openmrs.org/browse/OCLOMRS-54)
As a user after adding dictionaries, I want to view my dictionaries and also the dictionaries for all other OpenMRS organizations and users. 
A filter should be put in place to enable a user toggle between their dictionaries and all the dictionaries on the platform, the default should, however, be the dictionaries that have been created by the logged in user, either as personal dictionaries or as dictionaries belonging to their organizations.

OCLOMRS-54: A user should be able to view their personal dictionaries and dictionaries belonging to all other organizations and users

---

src/App.js
src/components/dashboard/components/SourceCard.jsx
src/components/dashboard/container/SpecificConcept.jsx
src/redux/actions/concepts/specificConceptAction.js
src/tests/Dashboard/action/specificConceptAction.test.js

[OCLOMRS-71: Fix the bug for concepts in a source not displaying when the owner is not an organization](https://issues.openmrs.org/browse/OCLOMRS-71)
At the moment when viewing concepts in a source created by an owner that is not an organization, they are not displayed even when they exist which should not be the case.

OCLOMRS-71: Fix the bug for concepts in a source not displaying when the owner is not an organization

---

src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx
src/tests/dictionaryConcepts/container/DictionaryConcepts.test.jsx

[Fix dictionary name](https://issues.openmrs.org/browse/OCLOMRS-82)
Currently, the name shown as the name of the dictionary in the *dictionary concept* page is the username of the user currently using the app, modify the code to display the actual dictionary name instead.

OCLOMRS-82: fix dictionary name

---

src/components/dictionaryConcepts/containers/CreateConcept.jsx
src/config/axiosConfig.js
src/redux/actions/concepts/dictionaryConcepts.js
src/redux/actions/types.js
src/redux/reducers/ConceptReducers.js
src/tests/Dashboard/reducer/conceptReducer.test.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js
src/tests/dictionaryConcepts/container/CreateConcept.test.jsx
src/tests/dictionaryConcepts/reducer/dictionaryConcept.test.js

[As a user, I should see my newly created concept in my dictionary](https://issues.openmrs.org/browse/OCLOMRS-77)
A newly created concept should be automatically added to a user's dictionary from the user's source.
Dev notes:
A newly created concept by default will be added to a source, you are to make sure it is added to collections(dictionary) at the point of creation as well.

OCLOMRS-77: Add newly created concept to user dictionary

---

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx

[OCLOMRS-90: Remove the placeholder in the Add Dictionary modal](https://issues.openmrs.org/browse/OCLOMRS-90)
A user should only see a placeholder that makes sense for example if an input's label is "Dictionary Name" then the placeholder should not repeat the label.

OCLOMRS-90: Remove the place holder in the Add Dictionary modal

---

src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx
src/components/dictionaryConcepts/components/Header.jsx
src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx

[Connect the concept page with the dictionary overview page](https://issues.openmrs.org/browse/OCLOMRS-79)
As a user, while viewing the dictionary overview page, I should be able to click on `Go to concepts` button to see all the concepts in that dictionary.

OCLOMRS-79: Connect the concept page with the dictionary overview page

---

src/components/dashboard/components/concepts/SpecificConceptTable.jsx
src/components/dashboard/container/SpecificConcept.jsx
src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx
src/redux/actions/concepts/addExistingConcepts/index.js
src/redux/actions/types.js
src/tests/Dashboard/addExistingConcepts/actions/index.test.js
src/tests/Dashboard/addExistingConcepts/specificConceptTable.test.jsx
src/tests/Dashboard/container/SpecificConcept.test.jsx

[OCLOMRS-68: Implement logic for adding CIEL concepts to a dictionary](https://issues.openmrs.org/browse/OCLOMRS-68)
- This happens after the user clicks the button to add CIEL concepts, It will show all concepts in CIEL source each with the Add button link infront, so a user can add one or multiple concepts by clicking the add link. And then when they navigate back to their dictionary they can see the concepts they added.

OCLOMRS-68: Implement logic for adding CIEL concepts to a dictionary

---

src/components/dashboard/container/DictionariesDisplay.jsx
src/components/dashboard/styles/index.css

[OCLOMRS-103: Enable viewing own dictionaries when on public dictionaries interface](https://issues.openmrs.org/browse/OCLOMRS-103)
Currently, when a user is viewing public dictionaries, they are unable to return to their own dictionaries aside from clicking the application name to return them to the home page, which should not be the case

OCLOMRS-103: Enable viewing own dictionaries when on public dictionaries interface

---

src/App.js
src/components/dashboard/components/dictionary/DictionaryCard.jsx
src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx
src/components/dashboard/components/dictionary/common/DictionaryModal.jsx
src/components/dictionaryConcepts/components/ConceptNameRows.jsx
src/components/dictionaryConcepts/components/CreateConceptForm.jsx
src/components/dictionaryConcepts/components/CreateConceptTable.jsx
src/components/dictionaryConcepts/components/DescriptionRow.jsx
src/components/dictionaryConcepts/components/DescriptionTable.jsx
src/components/dictionaryConcepts/containers/CreateConcept.jsx
src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx
src/components/dictionaryConcepts/style/index.css
src/tests/dictionaryConcepts/container/DictionaryConcepts.test.jsx

[OCLOMRS-94: Rework the concept creation page](https://issues.openmrs.org/browse/OCLOMRS-94)
Based on feedback received, the following should be rearranged:
- The datatype select element should be below the class select element
- The name column should come before the language column in both the Names and Description section.
- The language should be preloaded with the language of the dictionary itself
- Default value for datatype should be 'N/A'

OCLOMRS-94: Rework the concept creation page

---

src/components/dashboard/container/DictionariesDisplay.jsx

[OCLOMRS-107: Fix the link to view own dictionaries redirecting to wrong dashboard when viewing public dictionaries](https://issues.openmrs.org/browse/OCLOMRS-107)
Currently, when you click the link to go back to your dictionaries, you are redirected to the wrong dashboard. This should not be the case since changes had been made to the dashboard and a new component was created.

OCLOMRS-107: Fix the link to view own dictionaries redirecting to wrong dashboard when viewing public dictionaries

---

src/components/dashboard/container/SpecificConcept.jsx
src/tests/Dashboard/container/SpecificConcept.test.jsx

[OCLOMRS-112: Fix the links from specific concepts going back to a dictionary or sources](https://issues.openmrs.org/browse/OCLOMRS-112)
- Currently when a user is viewing concepts within a source, and then tries to go back it throws a 404 and the message displayed is also misleading.

OCLOMRS-112: Fix the links from specific concepts going back to a dictionary or sources

---

src/components/dictionaryConcepts/components/CreateConceptForm.jsx

[OCLOMRS-126: Change the naming of the submit button on create concept page](https://issues.openmrs.org/browse/OCLOMRS-126)
Currently, the creating concept button indicates “submit”, but this should say either be “save” or “create”

OCLOMRS-126: Change the naming of the submit button on create concept page

---

src/components/dictionaryConcepts/containers/CreateConcept.jsx
src/tests/dictionaryConcepts/container/CreateConcept.test.jsx

[OCLOMRS-130: Change the header naming on the create concept form](https://issues.openmrs.org/browse/OCLOMRS-130)
Currently, the heading indicates “in source: DTD custom concepts” DTD is a short code, which isn’t consistent with showing the full name of the dictionary.
The heading should only indicate “Dictionary Name: Create a Diagnosis Concept” on a single line.

OCLOMRS-130: Change the header naming on the create concept form

---

.gitignore
src/App.css
src/components/dashboard/components/dictionary/DictionaryCard.jsx
src/components/dashboard/components/dictionary/ListDictionaries.jsx
src/components/dashboard/container/DictionariesDisplay.jsx
src/components/userDasboard/components/CardWrapper.jsx
src/components/userDasboard/container/UserDashboard.jsx
src/tests/Dashboard/container/DictionaryDisplay.test.jsx
src/tests/userDashboard/container/UserDashboard.test.jsx

[Make the entire dictionary card clickable](https://issues.openmrs.org/browse/OCLOMRS-118)
Should make the entire card clickable, and it should redirect to the dictionary overview instead of having another option redirecting to the concepts page.

OCLOMRS:118: Make the entire dictionary card clickable

---

src/components/bulkConcepts/addBulkConcepts.jsx
src/components/bulkConcepts/bulkConceptList.jsx
src/components/bulkConcepts/bulkConceptTable.jsx
src/components/bulkConcepts/style.css
src/redux/actions/bulkConcepts/index.js
src/redux/actions/types.js
src/redux/reducers/bulkConcepts/index.js
src/redux/reducers/index.js
src/tests/bulkConcepts/actions/index.test.js
src/tests/bulkConcepts/addBulkConcepts.test.jsx
src/tests/bulkConcepts/bulkConceptList.test.jsx
src/tests/bulkConcepts/bulkConceptTable.test.jsx
src/tests/bulkConcepts/reducers/index.test.js

[OCLOMRS-140: Implement the retrieval of CIEL concepts on the bulk concept page](https://issues.openmrs.org/browse/OCLOMRS-140)
- This involves implementing the logic for clicking the CIEL radio button and populating the field with CIEL concept IDs.
- Write tests to ensure functionality is working.

OCLOMRS-140: Implement the retrieval of CIEL concepts on the bulk concept page

---

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx

[Fix the preferred source grammar on Add Dictionary Modal](https://issues.openmrs.org/browse/OCLOMRS-132)
Currently, the modal indicates “Preferred Sources” yet a user is only allowed to select 1. 
The naming should change it to singular i.e.“preferred source”

OCLOMRS-132: Fix the preferred source grammar on Add Dictionary Modal

---

src/components/dictionaryConcepts/components/CreateConceptTable.jsx
src/components/dictionaryConcepts/components/DescriptionTable.jsx

[Fix the row added after the user clicks Add Name/Synonym and Add Description buttons](https://issues.openmrs.org/browse/OCLOMRS-125)
Currently, when “Add name/synonym” or "Add descriptrion" buttons are clicked the row should be added to the bottom instead of the top of the list.

OCLOMRS-125: Fix the row added after the user clicks Add Name/Synonym and Add Description buttons

---

src/components/dictionaryConcepts/components/ConceptNameRows.jsx
src/components/dictionaryConcepts/components/DescriptionRow.jsx
src/components/dictionaryConcepts/containers/CreateConcept.jsx
src/tests/dictionaryConcepts/container/CreateConcept.test.jsx

[OCLOMRS-128: Fix the functionality for creating a custom concept.](https://issues.openmrs.org/browse/OCLOMRS-128)
Currently, when a user tries to create a concept an error indicating "the uuid must be unique" is thrown which should not be the case.

OCLOMRS-128: Fix the functionality for creating a custom concept.

---

src/components/bulkConcepts/addBulkConcepts.jsx
src/redux/actions/bulkConcepts/index.js
src/redux/actions/types.js
src/tests/bulkConcepts/actions/index.test.js
src/tests/bulkConcepts/addBulkConcepts.test.jsx

[OCLOMRS-142: Implement the logic for adding the retrieved CIEL concepts to a dictionary](https://issues.openmrs.org/browse/OCLOMRS-142)
- This is the logic that is executed when you click the Add All button on the bulk concept page.

OCLOMRS-142: Implement the logic for adding the retrieved CIEL concepts to a dictionary

---

src/components/bulkConcepts/component/ActionButtons.jsx
src/components/bulkConcepts/component/SideNavItems.jsx
src/components/bulkConcepts/component/Sidenav.jsx
src/components/bulkConcepts/container/BulkConceptsPage.jsx
src/components/bulkConcepts/styles/index.css
src/redux/actions/concepts/addBulkConcepts/index.js
src/redux/actions/types.js
src/redux/reducers/bulkConceptReducer.js
src/redux/reducers/util.js
src/tests/__mocks__/concepts.js
src/tests/bulkConcepts/actions/bulkConcept.test.js
src/tests/bulkConcepts/containers/BulkConceptsPage.test.js
src/tests/bulkConcepts/reducer/index.test.js

[Populate the filter sidebar with concept classes and datatype](https://issues.openmrs.org/browse/OCLOMRS-144)
As a user, I want to see pre-populated side navigation bar to filter concepts either by classes or by datatype.

OCLOMRS-144: Populate the filter sidebar with concept classes and datatypes

---

src/components/dictionaryConcepts/components/CreateConceptForm.jsx
src/components/dictionaryConcepts/containers/CreateConcept.jsx

[ OCLOMRS-131 : Change the functionality for the cancel button on the form and remove the back to dictionaries link](https://issues.openmrs.org/browse/OCLOMRS-131)
- “Back to the dictionary,” link functionality can be achieved by clicking the Cancel or the back button.
It is not relevant at the moment, therefore should be removed.

 OCLOMRS-131 : Change the functionality for the cancel button on the form and remove the back to dictionaries link

---

src/components/dictionaryConcepts/components/CreateConceptForm.jsx
src/components/dictionaryConcepts/containers/CreateConcept.jsx
src/tests/dictionaryConcepts/container/CreateConcept.test.jsx

[OCLOMRS-127: Make the default datatype None on the create concept forme](https://issues.openmrs.org/browse/OCLOMRS-127)
Currently, the default datatype is "N/A". 
When selected the form prompts the user to enter a datatype. 
Since, "None" already exists on the list of datatypes and does the same thing as "N/A", we should Indicate "None" as the default datatype

OCLOMRS-127: Make the default datatype None on the create concept form

---

src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx
src/components/dashboard/components/dictionary/common/DictionaryModal.jsx

[OCLOMRS-148: Fix to select one of the supported locales when a dictionary is created in English or Spanish](https://issues.openmrs.org/browse/OCLOMRS-148)
Currently, when the user creates a dictionary with English or Spanish as the default language,both languages are saved as the supported locales which should not be the case.

OCLOMRS-148: Fix to select one of the supported locales when a dictionary is created in English or Spanish

---

src/components/dashboard/components/dictionary/DictionaryContainer.jsx
src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx
src/redux/actions/dictionaries/dictionaryActionCreators.js
src/redux/actions/dictionaries/dictionaryActions.js
src/redux/api.js
src/tests/Dashboard/action/dictionaryAction.test.js
src/tests/Dictionary/DictionaryContainer.test.jsx

[The Concepts HEAD version card should display live data](https://issues.openmrs.org/browse/OCLOMRS-188)
Currently, the Concepts (HEAD version) fieldset in the Dictionary overview page is displaying dummy data. 
Therefore the Dictionary overview page should display live data on the fieldset mentioned above.

OCLOMRS-188 : The Concepts HEAD version card should display live data

---

src/components/dashboard/components/dictionary/DictionaryContainer.jsx

[Concepts HEAD version card in an Implementation Dictionary owned by an Organisation should display live data](https://issues.openmrs.org/browse/OCLOMRS-204)
Currently, an implementation dictionary owned/managed by an organisation is not displaying the correct details in regards to the number of concepts.
Therefore it should be able to display the correct live data.

OCLOMRS-204: Concepts HEAD version card in an Implementation Dictionary owned by an Organisation should display live data

---

.gitignore
src/App.css
src/components/dashboard/components/dictionary/DictionaryContainer.jsx
src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx
src/components/dashboard/components/dictionary/DictionaryVersionsTable.jsx
src/components/dashboard/components/dictionary/styles/dictionary-modal.css
src/redux/actions/dictionaries/dictionaryActionCreators.js
src/redux/actions/dictionaries/dictionaryActions.js
src/redux/actions/types.js
src/redux/api.js
src/redux/reducers/dictionaryReducers.js
src/tests/Dashboard/action/dictionaryAction.test.js
src/tests/Dashboard/reducer/dictionaryReducers.test.js
src/tests/Dictionary/DictionaryContainer.test.jsx
src/tests/__mocks__/versions.js

[OCLOMRS-191: A user should be able to Release Dictionary HEAD as a new version
](https://issues.openmrs.org/browse/OCLOMRS-191)
Currently, a user is not able to release the HEAD (first) version of a dictionary. This issue should ensure that the owner of a dictionary can release its HEAD version.

OCLOMRS-191: A user should be able to Release Dictionary HEAD as new version

---

src/redux/actions/concepts/dictionaryConcepts.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js

[Fix UUID bug that pops up while creating a custom concept](https://issues.openmrs.org/browse/OCLOMRS-205)
Fix the bug that displays an error message,"Concept could not be created, uuid must be unique", when a user wants to create a a custom concept.

OCLOMRS-205: Fix UUID bug that pops up while creating a custom concept

---

src/components/dashboard/components/dictionary/EditDictionary.jsx
src/components/dashboard/components/dictionary/common/DictionaryModal.jsx
src/tests/Dictionary/DictionaryModal.test.jsx

[A user should be able to select “Other Languages” when creating a new dictionary](https://issues.openmrs.org/browse/OCLOMRS-153)
Currently, user can only select preferred language for default locale. User should be able "other languages" for supported locales.

OCLOMRS-153: A user should be able to select “Other Languages” when creating a new dictionary

---

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx
src/redux/actions/sources/index.js
src/setupTests.js
src/tests/Dictionary/DictionaryContainer.test.jsx
src/tests/Dictionary/DictionaryModal.test.jsx
src/tests/Login/actions/login.test.js

[User should be able to select other Preferred sources while creating a Dictionary](https://issues.openmrs.org/browse/OCLOMRS-166)
Currently a user can only select CIEL as the only preferred source. PIH(Partners In Health)  is also another source. When a user wants to create a dictionary, the user should be able to select other public sources on the platform besides CIEL.

OCLOMRS-166: User should be able to select other Preferred sources while creating a Dictionary

---

src/components/dashboard/components/dictionary/DictionaryCard.jsx
src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx
src/tests/Dictionary/DictionaryContainer.test.jsx

[Fix the dashboard UI and remove the extra fields in the Dictionary overview](https://issues.openmrs.org/browse/OCLOMRS-223)
Currently, there is a duplicate of 'Concepts (HEAD version)' fieldset on the Dictionary Overview Page, the 'Copy concepts from another dictionary' Action is irrelevant on the same page and should be removed.
The top padding of the concepts in the Dashboard UI is not right and should be fixed.

OCLOMRS-223: Fix the dashboard UI and remove the extra fields in the Dictionary overview

---

src/components/dictionaryConcepts/components/ConceptNameRows.jsx

[While creating a concept the preferred type should be changed](https://issues.openmrs.org/browse/OCLOMRS-203)
Currently, while creating a concept the preferred type can only be a Fully specified name. However, the preferred type can either be a Fully specified name, a synonym or a search term. This issue adds the other two options.

OCLOMRS-203: While creating a concept the preferred type should be changed

---

src/components/dashboard/components/dictionary/DictionaryContainer.jsx
src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx
src/components/dashboard/components/dictionary/DictionaryVersionsTable.jsx
src/components/dashboard/components/dictionary/common/SubscriptionModal.jsx
src/tests/Dictionary/DictionaryContainer.test.jsx

[OCLOMRS-168: Subscribe to a released implementation dictionary](https://issues.openmrs.org/browse/OCLOMRS-168)
Subscribe to a released implementation dictionary from a fresh OpenMRS installation of Platform + Legacy UI.
Currently, a user cannot subscribe to a released implementation of a dictionary.

OCLOMRS-168: Subscribe to a released implementation dictionary

---

src/components/dictionaryConcepts/components/ActionButtons.jsx
src/components/dictionaryConcepts/components/ConceptTable.jsx
src/components/dictionaryConcepts/components/RemoveConcept.jsx
src/components/dictionaryConcepts/components/SearchBar.jsx
src/components/dictionaryConcepts/components/TableItem.jsx
src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx
src/components/dictionaryConcepts/style/index.css
src/redux/actions/dictionaries/dictionaryActionCreators.js
src/redux/actions/dictionaries/dictionaryActions.js
src/redux/actions/types.js
src/redux/api.js
src/redux/reducers/ConceptReducers.js
src/tests/Dashboard/action/dictionaryAction.test.js
src/tests/__mocks__/concepts.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js
src/tests/dictionaryConcepts/components/ActionButtons.test.jsx
src/tests/dictionaryConcepts/container/DictionaryConcepts.test.jsx
src/tests/dictionaryConcepts/reducer/dictionaryConcept.test.js

[User should be able to remove existing concepts from a dictionary](https://issues.openmrs.org/browse/OCLOMRS-156)
Currently, the Remove Concepts link in the Dictionary concepts overview page is not working and has no functionality.
Therefore the Remove Concepts link should remove a concept from the dictionary when clicked.

OCLOMRS-156: User should be able to remove existing concepts from a dictionary

---

src/components/dashboard/components/dictionary/DictionaryContainer.jsx
src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx
src/components/dashboard/components/dictionary/common/ReleaseVersionModal.jsx
src/redux/actions/dictionaries/dictionaryActionCreators.js
src/redux/actions/dictionaries/dictionaryActions.js
src/redux/actions/types.js
src/redux/api.js
src/redux/reducers/dictionaryReducers.js
src/tests/Dashboard/action/dictionaryAction.test.js
src/tests/Dashboard/reducer/dictionaryReducers.test.js
src/tests/Dictionary/DictionaryContainer.test.jsx
src/tests/__mocks__/versions.js

[User should be able to release a new Dictionary version](https://issues.openmrs.org/browse/OCLOMRS-200)
Currently, a user can only release the HEAD version of a dictionary. However, a user is required to create and release other versions of a dictionary. This issue enables a user to release other versions of a dictionary.

OCLOMRS-200: User should be able to release a new Dictionary version

---

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx

[Short code input field should be disabled when editing dictionary.](https://issues.openmrs.org/browse/OCLOMRS-243)
User should not be able to edit the short code field when editing a dictionary.

OCLOMRS-243: Short code input field should be disabled when editing dictionary.

---

src/components/userDasboard/components/DashboardDetails.jsx
src/styles/user_dashboard.scss

[Rework the homepage UI](https://issues.openmrs.org/browse/OCLOMRS-231)
After the welcome message, organisations by a user should be listed in one line. The sentence and link to all dictionaries should be removed since we have it on the Navigation bar. Some margin should be added below the user dictionaries container.

OCLOMRS-231 : Rework the homepage UI

---

src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx
src/components/dashboard/components/dictionary/DictionaryVersionsTable.jsx

[The Released version fieldset should be below the Actions fieldset](https://issues.openmrs.org/browse/OCLOMRS-229)
The released version should be below the action fieldset and also be wrapped in a fieldset. This is to utilize the space below the action fieldset.

OCLOMRS-229 : The Released version fieldset should be below the Actions fieldset

---

src/components/userDasboard/container/UserDashboard.jsx
src/styles/user_dashboard.scss
src/styles/utils.scss

[Dictionary cards should be the same across the application](https://issues.openmrs.org/browse/OCLOMRS-249)
The dictionary cards don't look the same for both homepage and dictionaries page, this has to be fixed. Regarding dictionary cards, divider line on home page that is in dictionaries section has to be aligned with the dictionary cards.

Dictionary cards should be the same across the application

---

src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx

[Copy concepts from another dictionary action should be removed from the dictionary overview](https://issues.openmrs.org/browse/OCLOMRS-259)
Copy concepts from another dictionary action should be removed from dictionary overview page since it's being implemented when creating a new dictionary. [HERE](https://github.com/openmrs/openmrs-ocl-client/pull/146)

OCLOMRS-259 : Copy concepts from another dictionary action should be removed from the dictionary overview

---

src/components/Navbar.js

[Change navbar links from using anchor tags to using links.](https://issues.openmrs.org/browse/OCLOMRS-254)
Currently, the links on the navbar are using anchor tags this causes the page to reload when you click on a link. This, however, shouldn't be the case. When a link is clicked it should take you to a different page without reloading.

OCLOMRS-254: Change navbar links from using anchor tags to using links.

---

src/components/bulkConcepts/component/PreviewCard.jsx
src/components/dictionaryConcepts/components/CreateConceptForm.jsx

[OCLOMRS-228: Change the UI on the pages to start with create then cancel](https://issues.openmrs.org/browse/OCLOMRS-228)
The cancel button came before the create button. This is not a good practice. Therefore, this ticket was to ensure the create or add button comes before cancel or close button

OCLOMRS-228:Change the UI on the pages to start with create then cancel

---

README.md

[Fix a spelling error in the README.md file.](https://issues.openmrs.org/browse/OCLOMRS-274)
I fixed a spelling error in the README.md file, the word `existence` was spelled as `exsitance` and the statement `Your should now see your app running` should be `You should now see your app running`. So I corrected them.

OCLOMRS-274: Fix a spelling error in the README.md file.

---

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx

[Use a standard tooltip for shortcode in new dictionary form](https://issues.openmrs.org/browse/OCLOMRS-269)
Tooltip for short code while creating a new dictionary doesn’t work like tooltips usually do. Any of the following are pretty standard, so one of these standard approaches has to be used:
- Write it out as plain text next to the label
- Write it as the placeholder text when the field is empty
- Have a visible icon that you can hover over, and this displays a tooltip
- Help text is displayed as a tooltip when the field is focused
(right now it does a tooltip when you hover over the field, but there’s no icon, and it doesn’t pop up if the field gets focus via a keyboard tab). Also this tooltip should say that it cannot be changed after creating the dictionary

Use a standard tooltip for short code in new dictionary form

---

src/redux/actions/auth/authActions.js
src/tests/Login/actions/login.test.js

[Show a visual cue that a user is logging in as soon as they submit the login form](https://issues.openmrs.org/browse/OCLOMRS-273)
At the moment, a loader is only shown after the server has responded and the login is successful. In the event that the network is a bit slow, a user might wonder if indeed they are logging in as there are no visual cues until the server responds.

OCLOMRS-273: Show a visual cue that a user is logging in as soon as they submit the login form

---

src/components/Navbar.js
src/styles/app.scss

[Refactor the navbar items bold styling to avoid repetition of strong tags](https://issues.openmrs.org/browse/OCLOMRS-264)
IInitially, strong tags were used to make the navbar items to become bold. This led to the repetition of the code hence the styling will now be in sass thus increasing reusability and decreasing repetition of code.

OCLOMRS-264: Refactor the navbar items bold styling to avoid repetition of strong tags

---

src/components/dashboard/components/dictionary/common/SubscriptionModal.jsx

[OCLOMRS-277: Fix subscription URL](https://issues.openmrs.org/browse/OCLOMRS-277)
Subscription URLs have double backslash and don’t work. After this fix there should be only on backslash and the url to be functional.

OCLOMRS-277: Fix subscription URL

---

src/components/Navbar.js

[Change Logout from a link to a button](https://issues.openmrs.org/browse/OCLOMRS-261)
On the navigation bar, log out on the dropdown is a link. This is not correct and as it doesn't lead to another page. This should, therefore, be changed to a button.

OCLOMRS-261: Change Logout from a link to a button

---

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx

[Change dictionary visibility options to Private and Public](https://issues.openmrs.org/browse/OCLOMRS-280)
In create new dictionary form, visibility options should be Private or public instead of View and None
The options in the UI should say “Public” and “Private”
In the back end API these map to View and None, but the end-user of our app shouldn’t ever see this
Also, there should not be a blank option for this. It’s a required field. (User would have it default to Public)

OCLOMRS-280: Change dictionary visibility options to Private and Public

---

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx
src/styles/dictionary_modal.scss
src/tests/Dictionary/DictionaryModal.test.jsx

[OCLOMRS-278: Fix error messages on create dictionary form](https://issues.openmrs.org/browse/OCLOMRS-278)
All the required inputs should be highlighted for example by asterisk *

OCLOMRS-278: Fix error messages on create dictionary form

---

src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx
src/tests/Dictionary/DictionaryContainer.test.jsx

[Change the versions table heading to say “Version(s)” instead of “Released Version”](https://issues.openmrs.org/browse/OCLOMRS-265)
On a dictionary details page, the versions table heading should be “Version(s)” instead of “Released Version”.

OCLOMRS-265: Change the versions table heading to say “Version(s)” instead of “Released Version”

---

src/styles/bulk_concepts.scss

[Fix input search box](https://issues.openmrs.org/browse/OCLOMRS-266)
In the Safari browser, in the input search box, the entry text is being hidden. This should be fixed to work across all browsers.

OCLOMRS-266: Fix input search box

---

src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx

[Change the table header to say “Release Date” instead of just date](https://issues.openmrs.org/browse/OCLOMRS-267)
Change the table header to say “Release Date” instead of just date, and make the actions look more distinct from each other. E.g. browse should have an icon like it does in the Actions section in the top right

OCLOMRS 267: Change the table header to say “Release Date” instead of just date

---

src/components/dashboard/components/dictionary/DictionaryVersionsTable.jsx

[OCLOMRS-287: Make the released versions table actions links look more distinct from each other](https://issues.openmrs.org/browse/OCLOMRS-287)
There are three links in released versions table, but they appear as one link. After this the link should be distinctive.

OCLOMRS-287: Make the released versions table actions links look more distinct from each other

---

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx

[Fix bad UX issues while escaping the create new dictionary form modal](https://issues.openmrs.org/browse/OCLOMRS-271)
Bad UX: Create a new dictionary, and add another language. The multi-select widget remains open, so I press Esc (thinking this will close the multi-select) but this closes the entire modal popup and discards my info. Even clicking outside of the modal in the gray area closes it and discards the form. This is bad UX for a form in a modal. Instead, the modal should only be dismissable via the Cancel button at the bottom of the form.
In fact, the form is not entirely cleared when closing the form (either via Cancel or clicking outside the modal): the Visibility and Dictionary Name fields stay filled, but the Other Languages multi-select is cleared. If the form is canceled, …

OCLOMRS-271: Fix bad UX issues while escaping the create new dictionary form modal

---

src/components/dictionaryConcepts/components/ActionButtons.jsx
src/components/dictionaryConcepts/components/ConceptTable.jsx
src/components/dictionaryConcepts/components/RemoveConcept.jsx
src/components/dictionaryConcepts/components/TableItem.jsx
src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx
src/tests/dictionaryConcepts/container/DictionaryConcepts.test.jsx

[Fix the delete dictionary concept modal not showing](https://issues.openmrs.org/browse/OCLOMRS-296)
Currently, when a user clicks the "remove" button in the concepts table, only a backdrop shows. The backdrop also doesn't disappear unless the user the refreshes the application.

OCLOMRS-296: Fix the delete dictionary concept modal not showing

---

src/components/dictionaryConcepts/components/AnswersRow.jsx
src/components/dictionaryConcepts/components/AnswersTable.jsx
src/components/dictionaryConcepts/components/ConceptNameRows.jsx
src/components/dictionaryConcepts/components/CreateConceptForm.jsx
src/components/dictionaryConcepts/components/DescriptionRow.jsx
src/components/dictionaryConcepts/containers/CreateConcept.jsx
src/components/dictionaryConcepts/containers/EditConcept.jsx
src/redux/actions/concepts/dictionaryConcepts.js
src/redux/actions/types.js
src/redux/reducers/ConceptReducers.js
src/styles/dictionary_concepts.scss
src/tests/Dashboard/reducer/conceptReducer.test.js
src/tests/__mocks__/answers.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js
src/tests/dictionaryConcepts/components/AnswersRow.test.jsx
src/tests/dictionaryConcepts/components/AnswersTable.test.jsx
src/tests/dictionaryConcepts/components/CreateConceptForm.test.jsx
src/tests/dictionaryConcepts/container/CreateConcept.test.jsx
src/tests/dictionaryConcepts/container/EditConcept.test.jsx
src/tests/dictionaryConcepts/reducer/dictionaryConcept.test.js

[Changes to create concept form options for Q-and-A concept](https://issues.openmrs.org/browse/OCLOMRS-173)
When a user selects to create Q-and-A concept they should be able to specify the answers

OCLOMRS-173: Changes to create concept form options for Q-and-A concept

---

package.json

[Clean up application dependencies](https://issues.openmrs.org/browse/OCLOMRS-294)
Currently, in the application dependencies file(`package.json`), app development dependencies are mixed with app dependencies and there are some unused dependencies listed there. This should be worked on and do and clean up.

OCLOMRS-294: Clean up application dependencies

---

src/components/dashboard/components/dictionary/DictionaryContainer.jsx
src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx

[ Fix the edit dictionary modal](https://issues.openmrs.org/browse/OCLOMRS-302)
For now, if a user clicks on edit dictionary button, the modal doesn't show up. This has to be fixed to work as expected and the modal form should have current dictionary details.

OCLOMRS-302: Fix the edit dictionary modal

---

src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx
src/components/dashboard/components/dictionary/DictionaryVersionsTable.jsx
src/components/dashboard/components/dictionary/common/ReleaseVersionModal.jsx
src/tests/Dictionary/DictionaryContainer.test.jsx

[Release version button should be one](https://issues.openmrs.org/browse/OCLOMRS-299)
On dictionary details page, there are two buttons to release version. Release version and release HEAD version, We should have one button instead and initially, it should say release Latest version instead of release HEAD version.

OCLOMRS-299: Release version button should be one

---

src/styles/app.scss

[Make the Hamburger button on the mobile view more visible](https://issues.openmrs.org/browse/OCLOMRS-285)
The Hamberger button that appears on smaller screen sizes has no contrast with the navbar background color (both of them are black). This makes it hard for a user to easily realize its presence. Use of a white Hamberger button would fix this issue.

OCLOMRS-285: Make the Hamburger button on the mobile view more visible

---

src/styles/all.scss
src/styles/custom_variables.scss
src/styles/dashboard.scss

[OCLOMRS-276: Fix placeholder text color](https://issues.openmrs.org/browse/OCLOMRS-276)
Placeholder text in fields is too dark and looks like an entry value. After this fix, it should be a lighter grey.

OCLOMRS-276: Fix placeholder text color

---

src/components/bulkConcepts/addBulkConcepts.jsx
src/components/bulkConcepts/bulkConceptList.jsx
src/components/bulkConcepts/bulkConceptTable.jsx
src/components/bulkConcepts/component/Paginations.jsx
src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx
src/redux/actions/bulkConcepts/index.js
src/redux/actions/concepts/addBulkConcepts/index.js
src/tests/__mocks__/concepts.js
src/tests/bulkConcepts/actions/index.test.js
src/tests/bulkConcepts/addBulkConcepts.test.jsx
src/tests/bulkConcepts/bulkConceptList.test.jsx

[OCLOMRS-304: Add CIEL concepts in the add Bulk concept pagee](https://issues.openmrs.org/browse/OCLOMRS-304)
Currently, a user can only add all bulk CIEL concepts. This issue will enable a user to able to select the bulk concepts when adding in the add Bulk page.

OCLOMRS-304: Add CIEL concepts in the add Bulk concept page

---

src/components/dictionaryConcepts/components/ConceptNameRows.jsx
src/components/dictionaryConcepts/components/DescriptionRow.jsx

OCLOMRS-301: Enable saving of different languages for concept name
[OCLOMRS-301: Enable saving of different languages for concept name](https://issues.openmrs.org/browse/OCLOMRS-301)
- Fix concept locale being displayed on edit form.

OCLOMRS-301: Enable saving of different languages for concept name

---

src/components/dashboard/components/dictionary/ListDictionaries.jsx
src/styles/dictionary_concepts.scss

[OCLOMRS-306: Resize all dictionaries display and remove text area top padding](https://issues.openmrs.org/browse/OCLOMRS-306)
1. Take a look at the home page dictionary display, change the dictionaries from the center display to one that follows each other.
2. Make the dictionaries in the all dictionaries navbar tab to appear the same way as the ones on the home page.
3. When creating a concept, remove the top padding on the description textarea

OCLOMRS-306: Resize all dictionaries display and remove text area top padding

---

src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx
src/components/dashboard/components/dictionary/DictionaryVersionsTable.jsx

[Make the subscription modal background to be lighter](https://issues.openmrs.org/browse/OCLOMRS-315)
The modal background on the subscription modal is too dark because multiple modals get stacked on top of each other depending on the number of `subscription URL` links. This gives the modal background an effect that makes it appear to be dark. Only a single modal should be displayed.

OCLOMRS-315: Make the subscription modal background to be lighter

---

src/styles/app.scss

[OCLOMRS-305: Resize the logout button on the navbar](https://issues.openmrs.org/browse/OCLOMRS-305)
Previously, the logout button stretches out of the navbar and it isn't appealing.
This was fixed in this PR.

OCLOMRS-305: Resize the logout button on the navbar

---

src/redux/actions/dictionaries/dictionaryActionCreators.js
src/tests/Dashboard/action/dictionaryAction.test.js

[Create a custom error message when fetching dictionaries when offline](https://issues.openmrs.org/browse/OCLOMRS-318)
Previously, when accessing all dictionaries or a single dictionary without internet in production mode, the loader could display infinitely. A typeError used to be displayed in development mode.
This is fixed by this PR.

OCLOMRS-318: Create a custom error message when fetching dictionaries when offline

---

src/components/dictionaryConcepts/components/ConceptTable.jsx

[Remove ID and DataType column from concepts table](https://issues.openmrs.org/browse/OCLOMRS-319)
Remove the ID and DataType column in order to pave way for mapping buttons on the actions column

OCLOMRS-319:Remove ID and DataType column from concepts table

---

src/components/Navbar.js
src/components/dictionaryConcepts/components/ConceptDropdown.jsx
src/styles/dictionary_concepts.scss
src/tests/Navbar.test.js

[Make reactstrap drop-downs work.](https://issues.openmrs.org/browse/OCLOMRS-320)
Since the team decided to migrate to react strap, there was a removal of unnecessary links to the bootstrap CDNs in the index.html. Different dropdowns depended on the bootstrap files from these CDNs and after they were removed, the dropdowns don't work anymore.

OCLOMRS-320: Make reactstrap drop-downs work.

---

src/redux/actions/auth/authActions.js
src/tests/Login/actions/login.test.js

[Mock login endpoint properly in the tests](https://issues.openmrs.org/browse/OCLOMRS-325)
For now, in login tests, the login API endpoint is not mocked properly. This causes making a call to the API when running the tests. The tests fail sometimes if there is something wrong with the backend.

OCLOMRS-325: Mock login endpoint properly in the tests

---

package.json

[Remove untestable files](https://issues.openmrs.org/browse/OCLOMRS-326)
Untestable files in the application lower the coverage hence removing them will increase the coverage

OCLOMRS-326: Remove untestable files

---

src/styles/login.scss

[Prevent the Footer and the Login form from overlapping](https://issues.openmrs.org/browse/OCLOMRS-330)
Previously, as seen on the login page, the login form overlaps with the footer content. This should not be the case. This is fixed by this PR.

OCLOMRS-330: Prevent the Footer and the Login form from overlapping 

---

src/components/dictionaryConcepts/components/ActionButtons.jsx
src/styles/app.scss

[make the edit concept action link to look like other action buttons for consistency](https://issues.openmrs.org/browse/OCLOMRS-312)
The edit concept action link in the view dictionary concepts table is placed under action buttons and should look similar to the action buttons for consistency.

OCLOMRS-312: make the edit concept action link to be a button

---

src/components/dictionaryConcepts/components/ExternalMapping.jsx

[Fix placeholder spelling error on the Add mappings modal](https://issues.openmrs.org/browse/OCLOMRS-329)
Correcting the *Term field* placeholder on the add mappings modal from "Malariae" to "Malaria" for consistency as the platform is written in English.

OCLOMRS-329: Fix placeholder spelling error on add mappings modal

---

src/styles/app.scss

[OCLOMRS-335: Put the "Take me back home" button lower on the Not Found page](https://issues.openmrs.org/browse/OCLOMRS-335)
Fix the `Take me back` home button CSS margin to move a bit lower.

OCLOMRS-335: Fix 'Take me back home' button alignment

---

src/components/NotFound.js
src/tests/Auth/notFound.test.js

[Make the link in NotFound.js file to use "Link" instead of "a" tag](https://issues.openmrs.org/browse/OCLOMRS-334)
The Link back to the home page in the NotFound.js file should take advantage of the react-router `Link` rather than HTML's `<a>`

OCLOMRS-334: Make the link in NotFound.js file to use "Link" instead of "a" tag

---

src/redux/actions/concepts/dictionaryConcepts.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js

[Display all concepts in the concepts table](https://issues.openmrs.org/browse/OCLOMRS-336)
The concepts table shows custom concepts alone. This PR will fix that, such that all concepts both custom and from existing sources are shown.

OCLOMRS-336: Display all concepts in the concepts table

---

src/components/bulkConcepts/bulkConceptList.jsx
src/components/bulkConcepts/component/ConceptTable.jsx
src/components/dictionaryConcepts/components/ConceptTable.jsx
src/components/dictionaryConcepts/components/ViewMappingsModal.jsx
src/styles/dictionary_concepts.scss

[Fix the "No concept/No mapping" info display position on all the react tables](https://issues.openmrs.org/browse/OCLOMRS-339)
Previously, the "No concepts/No mappings" info was overlapping other table rows and columns. This is fixed by this PR.

OCLOMRS-339: Fix the "No concept/No mapping" info display position on all the react tables

---

src/components/dictionaryConcepts/components/ActionButtons.jsx
src/components/dictionaryConcepts/components/ConceptTable.jsx
src/components/dictionaryConcepts/components/RemoveMappings.jsx
src/components/dictionaryConcepts/components/RemoveMappingsModal.jsx
src/components/dictionaryConcepts/components/ViewConceptMappings.jsx
src/components/dictionaryConcepts/components/ViewMappingsModal.jsx
src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx
src/redux/actions/dictionaries/dictionaryActionCreators.js
src/redux/actions/dictionaries/dictionaryActions.js
src/redux/actions/types.js
src/redux/api.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js
src/tests/dictionaryConcepts/components/ActionButtons.test.jsx
src/tests/dictionaryConcepts/components/RemoveMappings.test.jsx
src/tests/dictionaryConcepts/components/RemoveMappingsModal.test.jsx
src/tests/dictionaryConcepts/components/ViewMappingsModal.test.js
src/tests/dictionaryConcepts/container/DictionaryConcepts.test.jsx

[Implement Delete/Retire mapping functionality](https://issues.openmrs.org/browse/OCLOMRS-311)
This PR adds the Delete/Retire mappings feature to Concept mappings although the backend raises a CORS error when the action is performed.

OCLOMRS-311: Implement delete/retire mapping functionality

---

src/styles/bulk_concepts.scss

[Fix preview CIEL concept card overflow](https://issues.openmrs.org/browse/OCLOMRS-341)
The description fo the preview overflowed from the container.
Fixed it by wrapping the text to prevent overflow.

OCLOMRS-341: Fix preview CIEL concept card overflow

---

src/components/bulkConcepts/bulkConceptList.jsx
src/components/bulkConcepts/component/ConceptTable.jsx
src/components/dictionaryConcepts/components/ConceptTable.jsx
src/components/dictionaryConcepts/components/ViewMappingsModal.jsx
src/styles/dictionary_concepts.scss

[OCLOMRS-353: Fix excessive padding in ReactTable on concepts page](https://issues.openmrs.org/browse/OCLOMRS-353)
Previously, on the live website on the dictionary concepts page, when concepts are few (2) there was a lot of padding between concepts in ReactTable. This is fixed by this PR.

OCLOMRS-353: Fix excessive padding in ReactTable on concepts page

---

src/redux/actions/auth/authActions.js
src/redux/actions/concepts/dictionaryConcepts.js
src/redux/actions/dictionaries/dictionaryActionCreators.js
src/tests/Dashboard/action/api.test.js
src/tests/Dashboard/action/dictionaryAction.test.js
src/tests/Login/actions/login.test.js

[Add custom error messages when fetching the API while offline](https://issues.openmrs.org/browse/OCLOMRS-331)
Currently, there are no error messages when trying to access the API when offline hence providing a descriptive information makes the user aware that they are offline at that time.

OCLOMRS-331: Add custom error messages when fetching the API while offline

---

src/styles/dictionary_concepts.scss

[Make the "NEXT" or "BACK" button darker on the pagination](https://issues.openmrs.org/browse/OCLOMRS-362)
During pagination of concepts, when there are more items to scroll to, the "NEXT" button isn't significantly different from the when there are no "next" items to scroll to. The same applies to the "BACK" button.
This is fixed on this PR by adding custom styling to the buttons.

OCLOMRS-362: Make the "NEXT" or "BACK" button darker on the pagination

---

src/components/bulkConcepts/addBulkConcepts.jsx
src/components/bulkConcepts/bulkConceptList.jsx
src/styles/bulk_concepts.scss
src/tests/Dashboard/container/DictionaryDisplay.test.jsx
src/tests/bulkConcepts/addBulkConcepts.test.jsx
src/tests/bulkConcepts/containers/BulkConceptsPage.test.js

[OCLOMRS-354: Implement adding bulk concepts using IDs populated in the text area on bulk add concepts page](https://issues.openmrs.org/browse/OCLOMRS-354)
- Removed react table displaying concepts with a text are which will populate concepts IDs to be added to dictionary concepts.

OCLOMRS-354:  Replaced table with textarea on bulk add concepts page

---

src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx
src/redux/reducers/ConceptReducers.js
src/tests/dictionaryConcepts/reducer/dictionaryConcept.test.js

[Make the modal disappear after deleting a concept and show concepts without the deleted concept.](https://issues.openmrs.org/browse/OCLOMRS-365)
Previously, after deleting a concept, the modal did not disappear automatically and after closing it, the table still showed the deleted concept untill the the page was refreshed. That behaviour is fixed in this PR.

OCLOMRS-365: Make the modal disappear after deleting a concept and show concepts without the deleted concept.

---

src/components/dictionaryConcepts/components/SideNavItem.jsx
src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx
src/tests/__mocks__/concepts.js
src/tests/dictionaryConcepts/container/DictionaryConcepts.test.jsx

[Make the Source column and on sidebar show CIEL instead of UUID](https://issues.openmrs.org/browse/OCLOMRS-351)
Source column is wrong. A source should be something like “CIEL”, but what is being displayed in that column looks like a UID. (Also it’s wrong in the sidebar.)

OCLOMRS-351: Make the Source column and on sidebar show Custom instead of UUID

---

src/components/dictionaryConcepts/components/RemoveMappings.jsx
src/tests/dictionaryConcepts/components/ViewMappingsModal.test.js

[Clean props validation warnings in console when running tests](https://issues.openmrs.org/browse/OCLOMRS-366)
Currently, due to props validation, the RemoveMappings component throws warnings of missing URL prop when tests are run. This ticket fixes the code to take out the warnings.

OCLOMRS-366: Clean props validation warnings in console when running tests

---

src/components/bulkConcepts/component/ConceptTable.jsx
src/components/bulkConcepts/component/SearchBar.jsx
src/components/bulkConcepts/container/BulkConceptsPage.jsx
src/redux/reducers/bulkConceptReducer.js
src/tests/bulkConcepts/containers/BulkConceptsPage.test.js
src/tests/bulkConcepts/reducer/index.test.js

[Load CIEL concepts on search only](https://issues.openmrs.org/browse/OCLOMRS-337)
Initially importing CIEL concepts to a dictionary loads for too long even with only 1217 concepts. Make it easier to load only when a search is entered.

OCLOMRS-337: Load CIEL concepts on search only

---

src/components/dictionaryConcepts/containers/CreateConcept.jsx
src/redux/actions/concepts/dictionaryConcepts.js

… new concept
[OCLOMRS-361: Disable create button through the process of creating a new concept](https://issues.openmrs.org/browse/OCLOMRS-361)
- Reduced the setTime out as the store was being updated in a shorter time than the set timeout.

OCLOMRS-361: Disable create button when creating a concept

---

src/components/dictionaryConcepts/components/RemoveMappings.jsx
src/components/dictionaryConcepts/components/ViewConceptMappings.jsx
src/tests/dictionaryConcepts/components/ViewConceptMappings.test.js

[Hide retired mappings from the list of all dictionary mappings](https://issues.openmrs.org/browse/OCLOMRS-369)
Currently, after a mapping belonging to a particular dictionary is retired, it's still visible to the user among the list of mappings.

OCLOMRS-369: Hide retired mappings from the list of all dictionary mappings

---

src/components/dictionaryConcepts/components/ActionButtons.jsx

[Remove the add mappings button from the view dictionary concepts table](https://issues.openmrs.org/browse/OCLOMRS-377)
The add mappings button existent in the dictionary concepts table should be removed as its implementation is in the wrong interface.

OCLOMRS-377: Remove the add mappings button from the view dictionary concepts table

---

src/components/bulkConcepts/component/ConceptTable.jsx
src/components/bulkConcepts/container/BulkConceptsPage.jsx
src/components/dictionaryConcepts/components/ConceptTable.jsx
src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx
src/tests/bulkConcepts/containers/BulkConceptsPage.test.js
src/tests/dictionaryConcepts/container/DictionaryConcepts.test.jsx

[Remove filter text inputs at the top of tables on add CIEL concepts and dictionary concepts interfaces](https://issues.openmrs.org/browse/OCLOMRS-374)
There exist two ways of filtering CIEL concepts on the add CIEL concepts interface and the interface that shows concepts in a dictionary (The text inputs and the checkboxes on the left of the interface). The text inputs should be removed so as to enable a user only filter using the checkboxes.

OCLOMRS-374: Remove filter text inputs at the top of tables on add CIEL concepts and dictionary concepts interfaces

---

src/components/bulkConcepts/component/SearchBar.jsx
src/components/bulkConcepts/container/BulkConceptsPage.jsx
src/tests/bulkConcepts/containers/BulkConceptsPage.test.js

[OCLOMRS-372: Remove the show all button on the add CEIL concepts interface.](https://issues.openmrs.org/browse/OCLOMRS-372)
- Removed "**show all concepts**" button and implement `fetchConcepts` request on `componentDidMount`.

OCLOMRS-372: Remove the show all button on add CEIL concepts page.

---

src/components/userDasboard/components/CardWrapper.jsx
src/components/userDasboard/container/UserDashboard.jsx
src/redux/actions/types.js
src/redux/actions/user/index.js
src/redux/reducers/user/index.js
src/tests/userDashboard/actions/index.test.js
src/tests/userDashboard/container/UserDashboard.test.jsx
src/tests/userDashboard/reducers/index.test.js

[Remove the `No dictionaries found` message when there exists a network error](https://issues.openmrs.org/browse/OCLOMRS-379)
Whenever there is no internet, and dictionaries are failed to be fetched, a message is returned saying there are no dictionaries, this should be fixed as it can mislead a user that has dictionaries into thinking there are no dictionaries.

OCLOMRS-379: Remove the `No dictionaries found` message when there exists a network error

---

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx
src/tests/Dictionary/DictionaryModal.test.jsx

[Re-enable the buttons on the create dictionary modal once error occurs](https://issues.openmrs.org/browse/OCLOMRS-378)
The create dictionary modal's buttons do not get re-enabled once there occurs an error in the form.

OCLOMRS-378: Re-enable the buttons on the create dictionary modal once an error occurs

---

src/components/dictionaryConcepts/components/CreateConceptForm.jsx

[Fix linting errors that were not caught by Travis earlier](https://issues.openmrs.org/browse/OCLOMRS-385)
There are a couple of linting (prop validation errors) errors that were uncaught by Travis. This should be fixed so as to avoid any errors that may arise in production caused by them (the errors).

OCLOMRS-385: Fix linting errors that where not caught by Travis earlier

---

src/redux/actions/dictionaries/dictionaryActionCreators.js
src/tests/Dashboard/action/dictionaryAction.test.js

[show network error message when one tries to search for dictionaries with no internet](https://issues.openmrs.org/browse/OCLOMRS-381)
Whenever one tries to search for dictionaries when there is a network issue, a loader is shown and no error message is shown in the all dictionaries interface.

OCLOMRS-381: show network error message when one tries to search for dictionaries with no internet

---

src/components/bulkConcepts/component/SearchBar.jsx
src/components/dashboard/components/dictionary/DictionariesSearch.jsx
src/styles/dictionary_concepts.scss

[Add a search button to a search field on the add CIEL concepts and All Dictionaries interfaces.](https://issues.openmrs.org/browse/OCLOMRS-382)
Currently, to get concepts and to search for dictionaries, you type a keyword on the search field and press Enter. This is not apparent to all users. Adding a search button will make this clear to all the users.

OCLOMRS-382: Add a search button to a search field on the add CIEL concepts and All Dictionaries interfaces.

---

src/components/bulkConcepts/component/ActionButtons.jsx
src/components/bulkConcepts/component/PreviewCard.jsx
src/tests/bulkConcepts/components/PreviewCard.test.js

[Show only one preview modal at a time](https://issues.openmrs.org/browse/OCLOMRS-371)
On the Add CIEL concepts page, when a user first clicks on the preview button for the first CIEL concept and then closes it followed by clicking on preview concept buttons of the next CIEL concepts (2....n), several preview modals belonging to the same CIEL concepts are opened.

OCLOMRS-371: Show only one preview modal at a time

---

src/styles/app.scss

[Make the mappings search field wider](https://issues.openmrs.org/browse/OCLOMRS-386)
The mappings search field is too small and cannot accommodate the mappings. The search field should be wider

OCLOMRS-386 : Make the mappings search field wider

---

src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx
src/components/dashboard/components/dictionary/common/DictionaryModal.jsx
src/components/dictionaryConcepts/components/CreateConceptForm.jsx
src/components/dictionaryConcepts/components/ViewMappingsModal.jsx
src/styles/dictionary_concepts.scss
src/styles/dictionary_modal.scss
src/styles/login.scss

[Make all buttons consistent](https://issues.openmrs.org/browse/OCLOMRS-391)
The `add dictionary` and `cancel` buttons on the create new dictionary modal are of different colours and design as compared to the rest of the buttons in the application, they have to be similar to the other buttons for consistency.
The following buttons should all be consistent:
- Dictionary details page: "Edit" and "Go to Concepts" buttons
- Edit dictionary page: "Update" and "Cancel" buttons
- List of Concepts page: "Next" and "Previous" buttons
- Edit Concept page: "Update" and "Cancel" buttons
- View mapping page: "Cancel" button

OCLOMRS-391: Make all buttons consistent

---

src/components/bulkConcepts/component/CardBody.jsx
src/components/bulkConcepts/component/MappingPreview.jsx
src/components/bulkConcepts/component/PreviewCard.jsx
src/styles/bulk_concepts.scss
src/tests/bulkConcepts/components/PreviewCard.test.js

[Add more content about the concept in the preview modal](https://issues.openmrs.org/browse/OCLOMRS-360)
On this ticket, it’s generally important that the “Preview Concept” screen shows more information. Right now it actually shows less than is shown in the table, because it doesn’t show the Class and Datatype).

OCLOMRS-360: Add more content about the concept in the preview modal

---

src/components/dictionaryConcepts/components/CreateMapping.jsx
src/components/dictionaryConcepts/components/MapType.jsx
src/tests/dictionaryConcepts/components/MapType.test.js

[Make the CIEL select dropdown a text input field](https://issues.openmrs.org/browse/OCLOMRS-387)
The map-type input field should have no default values and should be open to the user to type in any map-type when it is an internal mapping (one with the source as CIEL). Therefore, it should be a text input field and not a select dropdown.

OCLOMRS-387: Make the CIEL select dropdown a text input field

---

src/components/bulkConcepts/component/ConceptPagination.jsx
src/components/bulkConcepts/component/ConceptTable.jsx
src/components/bulkConcepts/component/Pagination.jsx
src/components/bulkConcepts/container/BulkConceptsPage.jsx
src/redux/actions/concepts/addBulkConcepts/index.js
src/redux/actions/types.js
src/redux/reducers/bulkConceptReducer.js
src/tests/Dashboard/reducer/conceptReducer.test.js
src/tests/bulkConcepts/actions/bulkConcept.test.js
src/tests/bulkConcepts/components/ConceptPagination.test.js
src/tests/bulkConcepts/components/Pagination.test.js
src/tests/bulkConcepts/containers/BulkConceptsPage.test.js
src/tests/bulkConcepts/reducer/index.test.js

[Add pagination to the add CIEL concepts.](https://issues.openmrs.org/browse/OCLOMRS-373)
Enable a user to be able to view the first ten concepts in the add CIEL concepts interface when the component first loads. A user should then be able to click next to view the next ten. At this point, you should fetch the next ten in the table.

OCLOMRS-373: Add pagination to the add CIEL concepts.

---

src/components/bulkConcepts/addBulkConcepts.jsx
src/components/bulkConcepts/component/CardBody.jsx
src/components/bulkConcepts/component/PreviewCard.jsx
src/components/bulkConcepts/component/addBulkConceptResultModal.jsx
src/components/dictionaryConcepts/components/CreateConceptForm.jsx
src/tests/bulkConcepts/addBulkConcepts.test.jsx
src/tests/bulkConcepts/components/PreviewCard.test.js
src/tests/dictionaryConcepts/container/CreateConcept.test.jsx
src/tests/userDashboard/container/UserDashboard.test.jsx

[Fix warnings on the browser and terminal console logs](https://issues.openmrs.org/browse/OCLOMRS-384)
There are errors on the terminal console log when running tests and also a few that appear in the browsers console logs. These can cause issues during production if not caught early.

OCLOMRS-384: Fix warnings on browser and terminal console logs

---

src/components/dashboard/components/dictionary/DictionaryContainer.jsx
src/tests/Dictionary/DictionaryContainer.test.jsx
src/tests/__mocks__/concepts.js

[Fix bug with dictionary download](https://issues.openmrs.org/browse/OCLOMRS-398)
Previously,  the dictionary download button was throwing an error on console and doing nothing. This PR fixes that behavior.

OCLOMRS-398: Fix bug with dictionary download

---

src/components/dashboard/components/dictionary/DictionaryVersionsTable.jsx

[Browse released dictionary version shows 404](https://issues.openmrs.org/browse/OCLOMRS-401)
When you click browse on a released dictionary, it directs to 404 page

OCLOMRS-401: Browse released dictionary version shows 404

---

src/components/bulkConcepts/container/BulkConceptsPage.jsx
src/tests/bulkConcepts/containers/BulkConceptsPage.test.js

[Refresh dictionary concepts page when search field is cleared](https://issues.openmrs.org/browse/OCLOMRS-411)
When a user clears the search field the dictionary concepts should refresh. 
Steps to reproduce
1) Open the ﻿﻿Add CIEL concepts page.
2) input the concept on the search bar and click the arrow button to search.
3) When the search results are showing on the table clear the search bar.
4) You will notice that the search result is still showing on the table.

OCLOMRS-411: Refresh dictionary concepts page when search field is cleared

---

src/components/userDasboard/container/UserDashboard.jsx
src/redux/actions/dictionaries/dictionaryActionCreators.js
src/redux/actions/user/index.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js
src/tests/userDashboard/actions/index.test.js
src/tests/userDashboard/container/UserDashboard.test.jsx

[fix wrong error message with invalid authentication token](https://issues.openmrs.org/browse/OCLOMRS-403)
The first time the application url (for a developer; localhost:<port>/home. Currently deployed; https://openmrs.qa.openconceptlab.org/home) is visited on a browser, it shows network error message on the login page.
When an invalid token is supplied during authentication by the browser, it keeps showing network error on refresh until you click logout to get to the login page and login.
The application should show login page without network error message when a user visits the application url the first time.
Invalid token should redirect to login page.

OCLOMRS-403: fix wrong error message with invalid authentication token

---

src/components/dictionaryConcepts/components/SideNavItem.jsx
src/components/dictionaryConcepts/components/Sidenav.jsx
src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx

[Make checkbox on concepts page checked after concept edit](https://issues.openmrs.org/browse/OCLOMRS-399)
Edit concept after filter does not indicate the filtered class when returning to the page from the edit concept page

OCLOMRS-399: Make checkbox on concepts page checked after concept edit

---

src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx

[Add display for active concepts on the dictionary detail card](https://issues.openmrs.org/browse/OCLOMRS-409)
In order to tell the user what type of concepts they are looking at, there's a need to also add a display that explicitly tells the user the active concepts count on the dictionary detail card. This ticket is based on feedback from this [thread.](https://talk.openmrs.org/t/developing-the-ocl-for-openmrs-application/17771/537)

OCLOMRS-409: Add display for active concepts on the dictionary detail card

---

src/components/dictionaryConcepts/components/ConceptTable.jsx
src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx

[change the default number of rows to 20 on dictionary concepts page](https://issues.openmrs.org/browse/OCLOMRS-418)
Currently, the default number of rows is 5 when viewing concepts belonging to a dictionary. This is too small.

OCLMRS-418: change the default number of rows to 20 on dictionary concepts page

---

src/components/bulkConcepts/container/BulkConceptsPage.jsx
src/tests/bulkConcepts/containers/BulkConceptsPage.test.js

[Fix search error with search on Add CIEL Concepts page](https://issues.openmrs.org/browse/OCLOMRS-419)
Fix the error message that displays while searching
Steps to reproduce
1) Go to  add CIEL concepts page and search for a concept (example blood) with many occurrences
2) Click on the pagination arrow to get to the next page.
3) Search for another concept that has a very little occurrence
4) You will notice the page throws an error

 OCLOMRS-419: Fix search error with search on Add CIEL Concepts page.

---

src/components/dashboard/components/dictionary/DictionaryCard.jsx

[Display change 'concepts' to 'active_concepts' on the home page dictionary card](https://issues.openmrs.org/browse/OCLOMRS-408)
Currently, the concepts count displayed in dictionary card on the home page is the number of 'active_concepts' on that dictionary. Simply displaying 'concepts' doesn't give the user an idea what type of concepts they are looking at because some are active and some might be retired. This ticket is based on feedback from this [thread.](https://talk.openmrs.org/t/developing-the-ocl-for-openmrs-application/17771/537)

OCLOMRS-408: Display change 'concepts' to 'active_concepts' on the home page dictionary card

---

src/components/bulkConcepts/component/ActionButtons.jsx
src/tests/bulkConcepts/components/ActionButtons.test.js

[fix buffering of add concept on Add CIEL Concepts page](https://issues.openmrs.org/browse/OCLOMRS-420)
When adding an existing CIEL concept:
- When one clicks the `add concept` button
*The button is disabled but the concept is not added
- Then when one clicks on another concept to add it.
*The previous concept is added but the current concept is not added.
- Also when you click the button to add another concept
*Again the previous concept is added but the current concept is not added.

OCLOMRS-420: fix buffering of add concept on Add CIEL Concepts page

---

src/components/bulkConcepts/container/BulkConceptsPage.jsx
src/redux/actions/concepts/addBulkConcepts/index.js

[Make Datatypes and Classes sidebar filters work as expected](https://issues.openmrs.org/browse/OCLOMRS-412)
On Add CIEL concepts page when one tries to filter the results with Datatypes and Classes sidebar filters, nothing happens and an error is displayed.

OCLOMRS-412: Make Datatypes and Classes sidebar filters work as expected

---

src/components/bulkConcepts/container/BulkConceptsPage.jsx

[Fix the error that displays while searching on add CIEL Concepts page](https://issues.openmrs.org/browse/OCLOMRS-429)
Fix the error message that displays while searching
Steps to reproduce
1) Go to  add CIEL concepts page and search for a concept (example blood) with many occurrences
2) Click on the pagination arrow to get to the next page.
3) Search for another concept that has a very little occurrence
4) You will notice the page throws an error

OCLOMRS-429: Fix the error that displays while searching on add CIEL Concepts page

---

package.json
src/components/bulkConcepts/container/BulkConceptsPage.jsx
src/components/dashboard/container/DictionariesDisplay.jsx
src/components/dashboard/container/OwnerDictionary.jsx
src/redux/reducers/generalSearchReducer.js
src/tests/Dashboard/action/dictionaryAction.test.js
src/tests/Dashboard/container/DictionaryDisplay.test.jsx
src/tests/Dashboard/container/OwnerDisplay.test.jsx
src/tests/GeneralSearch/Reducers/generalSearchReducer.test.jsx
src/tests/__mocks__/dictionaries.js
src/tests/bulkConcepts/components/ActionButtons.test.js
src/tests/bulkConcepts/containers/BulkConceptsPage.test.js

[Enable Partial word searching on dictionary concepts page](https://issues.openmrs.org/browse/OCLOMRS-410)
Enable users to search for concepts by entering one or more letters as opposed to complete words only.

OCLOMRS-410: Enable Partial word searching on dictionary concepts page

---

src/components/bulkConcepts/component/PreviewCard.jsx
src/tests/bulkConcepts/components/PreviewCard.test.js

[Modify concept preview modal to show synonyms of concept name](https://issues.openmrs.org/browse/OCLOMRS-413)
A synonym is any valid, alternative name for the concept. This includes acronyms, abbreviations, and other names that reference the primary name. The preview concept card should show the concept's synonym as well.

OCLOMRS-413: Modify concept preview modal to show synonyms of concept name

---

src/components/dictionaryConcepts/components/CreateMapping.jsx
src/components/dictionaryConcepts/containers/CreateConcept.jsx
src/components/dictionaryConcepts/containers/EditConcept.jsx
src/tests/dictionaryConcepts/container/EditConcept.test.jsx

[remove autogenerated value from Code field when adding mappings](https://issues.openmrs.org/browse/OCLOMRS-426)
Remove auto-generated code for to concept code when adding an external mapping
- A user should be able to add an already existing to concept code.

OCLOMRS-426: remove autogenerated value from Code field when adding mappings

---

src/components/dictionaryConcepts/components/CreateConceptForm.jsx

[Change clickable texts on concept pages to buttons](https://issues.openmrs.org/browse/OCLOMRS-431)
Edit concept and Create concept pages have only texts "Add another name", "Add another description", and "Add another Mapping" to click for such actions. This should be changed to buttons

OCLOMRS-431: Change clickable texts on concept pages to buttons

---

src/components/dictionaryConcepts/components/Sidenav.jsx
src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx

[Make checkboxes appear as checked when they are checked under sources on the sidebar found on dictionary concepts page](https://issues.openmrs.org/browse/OCLOMRS-430)
Currenly, when you filter dictionary concepts by sources for example CIEL, CIEL concepts will be returned but the checkbox will remain unchecked.

OCLOMRS-430: Make checkboxes appear as checked when they are checked under sources on the sidebar found on dictionary concepts page

---

src/components/dictionaryConcepts/components/CreateMapping.jsx
src/tests/bulkConcepts/components/ActionButtons.test.js

[make source name case insensitive on mappings](https://issues.openmrs.org/browse/OCLOMRS-404)
When a user enters a source, the text field:
- Should be case insensitive, that is, allows both upper and lower case

OCLOMRS-404: make source name case insensitive on mappings

---

src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx

[Fix inaccurate total concept counts on dictionary detail card page](https://issues.openmrs.org/browse/OCLOMRS-397)
On the dictionary overview page, the dictionary overview card shows total concepts count that doesn't match the sum between custom concepts and CIEL concepts. With some dictionaries this sum is fine and the total concepts count is representative, however, some like [this one](https://openmrs.qa.openconceptlab.org/dictionaryOverview/users/admin/collections/ME101/) show this discrepancy.
The issue is that active_concepts field that is sent with the dictionary from the backend is used to represent total concepts on the frontend. This is not right.

OCLOMRS-397: Fix inaccurate total concept counts on some dictionary detail card page

---

src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx

[Fix the build error](https://issues.openmrs.org/browse/OCLOMRS-438)
Current active_concepts is not defined, which makes the build to fail. The url to the failing build is 
[https://ci.openmrs.org/browse/OCL-OC-304](https://ci.openmrs.org/browse/OCL-OC-304)

OCLOMRS-438: Fix the build error

---

package.json
src/components/dictionaryConcepts/components/CreateConceptForm.jsx
src/components/dictionaryConcepts/components/CreateMapping.jsx
src/components/dictionaryConcepts/containers/CreateConcept.jsx
src/components/dictionaryConcepts/containers/EditConcept.jsx
src/tests/__mocks__/concepts.js
src/tests/dictionaryConcepts/components/CreateConceptForm.test.jsx
src/tests/dictionaryConcepts/components/CreateMapping.test.js
src/tests/dictionaryConcepts/container/CreateConcept.test.jsx
src/tests/dictionaryConcepts/container/EditConcept.test.jsx

[Make source field autocomplete, with list of existing sources when adding mapping to concept](https://issues.openmrs.org/browse/OCLOMRS-424)
As the user types a source for any given mapping, the source field should automatically display all matching sources (from the existing list of sources).

OCLOMRS-424: Make source field autocomplete, with list of existing sources when adding mapping to concept

---

src/redux/actions/concepts/dictionaryConcepts.js

[Enable Partial word searching on create concept while mapping](https://issues.openmrs.org/browse/OCLOMRS-443)
when the user only enters part of a concept name. The user should be able to get concepts that match the query.  The screenshot of the page is attached below.

OCLOMRS-443: Enable Partial word searching on create concept while mapping

---

package.json
src/components/bulkConcepts/component/CardBody.jsx
src/components/bulkConcepts/component/PreviewCard.jsx
src/components/dictionaryConcepts/components/helperFunction.js
src/styles/bulk_concepts.scss
src/tests/bulkConcepts/components/PreviewCard.test.js

[Modify preview of convenient-set concept types to have set members, answers and other items as shown in the mock-ups](https://issues.openmrs.org/browse/OCLOMRS-415)
Any concept with set members should show the set members.   The same as true for any concept with coded answers.  These should show up when previewing a concept. Add items shown in the mocks-ups.

OCLOMRS-415: Modify preview of convenient-set concept types to have set members, answers and other items as shown in the mock-ups

---

src/components/dictionaryConcepts/components/ConceptTable.jsx
src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx
src/redux/actions/concepts/dictionaryConcepts.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js
src/tests/dictionaryConcepts/container/DictionaryConcepts.test.jsx

[Add search function on dictionary concepts page](https://issues.openmrs.org/browse/OCLOMRS-432)
Currently, there's no way to search for a concept by name on the dictionary concepts page. This ticket adds a search input on the dictionary concepts page.

OCLOMRS-432: Add search function on dictionary concepts page

---

src/components/dictionaryConcepts/components/helperFunction.js
src/redux/reducers/bulkConceptReducer.js
src/redux/reducers/util.js
src/tests/bulkConcepts/reducer/index.test.js

[Enable the selection of more than one class or data type on add CIEL concepts page.](https://issues.openmrs.org/browse/OCLOMRS-427)
Currently, on the add CIEL concepts page, a user is not able to select multiple classes or data types from the sidebar. After selecting a class or a data type, others disappear as shown in the attached video.

OCLOMRS-427: Enable the selection of more than one class or data type on add CIEL concepts page.

---

src/components/bulkConcepts/component/PreviewCard.jsx

[Attach locale to the Synonyms displayed while previewing concept](https://issues.openmrs.org/browse/OCLOMRS-447)
The primary Synonyms should be removed and other should have their locale attached to them.

OCLOMRS-447: Attach locale to the Synonyms displayed while previewing concept

---

src/components/dictionaryConcepts/components/ConceptNameRows.jsx
src/components/dictionaryConcepts/components/CreateMapping.jsx
src/components/dictionaryConcepts/components/DescriptionRow.jsx

[Change remove labels on create concept and edit concept page to buttons](https://issues.openmrs.org/browse/OCLOMRS-455)
The buttons on the create concept and edit concept page are displaying as labels;
- Make them display as buttons that prompt a user to click them

OCLOMRS-455: Change remove labels on create concept and edit concept page to buttons

---

src/components/dictionaryConcepts/components/ConceptNameRows.jsx
src/components/dictionaryConcepts/components/CreateConceptTable.jsx
src/components/dictionaryConcepts/components/DescriptionRow.jsx
src/components/dictionaryConcepts/components/DescriptionTable.jsx
src/tests/dictionaryConcepts/components/DescriptionRow.test.js

[The remove button on the name and description column of creating new concept does not work](https://issues.openmrs.org/browse/OCLOMRS-451)
On the create new concept page:
- The button for remove name does not function as expected. 
- Also the remove description button, not function as expected.

OCLOMRS-451: The remove button on the name and description column of creating new concept does not work

---

src/components/dictionaryConcepts/components/ActionButtons.jsx
src/components/dictionaryConcepts/components/ConceptTable.jsx
src/redux/actions/concepts/dictionaryConcepts.js
src/tests/dictionaryConcepts/container/DictionaryConcepts.test.jsx

[Show distinction between active and retired concepts](https://issues.openmrs.org/browse/OCLOMRS-449)
Show retired concepts as strikethrough text

OCLOMRS-449: Show distinction between active and retired concepts

---

src/components/bulkConcepts/container/BulkConceptsPage.jsx
src/tests/bulkConcepts/containers/BulkConceptsPage.test.js

[Fix the "Search query must contain at least 3 characters" message returned below search field when datatype/class filters are selected and pagination next button clicked](https://issues.openmrs.org/browse/OCLOMRS-450)
On the "Add CIEL concepts page", when a datatype and class filter is selected, a "Search query must contain at least 3 characters" message is returned below the search concept field when the pagination next button is clicked. The message should not appear when the pagination next button is clicked. The message should be removed.

OCLOMRS-450: Remove the message returned below search field when datatype/class filters are selected and pagination next button clicked

---

src/components/bulkConcepts/component/ConceptTable.jsx

[Remove source column on Add CIEL Page ](https://issues.openmrs.org/browse/OCLOMRS-460)
The source column on the " Add CIEL concepts Page" should be removed given the fact that all concepts listed are "CIEL concepts". There is no need for the source column.

OCLOMRS-460: Remove source column on Add CIEL Page

---

src/components/bulkConcepts/component/ActionButtons.jsx
src/components/bulkConcepts/component/ConceptTable.jsx
src/components/bulkConcepts/container/BulkConceptsPage.jsx
src/tests/bulkConcepts/components/ActionButtons.test.js

[Fix the issue with the preview concept button](https://issues.openmrs.org/browse/OCLOMRS-448)
Currently, a user needs to double click the preview concept button on the add CIEL page before it works. This should be fixed so that the preview concept button should work on a single click

OCLOMRS-448: Fix the issue with the preview concept button.

---

src/components/dictionaryConcepts/components/CreateConceptForm.jsx
src/components/dictionaryConcepts/components/CreateMapping.jsx
src/components/dictionaryConcepts/containers/CreateConcept.jsx
src/components/dictionaryConcepts/containers/EditConcept.jsx
src/tests/dictionaryConcepts/container/CreateConcept.test.jsx
src/tests/dictionaryConcepts/container/EditConcept.test.jsx

[Implement remove mapping on the right interface](https://issues.openmrs.org/browse/OCLOMRS-396)
"Remove mapping" is currently implemented in the view mappings interface. It needs to be implemented in the edit concept interface similar to implementation on create concept interface.

OCLOMRS-396: Implement remove mapping on the right interface

---

src/components/dictionaryConcepts/components/ConceptNameRows.jsx
src/components/dictionaryConcepts/components/CreateConceptTable.jsx
src/components/dictionaryConcepts/components/DescriptionRow.jsx
src/components/dictionaryConcepts/components/DescriptionTable.jsx

[Fix inability to create more than one Name or Description while Creating and Editing Concepts](https://issues.openmrs.org/browse/OCLOMRS-453)
This bug prevents the creation of more than one name and more than one description while creating or editing a custom concept. The concept itself is saved successfully, but the new name or new description is not saved.
This happens because:
- The identifiers for each new name-row and description-row were not passed correctly.
- The default locale (a required field) wasn't being passed correctly.

OCLOMRS-453: Fix inability to create more than one Name or Description while Creating and Editing Concepts

---

src/components/Signup/components/container/index.jsx
src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx
src/components/dashboard/components/dictionary/DictionaryVersionsTable.jsx
src/components/dashboard/components/dictionary/common/SubscriptionModal.jsx
src/components/login/container/LoginDetails.jsx
src/components/login/container/index.jsx
src/components/userDasboard/components/DashboardDetails.jsx
src/tests/Dictionary/DictionaryModal.test.jsx

[Use the traditional OCL url constant defined in HelperFunction.js to replace the traditional url scattered in the codebase.](https://issues.openmrs.org/browse/OCLOMRS-456)
The URL(https://qa.openconceptlab.org) to the traditional OCL site is scattered in the code base as seen in the attached screenshot. A constant defined in HelperFunction.js should be used instead.

OCLOMRS-456: Use the traditional OCL url constant defined in HelperFunction.js to replace the traditional url scattered in the codebase.

---

README.md
src/components/dictionaryConcepts/components/helperFunction.js
src/config/axiosConfig.js
src/config/index.js
src/redux/actions/auth/authActions.js

[Implement reading an OCL backend URL from a system environment property called OCL_API_HOST](https://issues.openmrs.org/browse/OCLOMRS-458)
-  Rename the BASE_URL to OCL_API_HOST
-  Enable creating a `.env` file to save these URLs as environment variables so that it can be easily switched when the need arrives.
-  Update the read me to show users how to store the environment variables in the .env file.

OCLOMRS-458: Implement reading an OCL backend URL from a system environment property called OCL_API_HOST

---

src/components/dictionaryConcepts/components/CreateMapping.jsx

[The source of the Mapping does not display while editing a Concept](https://issues.openmrs.org/browse/OCLOMRS-461)
When a concept is created with its mappings and then the user clicks to edit the concept, the mappings display without their sources.

OCLOMRS-461: The source of the Mapping does not display while editing a Concept

---

src/components/dictionaryConcepts/components/CreateMapping.jsx
src/components/dictionaryConcepts/components/MapType.jsx
src/tests/__mocks__/concepts.js
src/tests/dictionaryConcepts/container/CreateConcept.test.jsx

[Fix inability to save the correct relationship for each Mapping](https://issues.openmrs.org/browse/OCLOMRS-464)
While creating or editing concepts, any relationship that is not the default "SAME-AS" relationship is not saved. The concept and the mappings are saved but with wrong relationships.

OCLOMRS-464: Fix inability to save the correct relationship for each Mapping

---

.gitignore
Dockerfile
README.md
init.sh
package.json
public/index.html
src/components/dictionaryConcepts/components/ConceptNameRows.jsx
src/config/index.js
src/tests/dictionaryConcepts/components/ConceptNameRows.test.jsx

[Passing OCL URL environment variables to run at runtime](https://issues.openmrs.org/browse/OCLOMRS-463)
- Create a bash script that creates an env-config.js file with key-value pairs of the environment variables.
- Load env-config.js  with the script tag in index.html
- Update the start script in package.json to run the bash script when running the app during development.
- Update the Dockerfile to copy the .env file, the bash script and also run the bash script before the build(at runtime). Then remove env-config.js from the public folder if any and add the newly created one by the bash script. 
**Testing.**
**In development**
- Create a .env file in the root directory and pass it;
`OCL_API_HOST=https://api.qa.openconceptlab.org/`
`TRADITIONAL_OCL_HOST=https://qa.openconceptlab.org`
- …

OCLOMRS-463: Passing OCL URL environment variables to run at runtime

---

src/components/bulkConcepts/component/PreviewCard.jsx

[Preview a CIEL concept - Add space between the last word and id inside parenthesis](https://issues.openmrs.org/browse/OCLOMRS-468)
On the preview CIEL concept modal (popup), add a space between the last word in the title and the ID.

OCLOMRS-468: Preview a CIEL concept - Add space between the last word and id inside parenthesis

---

src/components/dictionaryConcepts/components/DescriptionRow.jsx
src/styles/dictionary_concepts.scss
src/styles/login.scss

[Show ellipses for long names and descriptions in Create and Edit Concept views](https://issues.openmrs.org/browse/OCLOMRS-466)
On the Create and Edit Concept screens, show an ellipsis (three dots) for all names and descriptions that are too long. (Those whose text is being truncated)

OCLOMRS-466: Show ellipses for long names and descriptions in Create and Edit Concept views

---

src/components/dictionaryConcepts/containers/EditConcept.jsx
src/redux/actions/concepts/dictionaryConcepts.js

[When a concept mapping from a specific source is removed  a user should be able to add it back ](https://issues.openmrs.org/browse/OCLOMRS-462)
When editing a concept, a user should be able to remove a concept mapping and re-add it. When one removes an already existing mapping then selects the same concept mapping and clicks update, the concept mapping is not added.

OCLOMRS-462: When a concept mapping from a specific source is removed  a user should be able to re-add it

---

src/components/dictionaryConcepts/components/MapType.jsx
src/components/dictionaryConcepts/components/helperFunction.js
src/tests/Signup/index.test.jsx

[Make “Narrower-Than” the default relationship for external mappings, and “SAME-AS” the default for CIEL (when adding a mapping)](https://issues.openmrs.org/browse/OCLOMRS-470)
Make “Narrower-Than” the default relationship for external mappings (all mappings except CIEL) when adding or editing a concept mapping.

OCLOMRS-470: Make “Narrower-Than” the default relationship for external mappings, and “SAME-AS” the default for CIEL (when adding a mapping)

---

src/components/dictionaryConcepts/containers/EditConcept.jsx

[Fix error when a concept doesn't have mapping](https://issues.openmrs.org/browse/OCLOMRS-465)
Create a custom concept without adding mapping. When you select that concept by clicking on the edit button on dictionary concept page it throws an error.

OCLOMRS-465: Fix error when a concept doesn't have mapping

---

src/components/dashboard/components/dictionary/DictionaryContainer.jsx
src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx
src/tests/Dictionary/DictionaryContainer.test.jsx

[Fix Retired count in the table of Concepts as well as the Dictionary Overview page](https://issues.openmrs.org/browse/OCLOMRS-467)
- Ensure that the number of retired concepts shown in on the Dictionary overview page.
- Matches the number of retired concepts shown in the table and ensure they add up.

OCLOMRS-467: Fix Retired count in the table of Concepts as well as the Dictionary Overview page

---

src/components/dictionaryConcepts/components/CreateConceptForm.jsx

[Display mappings on the Q-AND-A pages both on the Create and Edit page](https://issues.openmrs.org/browse/OCLOMRS-484)
Currently, on the page where we either create or edit Q-AND-A concepts, there are no mappings shown. In this ticket, on the page where we create Q-AND-A concepts, fields for adding mappings should be displayed at the bottom of the page. Likewise, on the page where we edit a Q-AND-A concept, mappings should be displayed at the bottom of the page.

OCLOMRS-484: Display mappings on the Q-AND-A pages both on the Create and Edit page

---

src/components/dictionaryConcepts/components/ActionButtons.jsx
src/components/dictionaryConcepts/components/helperFunction.js

[Get rid of the “Remove” button for custom concepts](https://issues.openmrs.org/browse/OCLOMRS-486)
Before this, when viewing a dictionary, the "Remove" button was being shown on all the concepts. This PR eliminates this button on custom concepts.

OCLOMRS-486: Get rid of the “Remove” button for custom concepts

---

src/redux/actions/concepts/dictionaryConcepts.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js

[Raise Test Coverage](https://issues.openmrs.org/browse/OCLOMRS-489)
Fix the drop in test coverage in the "dictionaryConcepts.js" file. This was discovered in this [PR](https://github.com/openmrs/openmrs-ocl-client/pull/378) and was due to an untested Action called *unretireMapping*

OCLOMRS-489: Raise Test Coverage

---

src/components/dictionaryConcepts/components/AnswerRow.jsx

[Mulago (Dictionary) - show the words in parenthesis and CIEL (Source) - show the words in parenthesis](https://issues.openmrs.org/browse/OCLOMRS-485)
- On the Create a question concept page, Under Answers section, the concept and the dictionary are not clearly differentiated.

OCLOMRS-485: Mulago (Dictionary) - show the words in parenthesis and CIEL (Source) - show the words in parenthesis	

---

src/components/dictionaryConcepts/components/helperFunction.js
src/components/dictionaryConcepts/containers/EditConcept.jsx
src/tests/dictionaryConcepts/container/EditConcept.test.jsx

[While editing a mapping when the source changes clear all the other fields in the row.](https://issues.openmrs.org/browse/OCLOMRS-475)
When editing a mapping, clear all editable fields when the mappings' source is changed.

OCLOMRS-475: While editing a mapping when the source changes clear all the other fields in the row

---

src/components/bulkConcepts/addBulkConcepts.jsx
src/components/dictionaryConcepts/components/CreateConceptForm.jsx
src/components/dictionaryConcepts/components/CreateMapping.jsx
src/components/dictionaryConcepts/components/helperFunction.js
src/redux/actions/concepts/dictionaryConcepts.js
src/styles/dictionary_concepts.scss
src/tests/bulkConcepts/addBulkConcepts.test.jsx
src/tests/dictionaryConcepts/components/CreateMapping.test.js

[When adding a CIEL mapping or Bulk Concepts, execute a search only when ENTER is pressed](https://issues.openmrs.org/browse/OCLOMRS-478)
When adding a CIEL mapping, execute a search only when ENTER is pressed in order to be consistent with other searches, and to avoid multiple calls to the backend at every keystroke. Repeat the same behaviour for the Add Bulk Concepts search fields.

OCLOMRS-478: When adding a CIEL mapping or Bulk Concepts, execute a search only when ENTER is pressed

---

src/redux/reducers/store.js

[Refreshing the Edit Page causes two versions of the same Concept to be created](https://issues.openmrs.org/browse/OCLOMRS-494)
After Editing a Concept, its reference to the Dictionary is supposed to be deleted and then recreated. However, this reference cannot be deleted when the page is refreshed because the version_url is lost. This is solved by preserving the State.

OCLOMRS-494: Refreshing the Edit Page causes two versions of the same Concept to be created

---

src/components/bulkConcepts/container/BulkConceptsPage.jsx
src/components/dashboard/container/DictionariesDisplay.jsx
src/tests/Dashboard/container/DictionaryDisplay.test.jsx

[Fix the occurrence of the message returned below the search fields on the "All dictionaries" and "Add CIEL concepts " pages](https://issues.openmrs.org/browse/OCLOMRS-495)
On the "All dictionaries" and "Add CIEL concepts " pages, when a user searches for anything less than three characters and the search button clicked multiple times, the 'Search query must contain at least 3 characters' message uncharacteristically appears multiple times.

OCLOMRS-495: Fix the occurrence of the message returned below the search fields on the All dictionaries and Add CIEL concepts pages

---

src/components/bulkConcepts/addBulkConcepts.jsx
src/tests/bulkConcepts/addBulkConcepts.test.jsx

[Remove the “Other” Option from Bulk Add Concepts page](https://issues.openmrs.org/browse/OCLOMRS-498)
Remove the Other radio button on the Bulk Add Concepts page it will be re-implemented in post MVP.

OCLOMRS-498: Remove the “Other” Option from Bulk Add Concepts page

---

src/components/dictionaryConcepts/containers/CreateConcept.jsx
src/tests/dictionaryConcepts/container/CreateConcept.test.jsx

[Refreshing the Create Concept page should not render new rows for Names and Descriptions](https://issues.openmrs.org/browse/OCLOMRS-501)
When the Create Concept page is refreshed, new rows for Names and Descriptions are created.

OCLOMRS-501: Refreshing the Create Concept page should not render new rows for Names and Descriptions

---

src/components/dictionaryConcepts/components/AnswerRow.jsx
src/tests/dictionaryConcepts/container/EditConcept.test.jsx

[Raise Test Coverage](https://issues.openmrs.org/browse/OCLOMRS-500)
Fix the drop in test coverage in the "EditConcepts.jsx" file. This was discovered in this [PR](https://github.com/openmrs/openmrs-ocl-client/pull/389) and was due to an if else statement found in the removeAnswerRow function not being fully tested

OCLOMRS-500: Raise Test Coverage

---

src/components/dashboard/components/dictionary/common/GeneralModal.jsx
src/components/dictionaryConcepts/components/CreateConceptForm.jsx
src/components/dictionaryConcepts/components/helperFunction.js
src/components/dictionaryConcepts/containers/CreateConcept.jsx
src/components/dictionaryConcepts/containers/EditConcept.jsx
src/styles/dictionary_modal.scss
src/tests/dictionaryConcepts/container/CreateConcept.test.jsx
src/tests/dictionaryConcepts/container/EditConcept.test.jsx

[The warning should not appear if no changes were made on the Edit and Create concept pages when Cancel is clicked](https://issues.openmrs.org/browse/OCLOMRS-497)
On the Edit and Create concept pages, do not show the warning message/popup if no changes were made.

OCLOMRS-497: The warning should not appear if no changes were made on the Edit and Create concept pages when Cancel is clicked

---

src/styles/dictionary_concepts.scss

[When adding or editing a mapping make the results drop down menu scrollable when searching for CIEL concepts](https://issues.openmrs.org/browse/OCLOMRS-505)
When adding or editing a mapping, searching for CIEL concepts might return a drop down of results in hundreds or thousands. This could make the display uncharacteristically inconveniencing and bad for the users. The results drop down should be made scrollable to improve user experience.

OCLOMRS-505: When adding or editing a mapping make the results drop down menu scrollable when searching for CIEL concepts

---

src/components/dictionaryConcepts/components/CreateConceptForm.jsx
src/components/dictionaryConcepts/components/CreateMapping.jsx
src/components/dictionaryConcepts/containers/CreateConcept.jsx
src/components/dictionaryConcepts/containers/EditConcept.jsx
src/tests/__mocks__/concepts.js
src/tests/dictionaryConcepts/container/CreateConcept.test.jsx
src/tests/dictionaryConcepts/container/EditConcept.test.jsx

[The default mapping relationship for external mappings is saved as SAME-AS instead of NARROWER-THAN](https://issues.openmrs.org/browse/OCLOMRS-503)
When creating a new external mapping (i.e. a mapping with a source that is not CIEL) the default relationship is saved as SAME-AS instead of NARROWER-THAN.

OCLOMRS-503: The default mapping relationship for external mappings is saved as SAME-AS instead of NARROWER-THAN

---

package.json
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js

[Tests are failing to run on the OpenMRS yokobue agent](https://issues.openmrs.org/browse/OCLOMRS-506)
Tests are failing to run on the OpenMRS yokobue agent due to having deprecated version of react-scripts. This PR fixes the bug.

OCLOMRS-506: Tests are failing to run on the OpenMRS yokobue agent

---

src/redux/actions/concepts/specificConceptAction.js
src/tests/Dashboard/action/specificConceptAction.test.js

[OCLOMRS-514](https://issues.openmrs.org/browse/OCLOMRS-514)
- Add test to cover condition where a request fails when making an api call for concept types.

OCLOMRS-514: raise test coverage

---

src/redux/actions/concepts/addBulkConcepts/index.js
src/tests/bulkConcepts/actions/bulkConcept.test.js

[addConcept action incorrectly calls with 'already added'](https://issues.openmrs.org/browse/OCLOMRS-521)
- Notify was called on outside the `if-else` block. Should be called within the else
- Add test for this

OCLOMRS-521: addConcept action incorrectly calls with 'already added'

---

src/components/bulkConcepts/addBulkConcepts.jsx
src/tests/bulkConcepts/addBulkConcepts.test.jsx

[Remove the quick search option from the Add Bulk Concepts Page](https://issues.openmrs.org/browse/OCLOMRS-515)
Remove the quick search option from the Add Bulk Concepts Page. The search functionality is irrelevant since users can easily add multiple concept IDs in the available text area.

OCLOMRS-515: Remove the quick search option from the Add Bulk Concepts Page

---

src/redux/actions/auth/authActions.js
src/tests/Login/actions/login.test.js

[A user should be redirected to the login page after a network error occurs](https://issues.openmrs.org/browse/OCLOMRS-510)
When a network error occurs or connection is lost while a user is trying to log in, a user should be redirected to the login page.
Currently, this is not possible at the moment.

OCLOMRS-510: A user should be redirected to the login page after a network error occurs

---

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx

[When creating a dictionary the default cursor position should be set in the dictionary name field.](https://issues.openmrs.org/browse/OCLOMRS-516)
When creating a dictionary the default cursor position should be set in the dictionary name field.

OCLOMRS-516: When creating a dictionary the default cursor position should be set in the dictionary name field

---

src/components/Navbar.js
src/tests/Navbar.test.js

[When logout is clicked, the flash message is missing a space](https://issues.openmrs.org/browse/OCLOMRS-522)
When logout is clicked, the flash message is missing a space

OCLOMRS-522: When logout is clicked, the flash message is missing a space

---

package.json
src/redux/actions/concepts/addBulkConcepts/index.js

[Concepts missing mappings, answers and sets on preview](https://issues.openmrs.org/browse/OCLOMRS-513)
When a user clicks 'preview concept', one of the items they expect to view are mappings, answers and sets.
Currently, mappings, answers and sets are not displayed

OCLOMRS-513: Previewing a concept does not display a concept's mappings, answers and sets

---

src/components/dictionaryConcepts/components/ConceptTable.jsx

[The concept ID should be visible on the Dictionary Concepts page](https://issues.openmrs.org/browse/OCLOMRS-528)
The concept ID should be visible on the Dictionary Concepts page

OCLOMRS-528: The concept ID should be visible on the Dictionary Concepts page

---

src/components/dictionaryConcepts/components/Sidenav.jsx

[Change the spelling of "sources" on the Dictionary concepts page](https://issues.openmrs.org/browse/OCLOMRS-525)
Change the spelling of "sources" on the Dictionary concepts page to 'Source'

OCLOMRS-525: Change the spelling of "sources" on the Dictionary concepts page

---

src/styles/dictionary_concepts.scss

[On the Dictionary Concepts Page, the names should be fully displayed](https://issues.openmrs.org/browse/OCLOMRS-526)
On the Dictionary Concepts Page, the names should be fully displayed. Remove the ellipsis

OCLOMRS-526: On the Dictionary Concepts Page, the names should be fully displayed

---

src/components/dictionaryConcepts/containers/CreateConcept.jsx

[When creating a concept, removing a name should really remove it, not just hide it in the UI](https://issues.openmrs.org/browse/OCLOMRS-535)
Steps to reproduce the bug:
- Create a new concept(e.g Symptom/Finding)
- Name: Any name in any language(e.g “Itchy Nose” in English), preferred in language = true
- Click add another name
- Choose the language e.g French(or any other) for the other name
- Click Remove on the second name without entering anything
- Enter description
- Save Concept
Bug:
When the concepts page is refreshed, an empty row appears i.e. an extra concept is created without a name

OCLOMRS-535: When creating a concept, removing a name should really remove it, not just hide it in the UI

---

src/components/bulkConcepts/component/PreviewCard.jsx

[On concept preview for a question or set concepts, the answers or set members should have a space between the title and ID](https://issues.openmrs.org/browse/OCLOMRS-557)
On concept preview for a question or set concepts, the answers or set members should have a space between the title and ID

OCLOMRS-557: On concept preview for a question or set concepts, the answers or set members should have a space between the title and ID

---

src/components/dictionaryConcepts/components/CreateConceptForm.jsx
src/components/dictionaryConcepts/containers/CreateConcept.jsx
src/tests/dictionaryConcepts/components/CreateConceptForm.test.jsx
src/tests/dictionaryConcepts/container/CreateConcept.test.jsx

[When creating a set or symptom-finding concept, a user should be able to select from the different class options](https://issues.openmrs.org/browse/OCLOMRS-556)
When creating a set or symptom-finding concept, a user should be able to select the different class options.

OCLOMRS-556: When creating a set or symptom-finding concept, a user should be able to select from the different class options

---

src/components/dictionaryConcepts/components/AnswerRow.jsx
src/components/dictionaryConcepts/components/AnswersTable.jsx
src/components/dictionaryConcepts/components/CreateConceptForm.jsx
src/components/dictionaryConcepts/containers/EditConcept.jsx
src/components/dictionaryConcepts/containers/SelectAnswers.jsx
src/redux/actions/concepts/dictionaryConcepts.js
src/redux/actions/dictionaries/dictionaryActionCreators.js
src/redux/actions/types.js
src/redux/reducers/ConceptReducers.js
src/redux/reducers/util.js
src/tests/Dashboard/action/dictionaryAction.test.js
src/tests/Dashboard/reducer/conceptReducer.test.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js
src/tests/dictionaryConcepts/components/AnswerRow.test.js
src/tests/dictionaryConcepts/components/AnswersTable.test.jsx
src/tests/dictionaryConcepts/container/EditConcept.test.jsx
src/tests/dictionaryConcepts/container/SelectAnswers.test.js

[ Edit a concept answer in Q-A concepts without having to remove it](https://issues.openmrs.org/browse/OCLOMRS-509)
Currently, if one wishes to change an answer to a concept, they have to remove it and then add a new answer. An ideal situation would be having the ability to edit a concept directly by clicking in the concept field.

OCLOMRS-509: Edit a concept answer in Q-A concepts without having to remove it

---

src/redux/reducers/store.js
src/tests/store.test.js

[Update state persistence to introduce state versioning](https://issues.openmrs.org/browse/OCLOMRS-541)
Given that we are persisting state, we have situation where when an individual updates the structure of state, it conflicts with the currently stored state, causing a crash
This ticket introduces versioning to solve this issue.

OCLOMRS-541: Update state persistence to introduce state versioning

---

src/components/dictionaryConcepts/components/CreateConceptForm.jsx
src/components/dictionaryConcepts/components/DescriptionRow.jsx
src/components/dictionaryConcepts/components/DescriptionTable.jsx
src/components/dictionaryConcepts/containers/CreateConcept.jsx
src/components/dictionaryConcepts/containers/EditConcept.jsx
src/redux/reducers/ConceptReducers.js
src/redux/reducers/util.js
src/tests/dictionaryConcepts/components/DescriptionTable.test.jsx
src/tests/dictionaryConcepts/container/CreateConcept.test.jsx
src/tests/dictionaryConcepts/reducer/dictionaryConcept.test.js

[Create and edit a concept without a description (which should be optional)](https://issues.openmrs.org/browse/OCLOMRS-542)
Creating a concept without a description (which should be optional) fails silently. The concept is not created but doesn't notify the user.
Relatedly, creating a concept with a description then editing it to remove the description works. However, on a subsequent edit, trying to remove the empty description added by default causes the app to crash.

OCLOMRS-542: Create and edit a concept without a description (which should be optional)

---

src/components/dictionaryConcepts/containers/EditConcept.jsx
src/redux/actions/concepts/dictionaryConcepts.js
src/redux/actions/dictionaries/dictionaryActionCreators.js
src/redux/api.js
src/tests/Dashboard/action/dictionaryAction.test.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js
src/tests/dictionaryConcepts/container/EditConcept.test.jsx

JIRA TICKET NAME:
[When you edit a concept, a new version of that concept should be created and its reference refreshed in the collection](https://issues.openmrs.org/browse/OCLOMRS-553)
- I added 4 concepts from CIEL, I created 4, and I edited one of those 4. In our application, I see that I have 8 concepts (which is what I expect). But in traditional OCL I see 5 references to custom concepts, not 4.
- What I think is happening is that when I edit a concept, you create a new concept version of the old concept, and you also create a new concept, and they’re both included in the collection.
- That’s wrong when I edit it should create a new version of one concept, and refresh its reference in the collection.

OCLOMRS-553: When you edit a concept, a new version of that concept should be created and its reference refreshed in the collection

---

src/components/dictionaryConcepts/components/CreateConceptForm.jsx
src/components/dictionaryConcepts/components/helperFunction.js
src/tests/dictionaryConcepts/components/CreateConceptForm.test.jsx
src/tests/dictionaryConcepts/container/CreateConcept.test.jsx
src/tests/dictionaryConcepts/container/EditConcept.test.jsx

[Fix the issue of missing Add answers field when creating a question concept](https://issues.openmrs.org/browse/OCLOMRS-558)
Fix the issue of missing Add answers field when creating a question concept

OCLOMRS-558: Fix the issue of missing Add answers field when creating a question concept

---

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx
src/redux/actions/concepts/dictionaryConcepts.js

[Enable OpenMRS validation for all dictionaries created to prevent duplication](https://issues.openmrs.org/browse/OCLOMRS-552)
Enable OpenMRS validation on the dictionaries we create through this application. This will prevent the dictionary from having two concepts with identical preferred names, which is illegal in OpenMRS.

OCLOMRS-552: Enable OpenMRS validation for all dictionaries created to prevent duplication

---

src/redux/actions/concepts/dictionaryConcepts.js
src/tests/__mocks__/concepts.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js

[Deleting a reference to an old concept fails sometimes](https://issues.openmrs.org/browse/OCLOMRS-561)
This is an issue with the API and an [issue](https://github.com/OpenConceptLab/ocl_issues/issues/115) has been raised. Pending resolution of this issue, the suggestion is not to display concepts that are not the latest version when viewing a dictionary's concepts.

OCLOMRS-561: Deleting a reference to an old concept fails sometimes

---

src/components/dictionaryConcepts/containers/EditConcept.jsx
src/redux/reducers/ConceptReducers.js
src/tests/dictionaryConcepts/container/EditConcept.test.jsx
src/tests/dictionaryConcepts/reducer/dictionaryConcept.test.js

[Changing a datatype when creating and editing a concept is not saved](https://issues.openmrs.org/browse/OCLOMRS-559)
When one creates a concept with a datatype other than 'none', the datatype is not reflected when editing the concept. It always displays 'none'.

OCLOMRS-559: Changing a datatype when creating and editing a concept is not saved

---

src/tests/dictionaryConcepts/container/DictionaryConcepts.test.jsx

[Raise Test Coverage](https://issues.openmrs.org/browse/OCLOMRS-565)
Account for drop in coverage on PR for ticket [OCLOMRS-562](https://github.com/openmrs/openmrs-ocl-client/pull/441).

OCLOMRS-565: Raise Test Coverage

---

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx

[When Editing a dictionary the added languages don't show up after updating](https://issues.openmrs.org/browse/OCLOMRS-524)
When editing a dictionary and adding some other languages, when the dictionary is updated and Edit clicked again, the popup does not show up with the additional languages. After refreshing the page, the languages do show up.

OCLOMRS-524: When Editing a dictionary the added languages don't show up after updating

---

src/components/dictionaryConcepts/components/CreateConceptForm.jsx
src/tests/dictionaryConcepts/components/CreateConceptForm.test.jsx

[Create Another Kind of concept should have all possible options](https://issues.openmrs.org/browse/OCLOMRS-563)
The create another kind of concept should display answers, sets and mappings for the concept being created.
The create another kind of concept page displays only mappings.

OCLOMRS-563: Create Another Kind of concept should have all possible options

---

src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx
src/redux/actions/dictionaries/dictionaryActionCreators.js
src/redux/actions/dictionaries/dictionaryActions.js
src/redux/actions/types.js
src/redux/api.js
src/redux/reducers/ConceptReducers.js
src/tests/Dashboard/action/dictionaryAction.test.js
src/tests/Dashboard/reducer/conceptReducer.test.js
src/tests/__mocks__/concepts.js
src/tests/dictionaryConcepts/container/DictionaryConcepts.test.jsx

[When you retire/ unretire, a new version of that concept should be created and its reference refreshed in the collection](https://issues.openmrs.org/browse/OCLOMRS-562)
Quoting from #553
- I added 4 concepts from CIEL, I created 4, and I edited one of those 4. In our application, I see that I have 8 concepts (which is what I expect). But in traditional OCL I see 5 references to custom concepts, not 4.
- What I think is happening is that when I edit a concept, you create a new concept version of the old concept, and you also create a new concept, and they’re both included in the collection.
- That’s wrong when I edit it should create a new version of one concept, and refresh its reference in the collection.
This behavior applies for retiring/ un-retiring concepts as well

OCLOMRS-562:     When you retire/ unretire, a new version of that concept should be created and its reference refreshed in the collection

---

src/components/dictionaryConcepts/components/CreateConceptForm.jsx
src/components/dictionaryConcepts/components/helperFunction.js
src/redux/actions/concepts/dictionaryConcepts.js
src/tests/__mocks__/concepts.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js
src/tests/dictionaryConcepts/components/CreateConceptForm.test.jsx
src/tests/dictionaryConcepts/container/EditConcept.test.jsx

[Edit concept should have all possible options](https://issues.openmrs.org/browse/OCLOMRS-518)
The edit concept should display answers, sets and mappings for the concept being edited.
The edit another concept page displays only either set or answer mappings and not both.

OCLOMRS-518: Edit concept should include all mapping types(answers, sets, mappings)

---

src/components/bulkConcepts/component/PreviewCard.jsx

[Previewing a Concept WIth Both Sets and Answers Does not Show Answers](https://issues.openmrs.org/browse/OCLOMRS-536)
Previewing a concept currently assumes that only an Answer or Sets can be present at a time. This PR caters for the possibility of both Answers and sets being available and displays them both.

OCLOMRS-536: Previewing a Concept WIth Both Sets and Answers Does not Show Sets

---

src/components/dictionaryConcepts/components/AnswerRow.jsx
src/components/dictionaryConcepts/components/AnswersTable.jsx
src/components/dictionaryConcepts/components/CreateConceptForm.jsx
src/components/dictionaryConcepts/containers/EditConcept.jsx
src/components/dictionaryConcepts/containers/SelectAnswers.jsx
src/redux/actions/concepts/dictionaryConcepts.js
src/redux/actions/types.js
src/redux/reducers/ConceptReducers.js
src/tests/bulkConcepts/actions/bulkConcept.test.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js
src/tests/dictionaryConcepts/components/AnswerRow.test.js
src/tests/dictionaryConcepts/components/AnswersTable.test.jsx
src/tests/dictionaryConcepts/container/EditConcept.test.jsx
src/tests/dictionaryConcepts/container/SelectAnswers.test.js

[Edit set members without having to remove them](https://issues.openmrs.org/browse/OCLOMRS-569)
Currently, it's not possible to edit a set member without first removing it then adding a new one. This PR is to add the functionality to edit a set member directly.

OCLOMRS-569: Edit set members without having to remove them

---

src/components/dictionaryConcepts/components/CreateMapping.jsx
src/redux/actions/concepts/dictionaryConcepts.js
src/redux/api.js
src/styles/dictionary_concepts.scss
src/tests/Dashboard/action/api.test.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js
src/tests/dictionaryConcepts/components/CreateMapping.test.js
src/tests/dictionaryConcepts/container/EditConcept.test.jsx

[Allow a user to search for concepts from internal sources while creating mappings](https://issues.openmrs.org/browse/OCLOMRS-575)
When creating mappings, a user should be able to search for concepts from internal sources that they might want to select

OCLOMRS-575: Allow a user to search for concepts from internal sources while creating mappings

---

src/components/dashboard/components/dictionary/DictionaryContainer.jsx

[Concept count on dictionary summary page and concepts list do not match](https://issues.openmrs.org/browse/OCLOMRS-572)
The concept count on the dictionary summary page also includes non latest concepts that might still belong to the collection.

OCLOMRS-572: Concept count on dictionary summary page and concepts list do not match

---

src/components/dictionaryConcepts/components/ConceptTable.jsx
src/tests/dictionaryConcepts/container/DictionaryConcepts.test.jsx

[After creating a new custom diagnosis concept, there are no actions available.](https://issues.openmrs.org/browse/OCLOMRS-577)
Action buttons are not displayed sometimes because the logged in user name is not correctly retrieved.

OCLOMRS-577: After creating a new custom diagnosis concept, there are no actions available.

---

src/tests/bulkConcepts/actions/index.test.js

[Rename tests to fit the naming convention](https://issues.openmrs.org/browse/OCLOMRS-584)
Rename the test file in the path "src/tests/bulkConcepts/actions/index.test.js" to fit our current naming conventions.

OCLOMRS-584: Rename tests to fit the naming convention

---

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx
src/tests/Dictionary/DictionaryModal.test.jsx

[Cursor moves back to the name field when filling other fields when creating a new dictionary](https://issues.openmrs.org/browse/OCLOMRS-580)
When one is creating a new dictionary, the cursor still moves back to the name field when trying to fill other fields.

OCLOMRS-580: Cursor moves back to the name field when filling other fields when creating a new dictionary

---

src/components/dashboard/components/dictionary/DictionaryContainer.jsx
src/tests/Dictionary/DictionaryContainer.test.jsx

[Dictionary Summary Page shows 'Invalid Date' after releasing a new collection version](https://issues.openmrs.org/browse/OCLOMRS-583)
Dictionary Summary page shows an "Invalid date" immediately after releasing a new collection version.

OCLOMRS-583: Dictionary Summary Page shows 'Invalid Date' after  releasing a new collection version

---

src/components/bulkConcepts/addBulkConcepts.jsx
src/redux/actions/concepts/addBulkConcepts/index.js

[When adding a concept to a collection, it's mappings should be added as well](https://issues.openmrs.org/browse/OCLOMRS-591)
The endpoint for adding concept references to a collection includes a cascade query option.
We want to add these mappings to the collection, so it should be set to cascade=sourcemappings

OCLOMRS-591: When adding a concept to a collection, its mappings should be added as well

---

src/redux/actions/concepts/dictionaryConcepts.js

[If there is an error while updating a concept after the concept itself has been updated, its reference should still be updated](https://issues.openmrs.org/browse/OCLOMRS-590)
If a concept's details have been successfully updated, it's reference in the collection should also be updated.
Currently, if there is an error after a concept's details have been updated, but before the update method completes, the concept's reference is not updated, leading to us having an old reference to the concept in our collection

OCLOMRS-590: If there is an error while updating a concept after the concept itself has been updated, its reference should still be updated

---

src/components/dictionaryConcepts/components/CreateConceptForm.jsx
src/components/dictionaryConcepts/containers/CreateConcept.jsx
src/components/dictionaryConcepts/containers/EditConcept.jsx
src/tests/dictionaryConcepts/container/CreateConcept.test.jsx

[Rename the UUID field to “OpenMRS UUID (OCL External ID)” and add an “OCL ID” field](https://issues.openmrs.org/browse/OCLOMRS-587)
When creating a concept, the UUID field should be renamed to “OpenMRS UUID (OCL External ID)”  and we should add another ID field with the name,  “OCL ID”
When editing a concept, both ID fields should not be editable

OCLOMRS-587: Rename the UUID field to “OpenMRS UUID (OCL External ID)” and add an “OCL ID” field

---

src/components/dictionaryConcepts/components/CreateConceptForm.jsx
src/components/dictionaryConcepts/components/helperFunction.js
src/tests/dictionaryConcepts/components/helperFunction.test.js

[Pressing enter in input field in the edit concept form triggers submit](https://issues.openmrs.org/browse/OCLOMRS-594)
The edit concept form is prematurely submitted when enter is pressed when the cursor is in an input

OCLOMRS-594: Pressing enter in input field in the edit concept form triggers submit

---

src/components/dictionaryConcepts/components/CreateConceptForm.jsx
src/components/dictionaryConcepts/components/CreateMapping.jsx

[When creating external mappings, a user should not be able to search for the to_concept](https://issues.openmrs.org/browse/OCLOMRS-588)
to_concepts for external mappings do not exist in OCL and they should therefore not be searchable

OCLOMRS-588: When creating external mappings, a user should not be able to search for the to_concept

---

src/tests/bulkConcepts/components/Pagination.test.js

[Raise Test Coverage](https://issues.openmrs.org/browse/OCLOMRS-571)
Address the falling coverage on this [PR](https://github.com/openmrs/openmrs-ocl-client/pull/478)

OCLOMRS-571: Raise Test Coverage

---

src/components/bulkConcepts/container/BulkConceptsPage.jsx

[User cannot delete all characters in the search bar for adding a CIEL concept](https://issues.openmrs.org/browse/OCLOMRS-598)
When adding a CIEL concept, if a user types anything into the search bar, they cannot delete the first character inputted

OCLOMRS-598: User cannot delete all characters in the search bar for adding a CIEL concept

---

src/components/dictionaryConcepts/components/CreateConceptForm.jsx
src/components/dictionaryConcepts/components/CreateMapping.jsx
src/components/dictionaryConcepts/containers/CreateConcept.jsx
src/components/dictionaryConcepts/containers/EditConcept.jsx
src/redux/actions/concepts/dictionaryConcepts.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js
src/tests/dictionaryConcepts/components/CreateMapping.test.js
src/tests/dictionaryConcepts/container/CreateConcept.test.jsx
src/tests/dictionaryConcepts/container/EditConcept.test.jsx

[Creating mappings to internal concepts should all have a single searchable field](https://issues.openmrs.org/browse/OCLOMRS-600)
- Creating mappings to internal concepts should all have only one single search field
- Currently, there are three fields, which can be confusing to the user

OCLOMRS-600: Creating mappings to internal concepts should all have a single searchable field

---

src/redux/api.js
src/tests/Dashboard/action/api.test.js

[When creating a mapping, a user should be able to search for more than 10 concepts](https://issues.openmrs.org/browse/OCLOMRS-609)
When creating a mapping, a user should be able to search for more than 10 concepts

OCLOMRS-609: When creating a mapping, a user should be able to search for more than 10 concepts

---

src/components/dictionaryConcepts/components/helperFunction.js
src/components/dictionaryConcepts/containers/EditConcept.jsx
src/redux/actions/concepts/addBulkConcepts/index.js
src/redux/actions/concepts/dictionaryConcepts.js
src/redux/actions/dictionaries/dictionaryActionCreators.js
src/redux/api.js
src/tests/Dashboard/action/api.test.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js
src/tests/dictionaryConcepts/container/EditConcept.test.jsx

[When creating a mapping, the to-concept should also be added to the dictionary](https://issues.openmrs.org/browse/OCLOMRS-597)
When creating a mapping, the to-concept should also be added to the dictionary. Currently, only the concept created is added. However, the to-concepts referenced in the mappings added to a concept need to be present in the collection too.

OCLOMRS-597: When creating a mapping, the to-concept should also be added to the dictionary

---

src/redux/actions/concepts/dictionaryConcepts.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js

[When a concept has no mapping references, we should not attempt to delete them](https://issues.openmrs.org/browse/OCLOMRS-613)
Attempting to request delete of an empty list of references returns a 400, causing the concept mappings not to be updated

OCLOMRS-613: When a concept has no mapping references, we should not attempt to delete them

---

src/components/dictionaryConcepts/components/helperFunction.js
src/redux/actions/concepts/dictionaryConcepts.js
src/tests/__mocks__/answers.js
src/tests/dictionaryConcepts/components/helperFunction.test.js

[Fix incorrect check for blank answer and set mappings](https://issues.openmrs.org/browse/OCLOMRS-612)
The check for whether a mapping is blank is different from the one for whether an answer or set is blank. A new method is needed to reflect this.

OCLOMRS-612: Fix incorrect check for blank answer and set mappings

---

src/redux/actions/concepts/dictionaryConcepts.js
src/tests/__mocks__/concepts.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js

[Fix incorrect filter for latest concept versions on dictionaryConcepts page](https://issues.openmrs.org/browse/OCLOMRS-614)
Previously, concepts created within OCL had a null external id. This is no longer the case. This updates the filter to reflect that.

OCLOMRS-614: Fix incorrect filter for latest concept versions on dictionaryConcepts page

---

src/components/dictionaryConcepts/components/ConceptNameRows.jsx
src/tests/dictionaryConcepts/components/ConceptNameRows.test.jsx

[The locale_preffered field for names displays an incorrect value](https://issues.openmrs.org/browse/OCLOMRS-617)
The condition for displaying this field assumed that the field contains a 'Yes', 'No'. It contains a true/false. This needs to be updated.

OCLOMRS-617: The locale_preffered field for names displays an incorrect value

---

src/components/dictionaryConcepts/components/ConceptNameRows.jsx
src/components/dictionaryConcepts/components/DescriptionRow.jsx
src/tests/dictionaryConcepts/components/ConceptNameRows.test.jsx

[Names and Descriptions Should Have external_ids as well](https://issues.openmrs.org/browse/OCLOMRS-616)
external_ids are required to perform imports in OpenMRS
Names and descriptions are currently creating these as null

OCLOMRS-616: Names and Descriptions Should Have external_ids as well

---

src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx
src/redux/actions/concepts/dictionaryConcepts.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js
src/tests/dictionaryConcepts/container/DictionaryConcepts.test.jsx

[Filtering and searching at the same time is not working on the dictionary concepts page](https://issues.openmrs.org/browse/OCLOMRS-615)
Using one of these features turns off the other. Ideally a user should be able to search through filtered concepts

OCLOMRS-615: Filtering and searching at the same time is not working on the dictionary concepts page

---

src/components/dictionaryConcepts/components/CreateMapping.jsx

[When creating external mappings the code field should come before the optional name field](https://issues.openmrs.org/browse/OCLOMRS-639)
When creating external mappings the code field should be before the optional name field

OCLOMRS-639: When creating external mappings the code field should come before the optional name field

---

src/styles/dashboard.scss

[Remove confusing hover effect on action buttons](https://issues.openmrs.org/browse/OCLOMRS-622)
Button styling feels weird. If I hover over a button, it stops looking like a button (e.g., action buttons)

OCLOMRS-622: Remove confusing hover effect on action buttons

---

src/components/dashboard/components/dictionary/DictionaryContainer.jsx
src/constants.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js

[The class breakdown shows incorrect class counts](https://issues.openmrs.org/browse/OCLOMRS-626)
The “By class” breakdown isn’t working right. It shows “Diagnosis: 0” when I have a lot of diagnoses

OCLOMRS-626: The class breakdown shows incorrect class counts

---

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx

[ Remove the PIH option from Create Dictionary page](https://issues.openmrs.org/browse/OCLOMRS-625)
Excerpt from user feedback:
Create Dictionary
gives two options for Preferred Source (CIEL, PIH) but I think the application only really supports CIEL, right? So, remove the PIH option.

OCLOMRS-625: Remove the PIH option from Create Dictionary page

---

src/components/bulkConcepts/component/Sidenav.jsx
src/components/bulkConcepts/container/BulkConceptsPage.jsx
src/components/dictionaryConcepts/components/Sidenav.jsx
src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx
src/constants.js
src/redux/actions/concepts/addBulkConcepts/index.js
src/redux/actions/concepts/dictionaryConcepts.js
src/redux/actions/types.js
src/redux/reducers/ConceptReducers.js
src/redux/reducers/bulkConceptReducer.js
src/styles/app.scss
src/styles/dictionary_concepts.scss
src/tests/bulkConcepts/actions/bulkConcept.test.js
src/tests/bulkConcepts/components/Sidenav.test.jsx
src/tests/bulkConcepts/containers/BulkConceptsPage.test.js
src/tests/bulkConcepts/reducer/index.test.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js
src/tests/dictionaryConcepts/components/Sidenav.test.jsx
src/tests/dictionaryConcepts/container/DictionaryConcepts.test.jsx
src/tests/dictionaryConcepts/reducer/dictionaryConcept.test.js

[Add clear all buttons for filter options](https://issues.openmrs.org/browse/OCLOMRS-621)
I expected a “clear all” link for Datatypes and Classes (if I’ve checked 5-6 of them, don’t make me manually uncheck all of them to remove filters)

OCLOMRS-621: Add clear all buttons for filter options

---

src/redux/actions/concepts/dictionaryConcepts.js

[Populate sidenav not dispatched on the dictionary Concepts page](https://issues.openmrs.org/browse/OCLOMRS-650)
The condition for dispatching this action checks for an empty query string. This string is now a wildcard.
This updates the condition and default query to reflect this.

OCLOMRS-650: Populate sidenav not dispatched on the dictionary Concepts page

---

src/redux/actions/dictionaries/dictionaryActionCreators.js

[Searching for public dictionaries returns dictionaries with validation that is not OpenMRS](https://issues.openmrs.org/browse/OCLOMRS-651)
From [OCLOMRS-87](https://issues.openmrs.org/browse/OCLOMRS-87), the public dictionaries page is expected to display only OpenMRS validated dictionaries

OCLOMRS-651: Searching for public dictionaries returns dictionaries with validation that is not OpenMRS

---

src/components/dictionaryConcepts/components/ConceptNameRows.jsx
src/tests/dictionaryConcepts/components/ConceptNameRows.test.jsx

[Name types should be; Fully Specified, null: Synonym in UI, SHORT: Short in UI, Index Term](https://issues.openmrs.org/browse/OCLOMRS-628)
I try to create a concept with two names in English, the first one has type=Fully Specified, the second has type=Synonym. I get “An error occurred when creating a concept. Invalid name type” for the one that’s a synonym. (Possibly OpenMRS calls this “synonym” but OCL backend calls this nametype=null.)

OCLOMRS-628: Name types should be; Fully Specified, null: Synonym in UI, SHORT: Short in UI, Index Term

---

package.json
src/App.js
src/components/Auth/index.jsx
src/config/axiosConfig.js
src/config/history.js
src/redux/reducers/authReducers.js
src/setupTests.js
src/tests/Auth/index.test.jsx
src/tests/AuthReducers.test.js
src/tests/Dashboard/action/dictionaryAction.test.js
src/tests/Login/container/index.test.jsx
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js

[Logging out on one tab should log the user out in all other tabs and windows](https://issues.openmrs.org/browse/OCLOMRS-606)
When one logs out on one tab, they are not logged out from other tabs and can still try to perform actions that require authentication. This fails and sometimes causes the app to crash.
This ticket is to fix this and make it such that when one logs outs, they are automatically logged out from all the other windows and tabs automatically. Also, when one logs in, they'll be automatically logged in to any open windows and/or tabs and be able to make authenticated requests.

OCLOMRS-606: Logging out on one tab should log the user out in all other tabs and windows

---

src/components/dashboard/components/dictionary/common/Languages.js
src/components/dictionaryConcepts/components/ConceptNameRows.jsx
src/components/dictionaryConcepts/components/DescriptionRow.jsx

[Fallback to English as default locale when creating names and descriptions](https://issues.openmrs.org/browse/OCLOMRS-638)
In situations when we cannot find the locale we need from the default list, we should fall back to english

OCLOMRS-638: Fallback to English as default locale when creating names and descriptions

---

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx
src/tests/Dictionary/DictionaryModal.test.jsx

[Hide the 'Start by copying another dictionary' feature on the create dictionary page](https://issues.openmrs.org/browse/OCLOMRS-623)
Excerpt from user feedback:
Create Dictionary
there’s an option for “Start by copying another dictionary”, but it doesn’t work right. (I tried to copy a dictionary that has 13 concepts, and the resulting dictionary only has 10 concepts.) Please hide this feature for MVP release...
This ticket removes the feature that allowed one to start by copying from another dictionary in the mvp release.
A complimentary ticket to address this bug in MVP+ has been created here [OCLOMRS-624](https://issues.openmrs.org/browse/OCLOMRS-623)

OCLOMRS-623: Hide the 'Start by copying another dictionary' feature on the create dictionary page

---

src/components/dashboard/components/dictionary/EditDictionary.jsx
src/components/dashboard/components/dictionary/common/DictionaryModal.jsx

[The preffered language on a collection shows English even after it is changed to another language](https://issues.openmrs.org/browse/OCLOMRS-649)
The preffered language on a collection shows English even after it is changed to another language.
This field uses an incorrect value, which does not exist. Updating this to the value in state.

OCLOMRS-649: The preffered language on a collection shows English even after it is changed to another language

---

src/components/dashboard/components/dictionary/DictionaryContainer.jsx
src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx
src/components/userDasboard/container/UserDashboard.jsx
src/constants.js
src/helperFunctions.js
src/redux/actions/types.js
src/redux/actions/user/index.js
src/redux/api.js
src/redux/reducers/dictionaryReducer.js
src/redux/reducers/store.js
src/tests/Dashboard/action/api.test.js
src/tests/Dashboard/reducer/dictionaryReducers.test.js
src/tests/Dictionary/DictionaryContainer.test.jsx
src/tests/Dictionary/dictionaryReducer.test.js
src/tests/userDashboard/actions/index.test.js
src/tests/userDashboard/container/UserDashboard.test.jsx

[A user should be able to view and manage collections belonging to organizations they are part of- 1](https://issues.openmrs.org/browse/OCLOMRS-654)
- The view dictionaries page does not display dictionaries belonging to a user's organizations.
- The check for whether or not to display the edit button is coded to show up only when a logged in user created a collection. This also needs to show up if they are a part of the organization that created the collection.

OCLOMRS-654: A user should be able to view and manage collections belonging to organisations they are part of- 1

---

src/components/bulkConcepts/component/ConceptTable.jsx

[When adding CIEL concepts, Turn off sorting on table](https://issues.openmrs.org/browse/OCLOMRS-644)
Excerpt from feedback:
Since sorting does not perform a global sort, but rather for only a single page, this is confusing for a user hence it needs to turned off for now
This ticket disables sorting on a single page. It will be implemented in the backend and consumed in MVP+. The complimentary ticket has been created here [OCLOMRS-644](https://issues.openmrs.org/browse/OCLOMRS-644)

OCLOMRS-644: When adding CIEL concepts, Turn off sorting on table

---

src/components/dictionaryConcepts/components/ConceptTable.jsx
src/components/dictionaryConcepts/components/Sidenav.jsx
src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx
src/tests/dictionaryConcepts/container/DictionaryConcepts.test.jsx

[Searching or filtering on the dictionary concepts page should set the page back to page 1](https://issues.openmrs.org/browse/OCLOMRS-647)
The current functionality fetches whatever page the user was already on. This is a problem because the user may not realize the best match to their search was on a previous page

OCLOMRS-647: Searching or filtering on the dictionary concepts page should set the page back to page 1

---

src/components/bulkConcepts/container/BulkConceptsPage.jsx
src/redux/actions/concepts/addBulkConcepts/index.js
src/tests/bulkConcepts/actions/bulkConcept.test.js
src/tests/bulkConcepts/containers/BulkConceptsPage.test.js

[Searching or filtering on the add CIEL concepts pages should set the page back to page 1](https://issues.openmrs.org/browse/OCLOMRS-666)
The current functionality fetches whatever page the user was already on. This is a problem because the user may not realize the best match to their search was on a previous page

OCLOMRS-666: Searching or filtering on the add CIEL concepts pages should set the page back to page 1

---

src/redux/actions/concepts/addBulkConcepts/index.js

[When recursively importing concepts, improve the count to indicate only internal concepts](https://issues.openmrs.org/browse/OCLOMRS-667)
Currently, the counter shows both internal and external concepts which can be confusing to the user since we later display a count of how many concepts were added, which only reflects internal concepts

OCLOMRS-667: When recursively importing concepts, improve the count to indicate only internal concepts

---

src/styles/dictionary_modal.scss

[Dictionary description doesn't wrap](https://issues.openmrs.org/browse/OCLOMRS-674)
When on the dictionary summary page, the description of the dictionary does not wrap. This should be fixed to prevent the description text from overflowing if it is too long

OCLOMRS-674: Dictionary description doesn't wrap

---

src/components/bulkConcepts/component/Sidenav.jsx
src/components/dictionaryConcepts/components/Sidenav.jsx

[Remove '0' that shows up when there are no concepts on the dictionary concepts and add ciel concepts page](https://issues.openmrs.org/browse/OCLOMRS-675)
On the dictionary concepts and add Ciel concepts pages, if either of them has no concepts, the side-nav bar  should not show `0` or the clear button if there are no concepts to display

OLCOMRS-675: Remove '0' that shows up when there are no concepts on the dictionary concepts and add ciel concepts page

---

src/constants.js
src/redux/actions/bulkConcepts/index.js
src/redux/actions/concepts/addBulkConcepts/index.js
src/styles/notifications.scss
src/tests/bulkConcepts/actions/bulkConcept.test.js
src/tests/bulkConcepts/actions/index.test.js

[Improve notification message to user when a long running import is ongoing](https://issues.openmrs.org/browse/OCLOMRS-673)
From talk(https://talk.openmrs.org/t/ocl-for-openmrs-user-feedback-discussion/21070/44);
I added “Reasons for Referral” to my dictionary. First it does a nice-looking thing where it shows that it’s going to add 39 dependent concepts, then the number goes up to 42. But then it just says “Finalizing” and it waits there for a long time.
That text is not helpful. I would change the initial text to say “Found X dependent concepts to add” and then “Adding and dependent concepts. This may take several minutes. DO NOT NAVIGATE AWAY FROM THE APPLICATION UNTIL THIS IS COMPLETE.”

OCLOMRS-673: Improve notification message to user when a long running import is ongoing

---

src/components/dashboard/components/dictionary/DictionaryContainer.jsx
src/redux/actions/dictionaries/dictionaryActionCreators.js
src/redux/actions/dictionaries/dictionaryActions.js
src/redux/actions/types.js
src/redux/reducers/dictionaryReducers.js
src/tests/Dashboard/action/dictionaryAction.test.js
src/tests/Dashboard/reducer/dictionaryReducers.test.js

[The edit dictionary modal is not pre-populated sometimes when editting](https://issues.openmrs.org/browse/OCLOMRS-653)
This page dispatched multiple actions on mount, all of which use the same action type in state to track loading status. The result is that the loading stops when the first action is complete, hence displaying the page and edit button before the data is ready.
The solution is to have each of these actions have a separate loading value in state
The workaround in such situations is to refresh the page
This is a larger problem though, and a larger ticket- OCLOMRS-670 has been created to deal with the other aspects

OCLOMRS-653: The edit dictionary modal is not prepopulated sometimes when editting

---

src/components/userDasboard/components/DashboardDetails.jsx

JIRA TICKET NAME:
[The dictionary count on the home page is not shown if a user is a member if an organization](https://issues.openmrs.org/browse/OCLOMRS-676)
The dictionary count on the main page is not shown when a user is not a part of any organization because the markup rendered for this condition does not contain these details

OCLOMRS-676: The dictionary count on the home page is not shown if a user is a member if an organisation

---

src/helperFunctions.js
src/redux/actions/concepts/addBulkConcepts/index.js
src/redux/actions/concepts/dictionaryConcepts.js
src/tests/helperFunctions.test.js

[Modify Search Queries to allow for partial search](https://issues.openmrs.org/browse/OCLOMRS-677)
As per this([https://talk.openmrs.org/t/developing-the-ocl-for-openmrs-application/17771/1095)]
Search queries must be explicitly formatted with '*'s if we would like to perform partial token base search, i.e
When searching for "The Day"
This: ?q=th*+da*(search for things that match both 'th' and 'da' partially)
Instead of what we are currently doing: ?q=th+da*(search for things that match 'th da' partially)

OCLOMRS-677: Modify Search Queries to allow for partial search

---

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx

[The collection owner and preffered source fields on the dictionary modal should not display duplicate values for a single item](https://issues.openmrs.org/browse/OCLOMRS-671)
Citing from talk;
About creating/editing dictionaries
- I created a dictionary. Then I click Edit.
- and the owner dropdown looks like;
(image in JIRA Ticket)
- then I change visibility to Private, and the owner dropdown changes to this:
(image in JIRA Ticket)
It should not show two options where there’s only real option
It shouldn’t change the text for no apparent reason.
This same situation applies for the preferred Source field

OCLOMRS-671: The collection owner and preffered source fields on the dictionary modal should not display duplicate values for a single item

---

src/components/dictionaryConcepts/components/CreateConceptForm.jsx

[to_concept_coded should not appear as a datatype](https://issues.openmrs.org/browse/OCLOMRS-685)
When creating a new procedure concept, the  to_concept_coded option appears in the list. This should not be the case

OCLOMRS-685: to_concept_coded should not appear as a datatype

---

src/components/Navbar.js

[Rename ‘All Dictionaries’ field to ‘Public Dictionaries' in the NavBar](https://issues.openmrs.org/browse/OCLOMRS-678)
Rename ‘All Dictionaries’ field to ‘Public Dictionaries’ in the NavBar

OCLOMRS-678: Rename ‘All Dictionaries’ field to ‘Public Dictionaries' in the NavBar

---

src/components/dashboard/components/dictionary/AddDictionary.jsx
src/tests/Dictionary/AddDictionary.test.js

[Creating collections belonging to a user fails](https://issues.openmrs.org/browse/OCLOMRS-683)
OCLOMRS-671 makes a change that breaks this. This ticket updates the check that was previously checking for an owner called 'Individual' to check for the username instead in order to decide who the collection belongs to

OCLOMRS-683: Creating collections belonging to a user fails

---

src/components/dictionaryConcepts/components/CreateConceptForm.jsx

[The 'coded' datatype is missing when creating a concept](https://issues.openmrs.org/browse/OCLOMRS-690)
The 'coded' concept is missing as a data type option when creating a concept. This PR rectifies that.

Oclomrs-690: The 'coded' datatype is missing when creating a concept

---

src/components/dashboard/components/dictionary/ListDictionaries.jsx
src/components/dashboard/container/DictionariesDisplay.jsx
src/redux/actions/dictionaries/dictionaryActionCreators.js
src/redux/reducers/dictionaryReducers.js
src/tests/Dashboard/action/dictionaryAction.test.js
src/tests/Dashboard/container/DictionaryDisplay.test.jsx
src/tests/Dashboard/reducer/dictionaryReducers.test.js
src/tests/Dictionary/ListDictionaries.test.jsx

[Remove the initial load on the Public Dictionaries Page](https://issues.openmrs.org/browse/OCLOMRS-684)
This initial load is slow and following this discussion(https://talk.openmrs.org/t/developing-the-ocl-for-openmrs-application/17771/1090) and the preceding thread, the decision was to have users search before fetching any data

OCLOMRS-684: Remove the initial load on the Public Dictionaries Page

---

src/components/dictionaryConcepts/components/helperFunction.js

[Set the number of levels to check for to-concepts in mappings to 10](https://issues.openmrs.org/browse/OCLOMRS-691)
This number is arbitrary and is currently set to 2. Set this number to 10 to reduce the chance that mappings imported at the last level don't have their concepts brought in as well. Details on this are contained in ticket OCLOMRS-688.

OCLOMRS-691: Set the number of levels to check for to-concepts in mappings to 10

---

src/components/dictionaryConcepts/components/ConceptNameRows.jsx
src/components/dictionaryConcepts/components/DescriptionRow.jsx
src/tests/helperFunctions.test.js

[The collection’s default language should dictate the default language when adding a new name/ description](https://issues.openmrs.org/browse/OCLOMRS-692)
Currently, this language is set to English by default. It should change based on a collection's preferred language.

OCLOMRS-692: The collection’s default language should dictate the default language when adding a new name/ description

---

src/components/dashboard/components/dictionary/common/DictionaryModal.jsx
src/components/userDasboard/container/UserDashboard.jsx
src/tests/Dictionary/DictionaryModal.test.jsx

[When creating a collection, the owner field says the field is required even after selecting it](https://issues.openmrs.org/browse/OCLOMRS-694)
From OCLOMRS-133, this field should automatically select the currently logged in user as the owner if they are not part of any organizations

OCLOMRS-694: When creating a collection, the owner field says the field is required even after selecting it

---

src/components/dictionaryConcepts/components/helperFunction.js
src/redux/actions/concepts/addBulkConcepts/index.js
src/tests/bulkConcepts/actions/bulkConcept.test.js
src/tests/dictionaryConcepts/components/helperFunction.test.js

[When you try to add a CIEL concept, even if the concept is there, it should recursively add the dependencies and give a better message](https://issues.openmrs.org/browse/OCLOMRS-696)
When you try to add a CIEL concept, even if the concept is there, it should recursively add the dependencies(this seems to already be working okay), and give a better(more informative) message(if the amount of work is justified for MVP). It currently simply says the concept was already added

OCLOMRS-696: When you try to add a CIEL concept, even if the concept is there, it should recursively add the dependencies and give a better message

---

src/redux/actions/concepts/dictionaryConcepts.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js

[App crashes when an error is encountered when creating a concept](https://issues.openmrs.org/browse/OCLOMRS-697)
When an error occurs while creating a concept, we dispatch the errors object which gets added to the concepts list. This is incorrect and causes the app to crash

OCLOMRS-697: App crashes when an error is encountered when creating a concept

---

src/components/dashboard/components/dictionary/DictionaryContainer.jsx
src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx
src/components/dashboard/components/dictionary/DictionaryVersionsTable.jsx
src/tests/Dictionary/DictionaryContainer.test.jsx

[When a dictionary version is released, the download option should produce a file with mappings](https://issues.openmrs.org/browse/OCLOMRS-682)
Mappings should be included in this file. They currently don't seem to be included
- Discussion on [talk](https://talk.openmrs.org/t/developing-the-ocl-for-openmrs-application/17771/1105)
- The download option should not be generating this file on the frontend.
- Find the endpoint that provides this file and simply link to them.
- If they are multiple/ cannot be found, drop this feature from the MVP

OCLOMRS-682: When a dictionary version is released, the download option should produce a file with mappings

---

src/App.js
src/components/dictionaryConcepts/components/ActionButtons.jsx
src/components/dictionaryConcepts/components/ViewConcept.jsx
src/tests/__mocks__/concepts.js
src/tests/dictionaryConcepts/components/ViewConcept.test.jsx

[Viewing a concept should display the particular concept version, and not merely the latest one](https://issues.openmrs.org/browse/OCLOMRS-700)
Currently, viewing a concept displays the latest version of that concept, and not the version in the collection. This is incorrect.

OCLOMRS-700: Viewing a concept should display the particular concept version, and not merely the latest one

---

src/components/dictionaryConcepts/containers/SelectAnswers.jsx

[The Answer and Set Inputs when creating a concept should also have spinners when loading internal concepts](https://issues.openmrs.org/browse/OCLOMRS-699)
Currently, the Answer and Set Inputs when creating a concept do not have spinners showing progress when the concepts are being retrieved. It is better UX for these to have a loader

OCLOMRS-699: The Answer and Set Inputs when creating a concept should also have spinners when loading internal concepts

---

src/components/dashboard/components/dictionary/DictionaryContainer.jsx
src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx
src/tests/Dictionary/DictionaryContainer.test.jsx
src/tests/__mocks__/dictionaries.js

[The view dictionary page should not fetch all a dictionary's concepts](https://issues.openmrs.org/browse/OCLOMRS-702)
This page currently fetches the verbose dictionary with all mappings and concepts.
This information is used to display a concept breakdown.
This presents a performance issue for this page if a dictionary contains a large number of concepts.

OCLOMRS-702: The view dictionary page should not fetch all of a dictionary's concepts

---

src/redux/actions/concepts/addBulkConcepts/index.js
src/tests/bulkConcepts/actions/bulkConcept.test.js

[When recursively fetching mappings while adding CIEL concepts, external mappings should be left out](https://issues.openmrs.org/browse/OCLOMRS-704)
Currently, external mappings are included as well. This is not correct and may cause the process to fail or add incorrect concepts.

OCLOMRS-704: When recursively fetching mappings while adding CIEL concepts, external mappings should be left out

---

src/redux/actions/dictionaries/dictionaryActionCreators.js
src/redux/api.js
src/tests/Dashboard/action/api.test.js
src/tests/Dashboard/action/dictionaryAction.test.js

[Updating a dictionary should update both the source and collection](https://issues.openmrs.org/browse/OCLOMRS-715)
Updating a dictionary currently only updates the collection and not the source as well. This creates a situation where the two repositories are out of sync.

OCLOMRS-715: Updating a dictionary should update both the source and collection

---

src/components/bulkConcepts/addBulkConcepts.jsx
src/redux/actions/bulkConcepts/index.js
src/tests/bulkConcepts/actions/index.test.js
src/tests/bulkConcepts/addBulkConcepts.test.jsx

[Remove unnecessary API calls on the add bulk concepts page](https://issues.openmrs.org/browse/OCLOMRS-709)
The API call to retrieve the concept sources in the bulk concept page was unnecessary and thus removed.

OCLOMRS-709: Remove unnecessary API calls on the add bulk concepts page

---

src/helperFunctions.js
src/redux/actions/bulkConcepts/index.js
src/redux/actions/concepts/ConceptActionCreators.js
src/redux/actions/concepts/dictionaryConcepts.js
src/redux/actions/concepts/specificConceptAction.js
src/redux/actions/dictionaries/dictionaryActionCreators.js
src/redux/actions/dictionaries/dictionaryActions.js
src/redux/actions/globalActionCreators/index.js
src/redux/actions/types.js
src/redux/actions/user/index.js
src/redux/reducers/ConceptReducers.js
src/tests/Dashboard/action/ConceptsActionCreator.test.js
src/tests/Dashboard/action/dictionaryAction.test.js
src/tests/Dashboard/action/specificConceptAction.test.js
src/tests/bulkConcepts/actions/index.test.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js
src/tests/dictionaryConcepts/reducer/dictionaryConcept.test.js
src/tests/userDashboard/actions/index.test.js

[Remove isErrored action creator](https://issues.openmrs.org/browse/OCLOMRS-703)
Some parts of the code use isErrored to dispatch an error response into state, causing unexpected crashes. These parts should be refactored to notify the user of the error, but not add it to state.
Dispatching a zero value(eg. empty list) would make sense.

OCLOMRS-703: Remove isErrored action creator

---

src/components/dictionaryConcepts/components/CreateConceptForm.jsx

[The coded datatype should only be an option on pages where we can add answers to a concept](https://issues.openmrs.org/browse/OCLOMRS-712)
Concepts with this datatype should be able to have answers. For MVP, we will only make this option available on the Add Q-A concepts and add another type of concept pages.

OCLOMRS-712: The coded datatype should only be an option on pages where we can add answers to a concept

---

src/tests/bulkConcepts/components/PreviewCard.test.js

[Fix Broken OCL Client Build](https://issues.openmrs.org/browse/OCLOMRS-724)
A test in one of the suites uses an implementation detail in one of the dependencies, causing inconsistent behaviour when testing in different environments. This eliminates that dependency while maintaining the test.

OCLOMRS-724: Fix Broken OCL Client Build

---

src/components/bulkConcepts/component/ConceptTable.jsx
src/components/bulkConcepts/component/SearchBar.jsx
src/components/bulkConcepts/component/SortBar.jsx
src/components/bulkConcepts/container/BulkConceptsPage.jsx
src/components/dictionaryConcepts/components/ConceptTable.jsx
src/components/dictionaryConcepts/containers/DictionaryConcepts.jsx
src/redux/actions/concepts/addBulkConcepts/index.js
src/redux/actions/concepts/dictionaryConcepts.js
src/redux/actions/types.js
src/redux/reducers/ConceptReducers.js
src/redux/reducers/bulkConceptReducer.js
src/styles/app.scss
src/styles/bulk_concepts.scss
src/tests/Dashboard/reducer/conceptReducer.test.js
src/tests/bulkConcepts/actions/bulkConcept.test.js
src/tests/bulkConcepts/components/SortBar.test.jsx
src/tests/bulkConcepts/reducer/index.test.js
src/tests/dictionaryConcepts/actions/dictionaryConcept.test.js

[Allow users to sort concepts on the add ciel concepts page and in their collection](https://issues.openmrs.org/browse/OCLOMRS-719)
Currently, we user a default sort criteria for both of these pages. This allows the user to sort concepts by `bestMatch`, `name` or `id`.

OCLOMRS-719: Allow users to sort concepts on the add ciel concepts page and in their collection

---

src/helperFunctions.js
src/redux/actions/concepts/dictionaryConcepts.js

[Add a little delay before making the request for concepts on the dictionary concepts page](https://issues.openmrs.org/browse/OCLOMRS-723)
For context;
Upon updating of a custom concepts in edit screen, returning to view concepts page did not show the concept at all. I had to click and unclick the custom concept filter to show. (MVP)
We noticed this has once again popped up of late. This appears to come from a ~slow update of the search index after a concept is added to the collection(on the backend). We’ll have to add a small delay before making that request to allow the update to complete.
https://talk.openmrs.org/t/developing-the-ocl-for-openmrs-application/17771/1240

OCLOMRS-723: Add a little delay before making the request for concepts on the dictionary concepts page

---

src/redux/reducers/ConceptReducers.js
src/tests/Dashboard/reducer/conceptReducer.test.js
src/tests/__mocks__/concepts.js

[Remove paginatedConcepts from dictionary concepts state](https://issues.openmrs.org/browse/OCLOMRS-727)
Remove unused state field

OCLOMRS-727: Remove paginatedConcepts from dictionary concepts state

---

src/components/dashboard/components/dictionary/DictionaryDetailCard.jsx
src/components/dashboard/components/dictionary/common/DictionaryModal.jsx
src/components/dictionaryConcepts/components/helperFunction.js

[OCLOMRS-646: Add support for multiple preferred sources](https://issues.openmrs.org/browse/OCLOMRS-646)
Added support for AMPATH and PIH sources
- If images don't show up, here's the link to Google Drive folder: [Google Drive](https://drive.google.com/open?id=1Ti299O2s65Bnq2U-NvsugELY21QrW5n3)

OCLOMRS-646: Added support for multiple preferred sources

---

.travis.yml
cypress/support/commands.js
package.json
src/App.tsx
src/apps/authentication/LoginPage.tsx
src/apps/authentication/components/AuthenticationRequired.tsx
src/apps/concepts/Routes.tsx
src/apps/concepts/components/FilterOptions.tsx
src/apps/concepts/pages/CreateOrEditConceptPage.tsx
src/apps/concepts/pages/ViewConceptPage.tsx
src/apps/concepts/pages/ViewConceptsPage.tsx
src/apps/concepts/tests/e2e/ViewConceptsPage.test.ts
src/apps/concepts/utils.ts
src/apps/dictionaries/Routes.tsx
src/apps/dictionaries/pages/AddBulkConceptsPage.tsx
src/apps/dictionaries/pages/EditDictionaryPage.tsx
src/apps/dictionaries/tests/e2e/CreateDictionaryPage.test.ts
src/components/Header.tsx
src/redux/reducer.ts
src/utils/constants.ts

JIRA TICKET NAME:
[Return to dictionary after changing source (Confusing navigation between pages)](https://issues.openmrs.org/browse/OCLOMRS-765)
When adding new concepts to the dictionary , changed from CIEL to PIH and back again. Doing this changes the behavior of the back arrow at the top, as this now backs up through the changing sources. It needs to ALWAYS go back to viewing the concepts in the dictionary that are added.

OCLOMRS-765: Return to dictionary after changing source (Confusing navigation between pages)

---

package.json
src/apps/concepts/components/ConceptsTable.tsx
src/apps/concepts/pages/CreateOrEditConceptPage.tsx
src/apps/concepts/pages/ViewConceptPage.tsx
src/apps/concepts/pages/ViewConceptsPage.tsx
src/apps/concepts/types.ts
src/apps/dictionaries/api.ts
src/apps/dictionaries/components/DictionaryForm.tsx
src/apps/dictionaries/components/ReleasedVersions.tsx
src/apps/dictionaries/constants.ts
src/apps/dictionaries/pages/EditDictionaryPage.tsx
src/apps/dictionaries/pages/ViewDictionaryPage.tsx
src/apps/dictionaries/pages/tests/e2e/EditDictionaryPage.test.ts
src/apps/dictionaries/redux/actionTypes.ts
src/apps/dictionaries/redux/actions.ts
src/apps/dictionaries/redux/selectors.ts
src/apps/dictionaries/types.ts
src/apps/sources/types.ts
src/redux/selectors.ts
src/redux/utils.ts
src/utils/types.ts

[JIRA ticket name](https://issues.openmrs.org/browse/OCLOMRS-821)
*Acceptance criteria*
* A dictionary created in the OCL web should be listed in the OCL for OpenMRS list of public dictionaries.
* The user should be able to select the source in the new UI
*Tasks*
* Remove API filter to see dictionaries created in OCL
* Add a field for the user to select the source in the new UI

OCLOMRS-821: As an organization member, I want to see the list of dictionaries created in OCL web so that I can use them in the new UI

---

src/apps/concepts/components/ConceptsTable.tsx
src/apps/concepts/pages/CreateOrEditConceptPage.tsx
src/apps/concepts/pages/ViewConceptsPage.tsx
src/apps/concepts/pages/tests/e2e/ViewConceptsPage.test.ts
src/apps/concepts/redux/reducer.ts
src/apps/dictionaries/redux/reducer.ts
src/apps/sources/redux/reducer.ts

* Rakesh | OCLOMRS-859 | MOBN-1410 | Flush Dictionaries from store on logout
* Rakesh | OCLOMRS-859 | MOBN-1410 | Load concept from browser url on edit concept page
* Rakesh | OCLOMRS-859 | MOBN-1410 | Fixed console errors on viewconceptspage
* Rakesh | OCLOMRS-859 | MOBN-1410 | Flush Sources & Concepts from store on logout
[OCLOMRS_859](https://issues.openmrs.org/browse/OCLOMRS-859)
Users face issues with respect to seeing the right information on certain pages, which retains the information from previously opened pages which causes confusion and ends up with wrong/undesired actions from the users.
For ex: Edit screen of custom concepts shows the Edit screen of another custom concept which was opened earlier, Similarly the list of dictionaries under Your Dictionaries page also retains …

Rakesh | OCLOMRS-859 | MOBN-1410 | Page retains the information from previously opened pages and causes confusion

---

src/apps/concepts/components/ConceptForm.tsx
src/apps/concepts/components/MappingsTable.tsx
src/apps/concepts/pages/tests/e2e/testUtils.ts

[OCLOMRS-863](https://issues.openmrs.org/browse/OCLOMRS-863)
In concept details page, user have a section to capture the set members of that particular concept. However the label currently is kept as 'Sets' instead of 'Set Members'. As part of this card, the label has to be renamed.
Following labels should be renamed
1. Title of the section 'Sets' to 'Set Members'
2. Label of the button 'Add Set' to 'Add set members'
3. Validation message 'No Sets' to 'No set members'

Rakesh | OCLOMRS-863 | MOBN-1416 | Rename 'Sets' as 'Set Members' in concepts details page

---

src/apps/dictionaries/components/DictionaryForm.tsx
src/apps/dictionaries/components/ReleasedVersions.tsx
src/apps/dictionaries/pages/ViewDictionaryPage.tsx
src/apps/sources/components/SourceForm.tsx
src/index.scss

* Rakesh | OCLOMRS-860 | MOBN-1411 | Added min width for fieldset
* Rakesh | OCLOMRS-860 | MOBN-1411 | Added multiline and max-row for name, shortcode in dictionaries and sources details page
* Rakesh | OCLOMRS-860 | MOBN-1411 | Wrap whiteSpace for supported locales dropdown
* Rakesh | OCLOMRS-860 | MOBN-1411 | Fixes code review comments
* Rakesh | OCLOMRS-860 | MOBN-1411 | Added multiline for linked_source in dictionary form &
custom validation schema in Sourceform
[OCLOMRS-860](https://issues.openmrs.org/browse/<ticket-id>)
If the details captured while creating a dictionary is too lengthy to get accommodated within the width of the general details section of a dictionary, the text doesn't get wrapped to the next line, instead it keeps going beyond the General details section boundary, …

Rakesh | OCLOMRS-860 | MOBN-1411 | [UI] General details section is not wrapped and hence the alignment is affected with lengthy information (#22)

---

src/redux/__test__/utils.test.ts
src/redux/utils.ts

* Rakesh | OCLOMRS-862 | MOBN-1419 | Show form validation errors from backend in UI
* Rakesh  | OCLOMRS-862 | MOBN-1419 | Added test cases for errorMsg function
[OCLOMRS-862](https://issues.openmrs.org/browse/OCLOMRS-862)
Today when the user creates/edits a concept, user doesn't get clear validation message on the UI. Instead user gets a generic message that the action couldn't be completed.
Identifies the list of backend validation messages and enable the same on UI

OCLOMRS-862 | Display more specific validation messages on Concept create/edit screen 

---

src/apps/sources/__test__/api.test.ts
src/apps/sources/api.ts

[Unable to see CIEL dictionary](https://issues.openmrs.org/browse/OCLOMRS-866)
The CIEL and other public sources are not visible in the OCL for OpenMRS web client because the client filters public sources to those with source type "Dictionary" (i.e., it queries the API for sources using the parameter ?sourceType=Dictionary).
On Staging and Production, CIEL's source type is "Interface Terminology"
```
curl https://api.staging.openconceptlab.org/orgs/CIEL/sources/CIEL/
{
"id": "CIEL",
"source_type": "Interface Terminology",
...
}
```
After discussion with Jonathan Payne, we believe this filtering was a work in progress to filter out external sources when Lincoln Karuhanga had to step away from the project.

Rakesh | OCLOMRS-866 | MOBN-1436 | Unable to see CIEL dictionary

---

src/apps/dictionaries/__test__/components/ReleasedVersions.test.tsx
src/apps/dictionaries/__test__/pages/ViewDictionaryPage.test.tsx
src/apps/dictionaries/components/ReleasedVersions.tsx
src/apps/dictionaries/pages/ViewDictionaryPage.tsx
src/apps/dictionaries/pages/tests/e2e/ViewDictionaryPage.test.ts
src/apps/dictionaries/redux/actions.ts
src/apps/dictionaries/types.ts

[OCLOMRS-869](https://issues.openmrs.org/browse/OCLOMRS-869)
Released Version component is not responsive. For a smaller window, UI is breaking.
Make this component responsive so that it will not break the UI. For a smaller window, horizontal scroll bar should appear.
Each version of a dictionary can have multiple actions associated to it such as View concepts, Copy subscription URL, Download the zip file of concepts, etc. Such actions buttons need to be arranged on the UI in such a way that it is aligned properly and improves the UX. Also Include created date as a new column next to the version ID

Kirity, Vinisha, Tarun | OCLOMRS-869 | MOBN-1441 | Make released version component of dictionary responsive and include date created field

---

src/apps/concepts/components/ConceptForm.tsx

[User allowed to create multiple different concepts with same UUID](https://issues.openmrs.org/browse/OCLOMRS-877)
Expected:
UUID field in Custom Concept creating experience should auto-populate a unique UID for each new custom concept created.
If for some reason the user manually edited the UUID field to have the same UUID as another concept, the user should not be allowed to save this.
The UUID should be unique for all the concepts. Otherwise it will create issues when importing into OpenMRS.
Right now in staging, there are two problems:
1) the UUID field auto-generates the same UUID # for every custom concept, instead of a random one each time
2) the user is allowed to create multiple different concepts with the same UUID (when they should not be able to save the form)

Rakesh | OCLOMRS-877 | MOBN-1448 | User allowed to create multiple different concepts with same UUID

---

src/apps/concepts/pages/CreateOrEditConceptPage.tsx
src/apps/concepts/redux/actions.ts

https://issues.openmrs.org/browse/OCLOMRS-878
I added a return function to the effect. This function is to be called when the effect needs to be cleaned up.

OCLOMRS-878: Previous Concept Form Validation Error Message Persists into New Custom Concept Form

---

src/apps/concepts/redux/actions.ts

https://issues.openmrs.org/browse/OCLOMRS-889
I removed the [mappings, MAPPINGS_BATCH_INDEX, "mappings"] element so that we no longer try to add a concept to the dictionary simply because we have mapped one of our concepts to it.

OCLOMRS-889: Don't pull in concepts from other sources for mappings

---

src/apps/dictionaries/pages/CreateDictionaryPage.tsx
src/apps/dictionaries/pages/EditDictionaryPage.tsx
src/apps/dictionaries/redux/actions.ts

https://issues.openmrs.org/browse/OCLOMRS-892
I added a react hook to reset the form state when you recreate a form.

OCLOMRS-892: Reset the Error Message on create and edit dictionary form

---

src/apps/sources/components/SourceForm.tsx

https://issues.openmrs.org/browse/OCLOMRS-896
I fixed the  `Owner field` on the Create Source form to be  mandatory

OCLOMRS-896: Owner field not mandatory for source

---

src/apps/authentication/LoginPage.tsx

https://issues.openmrs.org/browse/OCLOMRS-855
Fixed the validation error when one uses a wrong password or username by removing undefined object  which was making the error message not to be returned from the OCL API.

OCLOMRS-855: Missing error message with wrong login credentials

---

src/apps/concepts/components/ConceptsTable.tsx

https://issues.openmrs.org/browse/OCLOMRS-874
I deleted the
```
useEffect(() => {
resetSelected();
``` 
Which was  resetting the  selected concepts when new ones are fetched.

OCLOMRS-874:Concept selections in "Pick from existing" disappear if user extends list length

---

src/apps/concepts/types.ts

[Sort Names Alphabetically by Language (so Long & Short names end up grouped together](https://issues.openmrs.org/browse/OCLOMRS-907)
In the buildInitialValues() function which takes the set of names as a parameter, the names are passed to that function as an array. To  sort the names alphabetically by language, I called the Array.prototype.sort() function with an appropriate comparator function as reflected in the code below.

OCLOMRS-907: Sort Names Alphabetically by Language

---

package-lock.json
src/apps/organisations/pages/EditOrgPage.tsx

Issue worked on 
[OCLOMRS-934](https://issues.openmrs.org/browse/OCLOMRS-934)
- I added functionality to the NO button found on the warning modal that appears when a user clicks the delete Organisation button on the Edit Organisation Page.

OCLOMRS-934: Fix the NO button on the dialog modal for deleting an organisation

---

src/apps/authentication/components/UserTokenDetails.tsx

[OCLOMRS-929](https://issues.openmrs.org/browse/OCLOMRS-929)
This change uses a simple blur effect to obscure the user's API token on their profile page. The token is visible on hover and can be copied to clipboard just as before. This simple approach can help protect user API tokens from being accidentally compromised until we come up with a better approach.

OCLOMRS-929: Obscure api token on user profile page

---

src/apps/dictionaries/logic.ts

[Recursively loading concepts shouldn't try to reload the concept more than once](https://issues.openmrs.org/browse/OCLOMRS-926>)
I fixed the tracking of concepts being fetched an sure that each concept is only loaded a single time.

OCLOMRS-926:Recursively loading concepts shouldn't try to reload the concept more than once

---

src/apps/containers/api.ts
src/apps/dictionaries/api.ts
src/apps/sources/api.ts

[Concept counts not displayed when using API2](https://issues.openmrs.org/browse/OCLOMRS-923)
Fixes this issue by appending the `includeReferences=true` when loading the dictionary.

OCLOMRS-923: Concept counts not displayed when using API2

---

src/apps/authentication/api.ts
src/apps/authentication/components/UserOrganisationDetails.tsx

[OCLOMRS-942: Wrong organisations returned for users](https://issues.openmrs.org/browse/OCLOMRS-942)
Drops the `sortAsc=name` parameter from the request getting the list of organisations and adopts case-insensitive, locale-sensitive sorting for the list of organisations where this is displayed to users.

OCLOMRS-942: Wrong organisations returned for users

---

src/apps/organisations/components/ViewOrgsPage.tsx
src/apps/organisations/pages/ViewOrgPage.tsx
src/apps/organisations/redux/actions.ts

[Error Message Persists for failed Add Member](https://issues.openmrs.org/browse/OCLOMRS-954)
- Once the user clears the error message, it shouldn't show up again when I go back to that Organization, or when I go look at another different Organization or even the same organisation.

OCLOMRS-954: Reset adding and deleting org members

---

src/apps/concepts/pages/CreateOrEditConceptPage.tsx
src/apps/organisations/components/OrgMembers.tsx
src/apps/organisations/pages/ViewOrgPage.tsx

Missing Permissions Check for Organization Member Management:OCLOMRS-955 and Missing Permissions Check for "Edit Organization" button:OCLOMRS-956"

OCLOMRS-955 and OCLOMRS-956: Add missing permissions checks for organizations

---

src/App.tsx
src/apps/concepts/Routes.tsx
src/apps/concepts/components/AlreadyAddedIcon.tsx
src/apps/concepts/components/ConceptsTableRow.tsx
src/apps/concepts/pages/CreateOrEditConceptPage.tsx
src/apps/concepts/pages/ViewConceptsPage.tsx
src/apps/concepts/types.ts

[OCLOMRS-491](https://issues.openmrs.org/browse/OCLOMRS-491)
- Disable the add concept button on the CIEL concepts page when a specific concept is added.

OCLOMRS-491: Restyle already added concepts and add a tick icon.

---

Dockerfile
src/apps/authentication/LoginPage.tsx
src/apps/concepts/components/ViewConceptsHeader.tsx
src/components/Header.tsx
src/components/NavDrawer.tsx
src/utils/constants.ts
startup.sh

[OCLOMRS-959: Display OCL for OpenMRS Client Build](https://issues.openmrs.org/browse/OCLOMRS-959)
Adds a build number indicator to the login page and to the nav bar when the nav bar is expanded as show below:

OCLOMRS-959: Display OCL for OpenMRS Client Build

---

src/apps/organisations/api.ts

[Error:Cannot Edit Organization](https://issues.openmrs.org/browse/<OCLOMRS-962>)
I replaced the `post` in the  `src/apps/organisations/api.ts` file with `put` because the error from the api  after editing the changes indicated we are re-creating the page and couldn't save the changes successfully but with `put` when updating the file saves the changes successfully.

OCLOMRS-962:Error:Cannot Edit Organization

---

src/apps/dictionaries/redux/actions.ts
src/apps/dictionaries/types.ts

[Support populating the "source_type" and "collection_type" properties](https://issues.openmrs.org/browse/OCLOMRS-981)
- Added `source_type` and `collection_type` of `Dictionary` when creating a source and dictionary.

OCLOMRS-981: Add support for source and collection types.

---

src/apps/concepts/api.ts
src/apps/concepts/pages/ViewConceptsPage.tsx
src/utils/constants.ts

[General Filter: Hide Retired Concepts & Add Filter option to Include Retired Concepts](https://issues.openmrs.org/browse/OCLOMRS-932)
I changed includeRetired: includeRetired ? 1 : 0
Back to :
includeRetired
to enable filtering of retired concepts well.

OCLOMRS-932: Hide retired concepts & add option to include retired concepts

---

src/apps/concepts/__test__/api.test.ts
src/apps/sources/__test__/api.test.ts
src/utils/tests/unit/utils.test.ts
src/utils/utils.ts

[Remove the star on the query paramater](https://issues.openmrs.org/browse/OCLOMRS-1002)
- Remove the default `q*` from the request since the API no longer supports it.

OCLOMRS-1002: Remove the start to fix the request.

---

README.md
app.json
public/index.html
src/apps/authentication/LoginPage.tsx
src/apps/authentication/components/Login.tsx
src/apps/concepts/components/ConceptForm.tsx
src/components/Header.tsx
src/components/NavDrawer.tsx

Some light re-branding as the OpenMRS Dictionary Manager
Most of the changes are in these two screenshots:

Re-branding as OpenMRS Dictionary Manager

---

src/apps/concepts/api.ts
src/apps/concepts/pages/ViewConceptsPage.tsx
src/apps/sources/pages/ViewSourcePage.tsx
src/utils/constants.ts

[General Filter: Hide Added Concepts & Add Filter option to Include Added Concepts
](https://issues.openmrs.org/browse/OCLOMRS-933)
- Added ability to include and exclude.
- Used the endpoint provided by backend that returns only concepts that are not yet added, refer to this PR https://github.com/openconceptlab/ocl_issues/issues/728

OCLOMRS-933: Add ability to include and exclude already added concepts.

---

run_e2e.sh

Adds a script to run Cypress tests in a Docker container. This is intended to be used in conjunction with the `start_local_instance.sh` script, so to use it, run:
```sh
./start_local_instance.sh
./run_e2e.sh
./stop_local_instance.sh
```

Add a script to run Cypress in a Docker container

---

src/apps/concepts/pages/ViewConceptPage.tsx

Give it a backUrl which will skip the older concept version url
[Answers are not being displayed even the concepts are coded](https://issues.openmrs.org/browse/OCLOMRS-1022)
- Gave the header a backUrl which points to the dictionary concepts page to avoid going to the older concept version page which was the bug.
https://user-images.githubusercontent.com/30952856/130160565-59d6d57e-b918-4bf6-94d5-d0a14360d6a9.mov

OCLOMRS-1022: Answers are not being displayed even the concepts are coded

---

src/apps/sources/components/SourceForm.tsx

[Cannot select another language for a source](https://issues.openmrs.org/browse/OCLOMRS-1043)
I fixed the Source to enable  the user select  another language from the dropdown menu.

OCLOMRS-1043:Cannot select another language for a source

---

cypress/support/step_definitions/dictionary/createVersion/createVersion.ts
src/apps/dictionaries/api.ts
src/apps/sources/__test__/api.test.ts
src/apps/sources/api.ts

[Your Organizations Sources shows user-owned sources](https://issues.openmrs.org/browse/OCLOMRS-1031)
As Your Organization Source and Your Source were returning the same data, I have updated the query with verbose: true so that now it returns the desired result. And the same with dictionaries.

OCLOMRS-1031:Your Organizations Sources shows user-owned sources

---

src/apps/concepts/components/MappingsTableRow.tsx

[Source disappears in answer section of a coded concept](https://issues.openmrs.org/browse/OCLOMRS-1028)
- For where `to_source_url` is null consider `to_concept_url` and modify it to suit the source options

OCLOMRS-1028: Source disappears in answer section of a coded concept

---

src/apps/concepts/pages/ViewConceptsPage.tsx

[Paging through the list of concepts no longer works](https://issues.openmrs.org/browse/OCLOMRS-1046)
- This fixes pagination, filtering and searching through concepts.

OCLOMRS-1046:Paging, searching and filtering through the list of concepts no longer works

---

src/apps/concepts/pages/ViewConceptPage.tsx

[Pick concepts - Go back button goes back to dictionary instead of search results](https://issues.openmrs.org/browse/OCLOMRS-1048)
- Modify the backUrl for when you are importing

OCLOMRS-1048: Back button goes back to dictionary instead of search results

---

src/apps/concepts/components/NamesTable.tsx
src/utils/constants.ts

[Avoid implying SYNONYM is a name type](https://issues.openmrs.org/browse/OCLOMRS-1054)
Name type of Synonym is displayed at the top in grey italic text with a bracket

OCLOMRS-1054:Avoid implying SYNONYM is a name type

---

src/apps/concepts/components/MappingsTable.tsx

[Add ability to reorder members in a concept set](https://issues.openmrs.org/browse/OCLOMRS-1068)
Reordering of set members feature is added

OCLOMRS-1068:Add ability to reorder members in a concept set

---

src/apps/containers/components/ContainerCard.tsx
src/apps/containers/components/ContainerCards.tsx

[OCLOMRS-1071 - Client UI improvements](https://issues.openmrs.org/browse/OCLOMRS-1071)
1. Card container height should be equal within each row of cards.
2. Text overflow within cards should be clipped with an ellipsis.
Effect:

OCLOMRS-1071: Client UI improvements

---

src/apps/concepts/pages/ViewConceptsPage.tsx

[Concepts belonging to dictionaries for my user aren't displayed](https://issues.openmrs.org/browse/OCLOMRS-1030)
I changed `collectionOwnerUrl=!${dictionary?.owner_url}` to `collectionOwnerUrl`. parameter

OCLOMRS-1030: Concepts belonging to dictionaries for my user aren't displayed
